//HintName: BindCommandDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindCommand on global::SharedScenarios.BindCommand.ObservableParam.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindCommand(
            this global::SharedScenarios.BindCommand.ObservableParam.MyView view,
            global::SharedScenarios.BindCommand.ObservableParam.MyViewModel? viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.ObservableParam.MyViewModel, global::System.Windows.Input.ICommand?>> propertyName,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.ObservableParam.MyView, global::SharedScenarios.BindCommand.ObservableParam.MyButton>> controlName,
            global::System.IObservable<string> withParameter,
            string? toEvent = null,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("propertyName")] string propertyNameExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("controlName")] string controlNameExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            if (propertyNameExpression == "x => x.Save"
                && controlNameExpression == "x => x.SaveButton")
            {
                return __BindCommand_00000F3AD26C97AB(view, viewModel, withParameter);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindCommand_00000F3AD26C97AB(
            global::SharedScenarios.BindCommand.ObservableParam.MyView view,
            global::SharedScenarios.BindCommand.ObservableParam.MyViewModel viewModel, global::System.IObservable<string> withParameter)
        {
            // BindCommand: Save -> SaveButton (event: Click)
            if (viewModel == null)
            {
                return global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
            }

            var __commandChangesMechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<global::System.Windows.Input.ICommand>(viewModel, "Save", (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindCommand.ObservableParam.MyViewModel)__o).Save, true);
        var __commandChangesRegistration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(viewModel.GetType(), "Save", 5, false);
        var __commandChanges = __commandChangesRegistration == null
            ? (global::System.IObservable<global::System.Windows.Input.ICommand>)__commandChangesMechanism
            : (global::System.IObservable<global::System.Windows.Input.ICommand>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<global::System.Windows.Input.ICommand>(
                __commandChangesRegistration,
                viewModel,
                ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.ObservableParam.MyViewModel, global::System.Windows.Input.ICommand>>)(__e => __e.Save)).Body,
                "Save",
                (object __o) => ((global::SharedScenarios.BindCommand.ObservableParam.MyViewModel)__o).Save,
                false,
                true);
            var commandObs = global::ReactiveUI.Binding.BindingSchedulers.ObserveOnViewThread(__commandChanges, view);
            var __controlChangesMechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<global::SharedScenarios.BindCommand.ObservableParam.MyButton>(view, "SaveButton", (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindCommand.ObservableParam.MyView)__o).SaveButton, true);
        var __controlChangesRegistration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(view.GetType(), "SaveButton", 5, false);
        var __controlChanges = __controlChangesRegistration == null
            ? (global::System.IObservable<global::SharedScenarios.BindCommand.ObservableParam.MyButton>)__controlChangesMechanism
            : (global::System.IObservable<global::SharedScenarios.BindCommand.ObservableParam.MyButton>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<global::SharedScenarios.BindCommand.ObservableParam.MyButton>(
                __controlChangesRegistration,
                view,
                ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.ObservableParam.MyView, global::SharedScenarios.BindCommand.ObservableParam.MyButton>>)(__e => __e.SaveButton)).Body,
                "SaveButton",
                (object __o) => ((global::SharedScenarios.BindCommand.ObservableParam.MyView)__o).SaveButton,
                false,
                true);
            var __controls = global::ReactiveUI.Binding.BindingSchedulers.ObserveOnViewThread(__controlChanges, view);
            var __controlBinding = new global::ReactiveUI.Primitives.Disposables.SwapDisposable();
            var __controlSub = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(__controls, __control =>
            {
                __controlBinding.Disposable = global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                if (__control != null)
                {
                    __controlBinding.Disposable = __BindCommandCore_00000F3AD26C97AB(__control, commandObs, withParameter);
                }
            });
            return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(__controlSub, __controlBinding);
        }

        private static global::System.IDisposable __BindCommandCore_00000F3AD26C97AB(global::SharedScenarios.BindCommand.ObservableParam.MyButton __control, global::System.IObservable<global::System.Windows.Input.ICommand> commandObs, global::System.IObservable<string> withParameter)
        {

            if (global::ReactiveUI.Binding.Fallback.CommandBindingAffinityChecker
                .HasHigherAffinityPlugin<global::SharedScenarios.BindCommand.ObservableParam.MyButton>(3, false))
            {
                var __customBinder = global::ReactiveUI.Binding.CommandBinding.CommandBinderService
                    .GetBinder<global::SharedScenarios.BindCommand.ObservableParam.MyButton>(false);
                if (__customBinder != null)
                {
                    var __serial = new global::ReactiveUI.Primitives.Disposables.SwapDisposable();
                    var __binderCmdSub = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(commandObs, __cmd =>
                    {
                        __serial.Disposable = global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                        global::System.IObservable<object> __paramObs = new global::ReactiveUI.Primitives.Signals.MapSignal<string, object>(withParameter, __p => __p);
                        __serial.Disposable = __customBinder.BindCommandToObject<global::SharedScenarios.BindCommand.ObservableParam.MyButton>(
                            __cmd, __control, __paramObs)
                            ?? global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                    });
                    return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(__binderCmdSub, __serial);
                }
            }

            string __latestParam = default(string);
        var __parameterGate = new object();
        var __hasParameter = false;
        var __argumentCached = false;
        object __argument = null;
        object __ReadParameter()
        {
            lock (__parameterGate)
            {
                if (!__hasParameter)
                {
                    return null;
                }
                if (!__argumentCached)
                {
                    __argument = __latestParam;
                    __argumentCached = true;
                }
                return __argument;
            }
        }
        var __paramSub = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(withParameter, __parameter =>
        {
            lock (__parameterGate)
            {
                __latestParam = __parameter;
                __hasParameter = true;
                __argumentCached = false;
            }
        });
            var serial = new global::ReactiveUI.Primitives.Disposables.SwapDisposable();
            var __cmdSub = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(commandObs, cmd =>
            {
                serial.Disposable = global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                if (cmd == null)
                {
                    return;
                }

                void __Handler(object? sender, global::System.EventArgs e)
                {
                    var param = __ReadParameter();
                    if (cmd.CanExecute(param))
                    {
                        cmd.Execute(param);
                    }
                }

                __control.Click += __Handler;
                serial.Disposable = new global::ReactiveUI.Primitives.Disposables.ActionDisposable(() =>
                    __control.Click -= __Handler);
            });
            return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(
                new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(__cmdSub, __paramSub), serial);
        }

    }
}
