//HintName: BindCommandDispatch.g.cs
// <auto-generated/>
#pragma warning disable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindCommand on global::SharedScenarios.BindCommand.ObservableParam.MyView.
        /// Uses CallerFilePath + CallerLineNumber for dispatch.
        /// </summary>
        public static global::System.IDisposable BindCommand(
            this global::SharedScenarios.BindCommand.ObservableParam.MyView view,
            global::SharedScenarios.BindCommand.ObservableParam.MyViewModel viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.ObservableParam.MyViewModel, global::System.Windows.Input.ICommand>> propertyName,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.ObservableParam.MyView, global::SharedScenarios.BindCommand.ObservableParam.MyButton>> controlName,
            global::System.IObservable<string> withParameter,
            string toEvent = null,
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            if (callerLineNumber == 92
                && callerFilePath.EndsWith("", global::System.StringComparison.OrdinalIgnoreCase))
            {
                return __BindCommand_00000F3AD26C997C(view, viewModel, withParameter);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindCommand_00000F3AD26C997C(
            global::SharedScenarios.BindCommand.ObservableParam.MyView view,
            global::SharedScenarios.BindCommand.ObservableParam.MyViewModel viewModel, global::System.IObservable<string> withParameter)
        {
            // BindCommand: Save -> SaveButton (event: Click)
            if (viewModel == null)
            {
                return global::ReactiveUI.Binding.Observables.EmptyDisposable.Instance;
            }

        var commandObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<global::System.Windows.Input.ICommand>(
            viewModel,
            "Save",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindCommand.ObservableParam.MyViewModel)__o).Save,
            true);

            var __customBinder = global::ReactiveUI.Binding.CommandBinding.CommandBinderService
                .GetBinder<global::SharedScenarios.BindCommand.ObservableParam.MyButton>(true);
            if (__customBinder != null)
            {
                var __serial = new global::ReactiveUI.Binding.Observables.SerialDisposable();
                var __binderCmdSub = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Subscribe(commandObs, __cmd =>
                {
                    __serial.Disposable = global::ReactiveUI.Binding.Observables.EmptyDisposable.Instance;
                    global::System.IObservable<object> __paramObs = new global::ReactiveUI.Binding.Observables.SelectObservable<string, object>(withParameter, __p => __p);
                    __serial.Disposable = __customBinder.BindCommandToObject<global::SharedScenarios.BindCommand.ObservableParam.MyButton>(
                        __cmd, view.SaveButton, __paramObs)
                        ?? global::ReactiveUI.Binding.Observables.EmptyDisposable.Instance;
                });
                return new global::ReactiveUI.Binding.Observables.CompositeDisposable2(__binderCmdSub, __serial);
            }


            string __latestParam = default;
            var __paramSub = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Subscribe(
                withParameter, p => System.Threading.Volatile.Write(ref __latestParam, p));

            var serial = new global::ReactiveUI.Binding.Observables.SerialDisposable();
            var __cmdSub = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Subscribe(commandObs, cmd =>
            {
                serial.Disposable = global::ReactiveUI.Binding.Observables.EmptyDisposable.Instance;
                if (cmd == null)
                {
                    return;
                }

                void __Handler(object sender, global::System.EventArgs e)
                {
                    var param = System.Threading.Volatile.Read(ref __latestParam);
                    if (cmd.CanExecute(param))
                    {
                        cmd.Execute(param);
                    }
                }

                view.SaveButton.Click += __Handler;
                serial.Disposable = new global::ReactiveUI.Binding.Observables.ActionDisposable(() =>
                    view.SaveButton.Click -= __Handler);
            });
            return new global::ReactiveUI.Binding.Observables.CompositeDisposable2(
                new global::ReactiveUI.Binding.Observables.CompositeDisposable2(__cmdSub, __paramSub), serial);
        }

    }
}
