//HintName: BindCommandDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindCommand on global::SharedScenarios.BindCommand.BasicNoParam.MyView.
        /// Uses CallerFilePath + CallerLineNumber for dispatch.
        /// </summary>
        public static global::System.IDisposable BindCommand(
            this global::SharedScenarios.BindCommand.BasicNoParam.MyView view,
            global::SharedScenarios.BindCommand.BasicNoParam.MyViewModel viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.BasicNoParam.MyViewModel, global::System.Windows.Input.ICommand?>> propertyName,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.BasicNoParam.MyView, global::SharedScenarios.BindCommand.BasicNoParam.MyButton>> controlName,
            string? toEvent = null,
            string propertyNameExpression = "",
            string controlNameExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            if (callerLineNumber == 76
                && callerFilePath.EndsWith("", global::System.StringComparison.OrdinalIgnoreCase))
            {
                return __BindCommand_7FFFF69B2C59DF80(view, viewModel);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindCommand_7FFFF69B2C59DF80(
            global::SharedScenarios.BindCommand.BasicNoParam.MyView view,
            global::SharedScenarios.BindCommand.BasicNoParam.MyViewModel viewModel)
        {
            // BindCommand: Save -> SaveButton (event: Click)
            if (viewModel == null)
            {
                return global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
            }

        var commandObsMechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<global::System.Windows.Input.ICommand>(
            viewModel,
            "Save",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindCommand.BasicNoParam.MyViewModel)__o).Save,
            true);
        var commandObsRegistration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(typeof(global::SharedScenarios.BindCommand.BasicNoParam.MyViewModel), "Save", 5, false);
        var commandObs = commandObsRegistration == null
            ? (global::System.IObservable<global::System.Windows.Input.ICommand>)commandObsMechanism
            : (global::System.IObservable<global::System.Windows.Input.ICommand>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<global::System.Windows.Input.ICommand>(
                commandObsRegistration,
                viewModel,
                ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.BasicNoParam.MyViewModel, global::System.Windows.Input.ICommand>>)(__e => __e.Save)).Body,
                "Save",
                (object __o) => ((global::SharedScenarios.BindCommand.BasicNoParam.MyViewModel)__o).Save,
                false,
                true);

            if (global::ReactiveUI.Binding.Fallback.CommandBindingAffinityChecker
                .HasHigherAffinityPlugin<global::SharedScenarios.BindCommand.BasicNoParam.MyButton>(3, true))
            {
                var __customBinder = global::ReactiveUI.Binding.CommandBinding.CommandBinderService
                    .GetBinder<global::SharedScenarios.BindCommand.BasicNoParam.MyButton>(true);
                if (__customBinder != null)
                {
                    var __serial = new global::ReactiveUI.Primitives.Disposables.SwapDisposable();
                    var __binderCmdSub = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(commandObs, __cmd =>
                    {
                        __serial.Disposable = global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                        global::System.IObservable<object> __paramObs = global::ReactiveUI.Primitives.Advanced.ImmutableEmptySignal<object>.Instance;
                        __serial.Disposable = __customBinder.BindCommandToObject<global::SharedScenarios.BindCommand.BasicNoParam.MyButton>(
                            __cmd, view.SaveButton, __paramObs)
                            ?? global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                    });
                    return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(__binderCmdSub, __serial);
                }
            }


            var serial = new global::ReactiveUI.Primitives.Disposables.SwapDisposable();
            var __cmdSub = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(commandObs, cmd =>
            {
                serial.Disposable = global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                if (cmd == null)
                {
                    return;
                }

                void __Handler(object? sender, global::System.EventArgs e)
                {
                    if (cmd.CanExecute(null))
                    {
                        cmd.Execute(null);
                    }
                }

                view.SaveButton.Click += __Handler;
                serial.Disposable = new global::ReactiveUI.Primitives.Disposables.ActionDisposable(() =>
                    view.SaveButton.Click -= __Handler);
            });
            return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(__cmdSub, serial);
        }

    }
}
