//HintName: BindCommandDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindCommand on global::SharedScenarios.BindCommand.CommandProperty.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindCommand(
            this global::SharedScenarios.BindCommand.CommandProperty.MyView view,
            global::SharedScenarios.BindCommand.CommandProperty.MyViewModel? viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.CommandProperty.MyViewModel, global::System.Windows.Input.ICommand?>> propertyName,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.CommandProperty.MyView, global::SharedScenarios.BindCommand.CommandProperty.WpfLikeButton>> controlName,
            string? toEvent = null,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("propertyName")] string propertyNameExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("controlName")] string controlNameExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            if (propertyNameExpression == "x => x.Save"
                && controlNameExpression == "x => x.SaveButton")
            {
                return __BindCommand_00000A6C4A2CDDAA(view, viewModel);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindCommand_00000A6C4A2CDDAA(
            global::SharedScenarios.BindCommand.CommandProperty.MyView view,
            global::SharedScenarios.BindCommand.CommandProperty.MyViewModel viewModel)
        {
            // BindCommand: Save -> SaveButton (event: none)
            if (viewModel == null)
            {
                return global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
            }

            var __commandChangesMechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<global::System.Windows.Input.ICommand>(viewModel, "Save", (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindCommand.CommandProperty.MyViewModel)__o).Save, true);
        var __commandChangesRegistration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(viewModel.GetType(), "Save", 5, false);
        var __commandChanges = __commandChangesRegistration == null
            ? (global::System.IObservable<global::System.Windows.Input.ICommand>)__commandChangesMechanism
            : (global::System.IObservable<global::System.Windows.Input.ICommand>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<global::System.Windows.Input.ICommand>(
                __commandChangesRegistration,
                viewModel,
                ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.CommandProperty.MyViewModel, global::System.Windows.Input.ICommand>>)(__e => __e.Save)).Body,
                "Save",
                (object __o) => ((global::SharedScenarios.BindCommand.CommandProperty.MyViewModel)__o).Save,
                false,
                true);
            var commandObs = global::ReactiveUI.Binding.BindingSchedulers.ObserveOnViewThread(__commandChanges, view);
            var __controlChangesMechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<global::SharedScenarios.BindCommand.CommandProperty.WpfLikeButton>(view, "SaveButton", (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindCommand.CommandProperty.MyView)__o).SaveButton, true);
        var __controlChangesRegistration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(view.GetType(), "SaveButton", 5, false);
        var __controlChanges = __controlChangesRegistration == null
            ? (global::System.IObservable<global::SharedScenarios.BindCommand.CommandProperty.WpfLikeButton>)__controlChangesMechanism
            : (global::System.IObservable<global::SharedScenarios.BindCommand.CommandProperty.WpfLikeButton>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<global::SharedScenarios.BindCommand.CommandProperty.WpfLikeButton>(
                __controlChangesRegistration,
                view,
                ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.CommandProperty.MyView, global::SharedScenarios.BindCommand.CommandProperty.WpfLikeButton>>)(__e => __e.SaveButton)).Body,
                "SaveButton",
                (object __o) => ((global::SharedScenarios.BindCommand.CommandProperty.MyView)__o).SaveButton,
                false,
                true);
            var __controls = global::ReactiveUI.Binding.BindingSchedulers.ObserveOnViewThread(__controlChanges, view);
            var __controlBinding = new global::ReactiveUI.Primitives.Disposables.SwapDisposable();
            var __controlSub = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(__controls, __control =>
            {
                __controlBinding.Disposable = global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                if (__control != null)
                {
                    __controlBinding.Disposable = __BindCommandCore_00000A6C4A2CDDAA(__control, commandObs);
                }
            });
            return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(__controlSub, __controlBinding);
        }

        private static global::System.IDisposable __BindCommandCore_00000A6C4A2CDDAA(global::SharedScenarios.BindCommand.CommandProperty.WpfLikeButton __control, global::System.IObservable<global::System.Windows.Input.ICommand> commandObs)
        {

            if (global::ReactiveUI.Binding.Fallback.CommandBindingAffinityChecker
                .HasHigherAffinityPlugin<global::SharedScenarios.BindCommand.CommandProperty.WpfLikeButton>(5, false))
            {
                var __customBinder = global::ReactiveUI.Binding.CommandBinding.CommandBinderService
                    .GetBinder<global::SharedScenarios.BindCommand.CommandProperty.WpfLikeButton>(false);
                if (__customBinder != null)
                {
                    var __serial = new global::ReactiveUI.Primitives.Disposables.SwapDisposable();
                    var __binderCmdSub = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(commandObs, __cmd =>
                    {
                        __serial.Disposable = global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                        global::System.IObservable<object> __paramObs = global::ReactiveUI.Primitives.Advanced.ImmutableEmptySignal<object>.Instance;
                        __serial.Disposable = __customBinder.BindCommandToObject<global::SharedScenarios.BindCommand.CommandProperty.WpfLikeButton>(
                            __cmd, __control, __paramObs)
                            ?? global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                    });
                    return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(__binderCmdSub, __serial);
                }
            }


            var __originalCommand = __control.Command;
            var __originalParameter = __control.CommandParameter;
            var serial = new global::ReactiveUI.Primitives.Disposables.SwapDisposable();
            var __cmdSub = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(commandObs, cmd =>
            {
                serial.Disposable = global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                __control.Command = cmd;
            });

            return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(
                new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(__cmdSub, serial),
                new global::ReactiveUI.Primitives.Disposables.ActionDisposable(() =>
                {
                    __control.CommandParameter = __originalParameter;
                    __control.Command = __originalCommand;
                }));
        }

    }
}
