//HintName: BindCommandDispatch.g.cs
// <auto-generated/>
#pragma warning disable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindCommand on global::SharedScenarios.BindCommand.CustomEvent.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindCommand(
            this global::SharedScenarios.BindCommand.CustomEvent.MyView view,
            global::SharedScenarios.BindCommand.CustomEvent.MyViewModel viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.CustomEvent.MyViewModel, global::System.Windows.Input.ICommand>> propertyName,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.CustomEvent.MyView, global::SharedScenarios.BindCommand.CustomEvent.MyButton>> controlName,
            string toEvent = null,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("propertyName")] string propertyNameExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("controlName")] string controlNameExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            propertyNameExpression = propertyNameExpression.StartsWith("static ") ? propertyNameExpression.Substring(7) : propertyNameExpression;
            controlNameExpression = controlNameExpression.StartsWith("static ") ? controlNameExpression.Substring(7) : controlNameExpression;

            if (propertyNameExpression == "x => x.Save"
                && controlNameExpression == "x => x.SaveButton")
            {
                return __BindCommand_000010E3246572AA(view, viewModel);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindCommand_000010E3246572AA(
            global::SharedScenarios.BindCommand.CustomEvent.MyView view,
            global::SharedScenarios.BindCommand.CustomEvent.MyViewModel viewModel)
        {
            // BindCommand: Save -> SaveButton (event: MouseUp)
            if (viewModel == null)
            {
                return global::ReactiveUI.Binding.Observables.EmptyDisposable.Instance;
            }

        var commandObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<global::System.Windows.Input.ICommand>(
            viewModel,
            "Save",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindCommand.CustomEvent.MyViewModel)__o).Save,
            true);

            if (global::ReactiveUI.Binding.Fallback.CommandBindingAffinityChecker
                .HasHigherAffinityPlugin<global::SharedScenarios.BindCommand.CustomEvent.MyButton>(3, true))
            {
                var __customBinder = global::ReactiveUI.Binding.CommandBinding.CommandBinderService
                    .GetBinder<global::SharedScenarios.BindCommand.CustomEvent.MyButton>(true);
                if (__customBinder != null)
                {
                    var __serial = new global::ReactiveUI.Binding.Observables.SerialDisposable();
                    var __binderCmdSub = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Subscribe(commandObs, __cmd =>
                    {
                        __serial.Disposable = global::ReactiveUI.Binding.Observables.EmptyDisposable.Instance;
                        global::System.IObservable<object> __paramObs = global::ReactiveUI.Binding.Observables.EmptyObservable<object>.Instance;
                        __serial.Disposable = __customBinder.BindCommandToObject<global::SharedScenarios.BindCommand.CustomEvent.MyButton>(
                            __cmd, view.SaveButton, __paramObs)
                            ?? global::ReactiveUI.Binding.Observables.EmptyDisposable.Instance;
                    });
                    return new global::ReactiveUI.Binding.Observables.CompositeDisposable2(__binderCmdSub, __serial);
                }
            }


            var serial = new global::ReactiveUI.Binding.Observables.SerialDisposable();
            var __cmdSub = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Subscribe(commandObs, cmd =>
            {
                serial.Disposable = global::ReactiveUI.Binding.Observables.EmptyDisposable.Instance;
                if (cmd == null)
                {
                    return;
                }

                void __Handler(object sender, global::System.EventArgs e)
                {
                    if (cmd.CanExecute(null))
                    {
                        cmd.Execute(null);
                    }
                }

                view.SaveButton.MouseUp += __Handler;
                serial.Disposable = new global::ReactiveUI.Binding.Observables.ActionDisposable(() =>
                    view.SaveButton.MouseUp -= __Handler);
            });
            return new global::ReactiveUI.Binding.Observables.CompositeDisposable2(__cmdSub, serial);
        }

    }
}
