//HintName: BindCommandDispatch.g.cs
// <auto-generated/>
#pragma warning disable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindCommand on global::SharedScenarios.BindCommand.EventEnabledExprParam.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindCommand(
            this global::SharedScenarios.BindCommand.EventEnabledExprParam.MyView view,
            global::SharedScenarios.BindCommand.EventEnabledExprParam.MyViewModel viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.EventEnabledExprParam.MyViewModel, global::System.Windows.Input.ICommand>> propertyName,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.EventEnabledExprParam.MyView, global::SharedScenarios.BindCommand.EventEnabledExprParam.WinFormsLikeButton>> controlName,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.EventEnabledExprParam.MyViewModel, string>> withParameter,
            string toEvent = null,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("propertyName")] string propertyNameExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("controlName")] string controlNameExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("withParameter")] string withParameterExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            propertyNameExpression = propertyNameExpression.StartsWith("static ") ? propertyNameExpression.Substring(7) : propertyNameExpression;
            controlNameExpression = controlNameExpression.StartsWith("static ") ? controlNameExpression.Substring(7) : controlNameExpression;

            if (propertyNameExpression == "x => x.Save"
                && controlNameExpression == "x => x.SaveButton")
            {
                return __BindCommand_00001A92FB3E1BAE(view, viewModel, withParameter);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindCommand_00001A92FB3E1BAE(
            global::SharedScenarios.BindCommand.EventEnabledExprParam.MyView view,
            global::SharedScenarios.BindCommand.EventEnabledExprParam.MyViewModel viewModel, global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.EventEnabledExprParam.MyViewModel, string>> withParameter)
        {
            // BindCommand: Save -> SaveButton (event: Click)
            if (viewModel == null)
            {
                return global::ReactiveUI.Binding.Observables.EmptyDisposable.Instance;
            }

        var commandObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<global::System.Windows.Input.ICommand>(
            viewModel,
            "Save",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindCommand.EventEnabledExprParam.MyViewModel)__o).Save,
            true);

            if (global::ReactiveUI.Binding.Fallback.CommandBindingAffinityChecker
                .HasHigherAffinityPlugin<global::SharedScenarios.BindCommand.EventEnabledExprParam.WinFormsLikeButton>(4, true))
            {
                var __customBinder = global::ReactiveUI.Binding.CommandBinding.CommandBinderService
                    .GetBinder<global::SharedScenarios.BindCommand.EventEnabledExprParam.WinFormsLikeButton>(true);
                if (__customBinder != null)
                {
                    var __serial = new global::ReactiveUI.Binding.Observables.SerialDisposable();
                    var __binderCmdSub = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Subscribe(commandObs, __cmd =>
                    {
                        __serial.Disposable = global::ReactiveUI.Binding.Observables.EmptyDisposable.Instance;
                        global::System.IObservable<object> __paramObs = new global::ReactiveUI.Binding.Observables.ReturnObservable<object>(viewModel.CurrentItem);
                        __serial.Disposable = __customBinder.BindCommandToObject<global::SharedScenarios.BindCommand.EventEnabledExprParam.WinFormsLikeButton>(
                            __cmd, view.SaveButton, __paramObs)
                            ?? global::ReactiveUI.Binding.Observables.EmptyDisposable.Instance;
                    });
                    return new global::ReactiveUI.Binding.Observables.CompositeDisposable2(__binderCmdSub, __serial);
                }
            }


            var serial = new global::ReactiveUI.Binding.Observables.SerialDisposable();
            var __cmdSub = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Subscribe(commandObs, cmd =>
            {
                serial.Disposable = global::ReactiveUI.Binding.Observables.EmptyDisposable.Instance;
                if (cmd == null)
                {
                    view.SaveButton.Enabled = false;
                    return;
                }

                view.SaveButton.Enabled = cmd.CanExecute(viewModel.CurrentItem);
                global::System.EventHandler __canExecHandler = (s, e) =>
                    view.SaveButton.Enabled = cmd.CanExecute(viewModel.CurrentItem);
                cmd.CanExecuteChanged += __canExecHandler;

                void __Handler(object sender, global::System.EventArgs e)
                {
                    var param = viewModel.CurrentItem;
                    if (cmd.CanExecute(param))
                    {
                        cmd.Execute(param);
                    }
                }

                view.SaveButton.Click += __Handler;
                serial.Disposable = new global::ReactiveUI.Binding.Observables.ActionDisposable(() =>
                {
                    view.SaveButton.Click -= __Handler;
                    cmd.CanExecuteChanged -= __canExecHandler;
                });
            });
            return new global::ReactiveUI.Binding.Observables.CompositeDisposable2(__cmdSub, serial);
        }

    }
}
