//HintName: BindCommandDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindCommand on global::SharedScenarios.BindCommand.EventEnabledObsParam.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindCommand(
            this global::SharedScenarios.BindCommand.EventEnabledObsParam.MyView view,
            global::SharedScenarios.BindCommand.EventEnabledObsParam.MyViewModel viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.EventEnabledObsParam.MyViewModel, global::System.Windows.Input.ICommand?>> propertyName,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.EventEnabledObsParam.MyView, global::SharedScenarios.BindCommand.EventEnabledObsParam.WinFormsLikeButton>> controlName,
            global::System.IObservable<string> withParameter,
            string? toEvent = null,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("propertyName")] string propertyNameExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("controlName")] string controlNameExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            propertyNameExpression = propertyNameExpression.StartsWith("static ", global::System.StringComparison.Ordinal)
                ? propertyNameExpression.Substring(7)
                : propertyNameExpression;
            controlNameExpression = controlNameExpression.StartsWith("static ", global::System.StringComparison.Ordinal)
                ? controlNameExpression.Substring(7)
                : controlNameExpression;

            if (propertyNameExpression == "x => x.Save"
                && controlNameExpression == "x => x.SaveButton")
            {
                return __BindCommand_00001723A43D0363(view, viewModel, withParameter);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindCommand_00001723A43D0363(
            global::SharedScenarios.BindCommand.EventEnabledObsParam.MyView view,
            global::SharedScenarios.BindCommand.EventEnabledObsParam.MyViewModel viewModel, global::System.IObservable<string> withParameter)
        {
            // BindCommand: Save -> SaveButton (event: Click)
            if (viewModel == null)
            {
                return global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
            }

        var commandObsMechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<global::System.Windows.Input.ICommand>(
            viewModel,
            "Save",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindCommand.EventEnabledObsParam.MyViewModel)__o).Save,
            true);
        var commandObsRegistration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(typeof(global::SharedScenarios.BindCommand.EventEnabledObsParam.MyViewModel), "Save", 5, false);
        var commandObs = commandObsRegistration == null
            ? (global::System.IObservable<global::System.Windows.Input.ICommand>)commandObsMechanism
            : (global::System.IObservable<global::System.Windows.Input.ICommand>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<global::System.Windows.Input.ICommand>(
                commandObsRegistration,
                viewModel,
                ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.EventEnabledObsParam.MyViewModel, global::System.Windows.Input.ICommand>>)(__e => __e.Save)).Body,
                "Save",
                (object __o) => ((global::SharedScenarios.BindCommand.EventEnabledObsParam.MyViewModel)__o).Save,
                false,
                true);

            if (global::ReactiveUI.Binding.Fallback.CommandBindingAffinityChecker
                .HasHigherAffinityPlugin<global::SharedScenarios.BindCommand.EventEnabledObsParam.WinFormsLikeButton>(4, true))
            {
                var __customBinder = global::ReactiveUI.Binding.CommandBinding.CommandBinderService
                    .GetBinder<global::SharedScenarios.BindCommand.EventEnabledObsParam.WinFormsLikeButton>(true);
                if (__customBinder != null)
                {
                    var __serial = new global::ReactiveUI.Primitives.Disposables.SwapDisposable();
                    var __binderCmdSub = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(commandObs, __cmd =>
                    {
                        __serial.Disposable = global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                        global::System.IObservable<object> __paramObs = new global::ReactiveUI.Primitives.Signals.MapSignal<string, object>(withParameter, __p => __p);
                        __serial.Disposable = __customBinder.BindCommandToObject<global::SharedScenarios.BindCommand.EventEnabledObsParam.WinFormsLikeButton>(
                            __cmd, view.SaveButton, __paramObs)
                            ?? global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                    });
                    return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(__binderCmdSub, __serial);
                }
            }


            string? __latestParam = default;
            var __paramSub = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(
                withParameter, p => global::System.Threading.Volatile.Write(ref __latestParam, p));

            var serial = new global::ReactiveUI.Primitives.Disposables.SwapDisposable();
            var __cmdSub = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(commandObs, cmd =>
            {
                serial.Disposable = global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                if (cmd == null)
                {
                    view.SaveButton.Enabled = false;
                    return;
                }

                var param = global::System.Threading.Volatile.Read(ref __latestParam);
                view.SaveButton.Enabled = cmd.CanExecute(param);
                global::System.EventHandler __canExecHandler = (s, e) =>
                    view.SaveButton.Enabled = cmd.CanExecute(global::System.Threading.Volatile.Read(ref __latestParam));
                cmd.CanExecuteChanged += __canExecHandler;

                void __Handler(object? sender, global::System.EventArgs e)
                {
                    var p = global::System.Threading.Volatile.Read(ref __latestParam);
                    if (cmd.CanExecute(p))
                    {
                        cmd.Execute(p);
                    }
                }

                view.SaveButton.Click += __Handler;
                serial.Disposable = new global::ReactiveUI.Primitives.Disposables.ActionDisposable(() =>
                {
                    view.SaveButton.Click -= __Handler;
                    cmd.CanExecuteChanged -= __canExecHandler;
                });
            });
            return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(
                new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(__cmdSub, __paramSub), serial);
        }

    }
}
