//HintName: BindCommandDispatch.g.cs
// <auto-generated/>
#pragma warning disable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindCommand on global::SharedScenarios.BindCommand.CommandPropertyObsParam.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindCommand(
            this global::SharedScenarios.BindCommand.CommandPropertyObsParam.MyView view,
            global::SharedScenarios.BindCommand.CommandPropertyObsParam.MyViewModel viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.CommandPropertyObsParam.MyViewModel, global::System.Windows.Input.ICommand>> propertyName,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.CommandPropertyObsParam.MyView, global::SharedScenarios.BindCommand.CommandPropertyObsParam.WpfLikeButton>> controlName,
            global::System.IObservable<string> withParameter,
            string toEvent = null,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("propertyName")] string propertyNameExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("controlName")] string controlNameExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            propertyNameExpression = propertyNameExpression.StartsWith("static ") ? propertyNameExpression.Substring(7) : propertyNameExpression;
            controlNameExpression = controlNameExpression.StartsWith("static ") ? controlNameExpression.Substring(7) : controlNameExpression;

            if (propertyNameExpression == "x => x.Save"
                && controlNameExpression == "x => x.SaveButton")
            {
                return __BindCommand_000025BD0B2B0246(view, viewModel, withParameter);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindCommand_000025BD0B2B0246(
            global::SharedScenarios.BindCommand.CommandPropertyObsParam.MyView view,
            global::SharedScenarios.BindCommand.CommandPropertyObsParam.MyViewModel viewModel, global::System.IObservable<string> withParameter)
        {
            // BindCommand: Save -> SaveButton (event: none)
            if (viewModel == null)
            {
                return global::ReactiveUI.Binding.Observables.EmptyDisposable.Instance;
            }

        var commandObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<global::System.Windows.Input.ICommand>(
            viewModel,
            "Save",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindCommand.CommandPropertyObsParam.MyViewModel)__o).Save,
            true);

            string __latestParam = default;
            var __paramSub = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Subscribe(
                withParameter, p => System.Threading.Volatile.Write(ref __latestParam, p));

            var serial = new global::ReactiveUI.Binding.Observables.SerialDisposable();
            var __cmdSub = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Subscribe(commandObs, cmd =>
            {
                serial.Disposable = global::ReactiveUI.Binding.Observables.EmptyDisposable.Instance;
                view.SaveButton.Command = cmd;
                var param = System.Threading.Volatile.Read(ref __latestParam);
                view.SaveButton.CommandParameter = param;
                if (cmd != null)
                {
                    serial.Disposable = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Subscribe(
                        withParameter, p =>
                        {
                            System.Threading.Volatile.Write(ref __latestParam, p);
                            view.SaveButton.CommandParameter = p;
                        });
                }
            });
            return new global::ReactiveUI.Binding.Observables.CompositeDisposable2(
                new global::ReactiveUI.Binding.Observables.CompositeDisposable2(__cmdSub, __paramSub), serial);
        }

    }
}
