//HintName: BindCommandDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindCommand on global::SharedScenarios.BindCommand.DeepCommandPath.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindCommand(
            this global::SharedScenarios.BindCommand.DeepCommandPath.MyView view,
            global::SharedScenarios.BindCommand.DeepCommandPath.MyViewModel viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.DeepCommandPath.MyViewModel, global::System.Windows.Input.ICommand?>> propertyName,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindCommand.DeepCommandPath.MyView, global::SharedScenarios.BindCommand.DeepCommandPath.MyButton>> controlName,
            string? toEvent = null,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("propertyName")] string propertyNameExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("controlName")] string controlNameExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            propertyNameExpression = propertyNameExpression.StartsWith("static ") ? propertyNameExpression.Substring(7) : propertyNameExpression;
            controlNameExpression = controlNameExpression.StartsWith("static ") ? controlNameExpression.Substring(7) : controlNameExpression;

            if (propertyNameExpression == "x => x.Child!.SaveCommand"
                && controlNameExpression == "x => x.SaveButton")
            {
                return __BindCommand_7FFFEA7C178C3571(view, viewModel);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindCommand_7FFFEA7C178C3571(
            global::SharedScenarios.BindCommand.DeepCommandPath.MyView view,
            global::SharedScenarios.BindCommand.DeepCommandPath.MyViewModel viewModel)
        {
            // BindCommand: Child.SaveCommand -> SaveButton (event: Click)
            if (viewModel == null)
            {
                return global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
            }

            var __commandObs_s0 = (global::System.IObservable<global::SharedScenarios.BindCommand.DeepCommandPath.ChildViewModel>)new global::ReactiveUI.Binding.Observables.PropertyObservable<global::SharedScenarios.BindCommand.DeepCommandPath.ChildViewModel>(
                viewModel,
                "Child",
                (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindCommand.DeepCommandPath.MyViewModel)__o).Child,
                false);

        var __commandObs_s1 = new global::ReactiveUI.Primitives.Advanced.SwitchMapSignal<global::SharedScenarios.BindCommand.DeepCommandPath.ChildViewModel, global::System.Windows.Input.ICommand>(__commandObs_s0,
            __p1 => __p1 != null
                ? (global::System.IObservable<global::System.Windows.Input.ICommand>)new global::ReactiveUI.Binding.Observables.PropertyObservable<global::System.Windows.Input.ICommand>(
                    (global::System.ComponentModel.INotifyPropertyChanged)__p1,
                    "SaveCommand",
                    (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindCommand.DeepCommandPath.ChildViewModel)__o).SaveCommand,
                    false)
                : (global::System.IObservable<global::System.Windows.Input.ICommand>)new global::ReactiveUI.Binding.Observables.ReturnObservable<global::System.Windows.Input.ICommand>(default(global::System.Windows.Input.ICommand)));
        var commandObs = global::ReactiveUI.Primitives.LinqExtensions.DistinctUntilChanged(__commandObs_s1);

            if (global::ReactiveUI.Binding.Fallback.CommandBindingAffinityChecker
                .HasHigherAffinityPlugin<global::SharedScenarios.BindCommand.DeepCommandPath.MyButton>(3, true))
            {
                var __customBinder = global::ReactiveUI.Binding.CommandBinding.CommandBinderService
                    .GetBinder<global::SharedScenarios.BindCommand.DeepCommandPath.MyButton>(true);
                if (__customBinder != null)
                {
                    var __serial = new global::ReactiveUI.Primitives.Disposables.SwapDisposable();
                    var __binderCmdSub = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(commandObs, __cmd =>
                    {
                        __serial.Disposable = global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                        global::System.IObservable<object> __paramObs = global::ReactiveUI.Binding.Observables.EmptyObservable<object>.Instance;
                        __serial.Disposable = __customBinder.BindCommandToObject<global::SharedScenarios.BindCommand.DeepCommandPath.MyButton>(
                            __cmd, view.SaveButton, __paramObs)
                            ?? global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                    });
                    return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(__binderCmdSub, __serial);
                }
            }


            var serial = new global::ReactiveUI.Primitives.Disposables.SwapDisposable();
            var __cmdSub = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(commandObs, cmd =>
            {
                serial.Disposable = global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                if (cmd == null)
                {
                    return;
                }

                void __Handler(object? sender, global::System.EventArgs e)
                {
                    if (cmd.CanExecute(null))
                    {
                        cmd.Execute(null);
                    }
                }

                view.SaveButton.Click += __Handler;
                serial.Disposable = new global::ReactiveUI.Primitives.Disposables.ActionDisposable(() =>
                    view.SaveButton.Click -= __Handler);
            });
            return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(__cmdSub, serial);
        }

    }
}
