//HintName: BindDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for Bind from global::SharedScenarios.Bind.SinglePropertyWithConvertersAndScheduler.MyViewModel to global::SharedScenarios.Bind.SinglePropertyWithConvertersAndScheduler.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::ReactiveUI.Binding.IReactiveBinding<global::SharedScenarios.Bind.SinglePropertyWithConvertersAndScheduler.MyView, global::ReactiveUI.Binding.BindingChange> Bind(
            this global::SharedScenarios.Bind.SinglePropertyWithConvertersAndScheduler.MyView view,
            global::SharedScenarios.Bind.SinglePropertyWithConvertersAndScheduler.MyViewModel viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.Bind.SinglePropertyWithConvertersAndScheduler.MyViewModel, int>> viewModelProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.Bind.SinglePropertyWithConvertersAndScheduler.MyView, string?>> viewProperty,
            global::System.Func<int, string> viewModelToViewConverter,
            global::System.Func<string, int> viewToViewModelConverter,
            global::ReactiveUI.Primitives.Concurrency.ISequencer scheduler,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("viewModelProperty")] string viewModelPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("viewProperty")] string viewPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            // A registered plugin that outranks the generated one drives the binding instead
            if (global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.HasHigherAffinityPlugin(typeof(global::SharedScenarios.Bind.SinglePropertyWithConvertersAndScheduler.MyViewModel), "Count", 5, false)
                || global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.HasHigherAffinityPlugin(typeof(global::SharedScenarios.Bind.SinglePropertyWithConvertersAndScheduler.MyView), "CountText", 5, false))
            {
                return global::ReactiveUI.Binding.Fallback.RuntimeBindingFallback.Bind(
                    view, viewModel, viewModelProperty, viewProperty, global::ReactiveUI.Binding.Fallback.TwoWayConverters.Create(viewModelToViewConverter, viewToViewModelConverter), scheduler, viewPropertyExpression);
            }

            if (viewModelPropertyExpression == "x => x.Count"
                && viewPropertyExpression == "x => x.CountText")
            {
                return __Bind_7FFFD53F4944055D(viewModel, view, viewModelToViewConverter, viewToViewModelConverter, scheduler);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::ReactiveUI.Binding.IReactiveBinding<global::SharedScenarios.Bind.SinglePropertyWithConvertersAndScheduler.MyView, global::ReactiveUI.Binding.BindingChange> __Bind_7FFFD53F4944055D(global::SharedScenarios.Bind.SinglePropertyWithConvertersAndScheduler.MyViewModel viewModel, global::SharedScenarios.Bind.SinglePropertyWithConvertersAndScheduler.MyView view, global::System.Func<int, string> viewModelToViewConverter, global::System.Func<string, int> viewToViewModelConverter, global::ReactiveUI.Primitives.Concurrency.ISequencer scheduler)
        {
            // Bind: Count <-> CountText (with conversion) (with scheduler)
        if (global::ReactiveUI.Binding.BindingHooks.Any
            && !global::ReactiveUI.Binding.BindingHooks.ShouldBind(
                viewModel,
                view,
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(viewModel, null, viewModel),
                },
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(view, null, view),
                },
                global::ReactiveUI.Binding.BindingDirection.TwoWay))
        {
            return null;
        }
        var vmObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<int>(
            viewModel,
            "Count",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.Bind.SinglePropertyWithConvertersAndScheduler.MyViewModel)__o).Count,
            true);
        var viewObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
            view,
            "CountText",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.Bind.SinglePropertyWithConvertersAndScheduler.MyView)__o).CountText,
            true);
        var __vmSelected = new global::ReactiveUI.Primitives.Signals.MapSignal<int, string>(vmObs, viewModelToViewConverter);
        var __viewSelected = new global::ReactiveUI.Primitives.Signals.MapSignal<string, int>(viewObs, viewToViewModelConverter);
        var vmBind = global::ReactiveUI.Primitives.LinqExtensions.ObserveOn<string>(__vmSelected, scheduler);
        var viewBind = global::ReactiveUI.Primitives.LinqExtensions.ObserveOn<int>(__viewSelected, scheduler);

            var d1 = global::ReactiveUI.Binding.BindingErrors.Subscribe(vmBind, value =>
            {
                if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(view.CountText, value))
                {
                    return;
                }

                view.CountText = value;
            }, "x => x.CountText");

            var __viewSkipped = global::ReactiveUI.Primitives.LinqExtensions.Skip(viewBind, 1);
            var d2 = global::ReactiveUI.Binding.BindingErrors.Subscribe(__viewSkipped, value =>
            {
                if (global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(viewModel.Count, value))
                {
                    return;
                }

                viewModel.Count = value;
            }, "x => x.Count");

            var __vmTagged = new global::ReactiveUI.Primitives.Signals.MapSignal<string, global::ReactiveUI.Binding.BindingChange>(vmBind, v => new global::ReactiveUI.Binding.BindingChange(v, true));
            var __viewTagged = new global::ReactiveUI.Primitives.Signals.MapSignal<int, global::ReactiveUI.Binding.BindingChange>(__viewSkipped, v => new global::ReactiveUI.Binding.BindingChange(v, false));
            var changed = new global::ReactiveUI.Primitives.Advanced.MergeSignal<global::ReactiveUI.Binding.BindingChange>(__vmTagged, __viewTagged);

            var disposable = new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(d1, d2);

            return new global::ReactiveUI.Binding.ReactiveBinding<global::SharedScenarios.Bind.SinglePropertyWithConvertersAndScheduler.MyView, global::ReactiveUI.Binding.BindingChange>(
                view,
                changed,
                global::ReactiveUI.Binding.BindingDirection.TwoWay,
                disposable);
        }

    }
}
