//HintName: BindDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for Bind from global::SharedScenarios.Bind.SinglePropertyStringToString.MyViewModel to global::SharedScenarios.Bind.SinglePropertyStringToString.MyView.
        /// Uses CallerFilePath + CallerLineNumber for dispatch.
        /// </summary>
        public static global::ReactiveUI.Binding.IReactiveBinding<global::SharedScenarios.Bind.SinglePropertyStringToString.MyView, (object? View, bool IsViewModel)> Bind(
            this global::SharedScenarios.Bind.SinglePropertyStringToString.MyView view,
            global::SharedScenarios.Bind.SinglePropertyStringToString.MyViewModel viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.Bind.SinglePropertyStringToString.MyViewModel, string?>> viewModelProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.Bind.SinglePropertyStringToString.MyView, string?>> viewProperty,
            string viewModelPropertyExpression = "",
            string viewPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            if (callerLineNumber == 77
                && callerFilePath.EndsWith("", global::System.StringComparison.OrdinalIgnoreCase))
            {
                return __Bind_000011908961B668(viewModel, view);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::ReactiveUI.Binding.IReactiveBinding<global::SharedScenarios.Bind.SinglePropertyStringToString.MyView, (object? View, bool IsViewModel)> __Bind_000011908961B668(global::SharedScenarios.Bind.SinglePropertyStringToString.MyViewModel viewModel, global::SharedScenarios.Bind.SinglePropertyStringToString.MyView view)
        {
            // Bind: Name <-> NameText
        var vmObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
            viewModel,
            "Name",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.Bind.SinglePropertyStringToString.MyViewModel)__o).Name,
            true);
        var viewObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
            view,
            "NameText",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.Bind.SinglePropertyStringToString.MyView)__o).NameText,
            true);

            var d1 = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(vmObs, value =>
            {
                view.NameText = value;
            });

            var __viewSkipped = global::ReactiveUI.Primitives.LinqExtensions.Skip(viewObs, 1);
            var d2 = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(__viewSkipped, value =>
            {
                viewModel.Name = value;
            });

            var __vmTagged = new global::ReactiveUI.Primitives.Signals.MapSignal<string, (object?, bool)>(vmObs, v => ((object?)v, true));
            var __viewTagged = new global::ReactiveUI.Primitives.Signals.MapSignal<string, (object?, bool)>(__viewSkipped, v => ((object?)v, false));
            var changed = new global::ReactiveUI.Primitives.Advanced.MergeSignal<(object?, bool)>(__vmTagged, __viewTagged);

            var disposable = new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(d1, d2);

            return new global::ReactiveUI.Binding.ReactiveBinding<global::SharedScenarios.Bind.SinglePropertyStringToString.MyView, (object? View, bool IsViewModel)>(
                view,
                changed,
                global::ReactiveUI.Binding.BindingDirection.TwoWay,
                disposable);
        }

    }
}
