//HintName: BindDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for Bind from global::SharedScenarios.Bind.SinglePropertyWithConverters.MyViewModel to global::SharedScenarios.Bind.SinglePropertyWithConverters.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::ReactiveUI.Binding.IReactiveBinding<global::SharedScenarios.Bind.SinglePropertyWithConverters.MyView, (object? View, bool IsViewModel)> Bind(
            this global::SharedScenarios.Bind.SinglePropertyWithConverters.MyView view,
            global::SharedScenarios.Bind.SinglePropertyWithConverters.MyViewModel viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.Bind.SinglePropertyWithConverters.MyViewModel, int>> viewModelProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.Bind.SinglePropertyWithConverters.MyView, string?>> viewProperty,
            global::System.Func<int, string> viewModelToViewConverter,
            global::System.Func<string, int> viewToViewModelConverter,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("viewModelProperty")] string viewModelPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("viewProperty")] string viewPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            if (viewModelPropertyExpression == "x => x.Count"
                && viewPropertyExpression == "x => x.CountText")
            {
                return __Bind_0000102A67853CB8(viewModel, view, viewModelToViewConverter, viewToViewModelConverter);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::ReactiveUI.Binding.IReactiveBinding<global::SharedScenarios.Bind.SinglePropertyWithConverters.MyView, (object? View, bool IsViewModel)> __Bind_0000102A67853CB8(global::SharedScenarios.Bind.SinglePropertyWithConverters.MyViewModel viewModel, global::SharedScenarios.Bind.SinglePropertyWithConverters.MyView view, global::System.Func<int, string> viewModelToViewConverter, global::System.Func<string, int> viewToViewModelConverter)
        {
            // Bind: Count <-> CountText (with conversion)
        var vmObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<int>(
            viewModel,
            "Count",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.Bind.SinglePropertyWithConverters.MyViewModel)__o).Count,
            true);
        var viewObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
            view,
            "CountText",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.Bind.SinglePropertyWithConverters.MyView)__o).CountText,
            true);
        var vmBind = new global::ReactiveUI.Primitives.Signals.MapSignal<int, string>(vmObs, viewModelToViewConverter);
        var viewBind = new global::ReactiveUI.Primitives.Signals.MapSignal<string, int>(viewObs, viewToViewModelConverter);

            var d1 = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(vmBind, value =>
            {
                view.CountText = value;
            });

            var __viewSkipped = global::ReactiveUI.Primitives.LinqExtensions.Skip(viewBind, 1);
            var d2 = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(__viewSkipped, value =>
            {
                viewModel.Count = value;
            });

            var __vmTagged = new global::ReactiveUI.Primitives.Signals.MapSignal<string, (object?, bool)>(vmBind, v => ((object?)v, true));
            var __viewTagged = new global::ReactiveUI.Primitives.Signals.MapSignal<int, (object?, bool)>(__viewSkipped, v => ((object?)v, false));
            var changed = new global::ReactiveUI.Primitives.Advanced.MergeSignal<(object?, bool)>(__vmTagged, __viewTagged);

            var disposable = new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(d1, d2);

            return new global::ReactiveUI.Binding.ReactiveBinding<global::SharedScenarios.Bind.SinglePropertyWithConverters.MyView, (object? View, bool IsViewModel)>(
                view,
                changed,
                global::ReactiveUI.Binding.BindingDirection.TwoWay,
                disposable);
        }

    }
}
