//HintName: BindInteractionDispatch.g.cs
// <auto-generated/>
#pragma warning disable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindInteraction on global::SharedScenarios.BindInteraction.TaskHandler.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindInteraction(
            this global::SharedScenarios.BindInteraction.TaskHandler.MyView view,
            global::SharedScenarios.BindInteraction.TaskHandler.MyViewModel viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindInteraction.TaskHandler.MyViewModel, global::ReactiveUI.Binding.IInteraction<string, bool>>> propertyName,
            global::System.Func<global::ReactiveUI.Binding.IInteractionContext<string, bool>, global::System.Threading.Tasks.Task> handler,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("propertyName")] string propertyNameExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            propertyNameExpression = propertyNameExpression.StartsWith("static ") ? propertyNameExpression.Substring(7) : propertyNameExpression;

            if (propertyNameExpression == "x => x.Confirm")
            {
                return __BindInteraction_000025C4B6C67FDF(view, viewModel, handler);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindInteraction_000025C4B6C67FDF(
            global::SharedScenarios.BindInteraction.TaskHandler.MyView view,
            global::SharedScenarios.BindInteraction.TaskHandler.MyViewModel viewModel,
            global::System.Func<global::ReactiveUI.Binding.IInteractionContext<string, bool>, global::System.Threading.Tasks.Task> handler)
        {
            // BindInteraction: Confirm
            var serial = new global::ReactiveUI.Binding.Observables.SerialDisposable();

        if (viewModel == null)
        {
            return serial;
        }

        var interactionObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<global::ReactiveUI.Binding.IInteraction<string, bool>>(
            viewModel,
            "Confirm",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindInteraction.TaskHandler.MyViewModel)__o).Confirm,
            true);

            var sub = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Subscribe(interactionObs, interaction =>
            {
                serial.Disposable = interaction != null
                    ? interaction.RegisterHandler(handler)
                    : global::ReactiveUI.Binding.Observables.EmptyDisposable.Instance;
            });
            return new global::ReactiveUI.Binding.Observables.CompositeDisposable2(sub, serial);
        }

    }
}
