//HintName: BindInteractionDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindInteraction on global::SharedScenarios.BindInteraction.DeepPropertyPath.MyView.
        /// Uses CallerFilePath + CallerLineNumber for dispatch.
        /// </summary>
        public static global::System.IDisposable BindInteraction(
            this global::SharedScenarios.BindInteraction.DeepPropertyPath.MyView view,
            global::SharedScenarios.BindInteraction.DeepPropertyPath.MyViewModel viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindInteraction.DeepPropertyPath.MyViewModel, global::ReactiveUI.Binding.IInteraction<string, bool>>> propertyName,
            global::System.Func<global::ReactiveUI.Binding.IInteractionContext<string, bool>, global::System.Threading.Tasks.Task> handler,
            string propertyNameExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            if (callerLineNumber == 88
                && callerFilePath.EndsWith("", global::System.StringComparison.OrdinalIgnoreCase))
            {
                return __BindInteraction_7FFFEF09AD5AF30B(viewModel, handler);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindInteraction_7FFFEF09AD5AF30B(
            global::SharedScenarios.BindInteraction.DeepPropertyPath.MyViewModel viewModel,
            global::System.Func<global::ReactiveUI.Binding.IInteractionContext<string, bool>, global::System.Threading.Tasks.Task> handler)
        {
            // BindInteraction: Child.Confirm
            var serial = new global::ReactiveUI.Primitives.Disposables.SwapDisposable();

        if (viewModel == null)
        {
            return serial;
        }
            var __interactionObs_s0 = (global::System.IObservable<global::SharedScenarios.BindInteraction.DeepPropertyPath.ChildViewModel>)new global::ReactiveUI.Binding.Observables.PropertyObservable<global::SharedScenarios.BindInteraction.DeepPropertyPath.ChildViewModel>(
                viewModel,
                "Child",
                (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindInteraction.DeepPropertyPath.MyViewModel)__o).Child,
                false);

        var __interactionObs_s1 = new global::ReactiveUI.Primitives.Advanced.SwitchMapSignal<global::SharedScenarios.BindInteraction.DeepPropertyPath.ChildViewModel, global::ReactiveUI.Binding.Interaction<string, bool>>(__interactionObs_s0,
            __p1 => __p1 != null
                ? (global::System.IObservable<global::ReactiveUI.Binding.Interaction<string, bool>>)new global::ReactiveUI.Binding.Observables.PropertyObservable<global::ReactiveUI.Binding.Interaction<string, bool>>(
                    (global::System.ComponentModel.INotifyPropertyChanged)__p1,
                    "Confirm",
                    (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindInteraction.DeepPropertyPath.ChildViewModel)__o).Confirm,
                    false)
                : (global::System.IObservable<global::ReactiveUI.Binding.Interaction<string, bool>>)new global::ReactiveUI.Primitives.Advanced.ImmediateReturnSignal<global::ReactiveUI.Binding.Interaction<string, bool>>(default(global::ReactiveUI.Binding.Interaction<string, bool>)));
        var interactionObs = global::ReactiveUI.Primitives.LinqExtensions.DistinctUntilChanged(__interactionObs_s1);

            var sub = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(interactionObs, interaction =>
            {
                serial.Disposable = interaction != null
                    ? interaction.RegisterHandler(handler)
                    : global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
            });
            return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(sub, serial);
        }

    }
}
