//HintName: BindTwoWayDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindTwoWay from global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyViewModel to global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindTwoWay(
            this global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyViewModel source,
            global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyView target,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyViewModel, string>> sourceProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyView, string>> targetProperty,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("sourceProperty")] string sourcePropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("targetProperty")] string targetPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            sourcePropertyExpression = sourcePropertyExpression.StartsWith("static ") ? sourcePropertyExpression.Substring(7) : sourcePropertyExpression;
            targetPropertyExpression = targetPropertyExpression.StartsWith("static ") ? targetPropertyExpression.Substring(7) : targetPropertyExpression;

            if (sourcePropertyExpression == "x => x.Name"
                && targetPropertyExpression == "x => x.NameText")
            {
                return __BindTwoWay_7FFFF577D0B63DEB(source, target);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindTwoWay_7FFFF577D0B63DEB(global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyViewModel source, global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyView target)
        {
            // BindTwoWay: Name <-> NameText
        var sourceObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
            source,
            "Name",
            static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyViewModel)__o).Name,
            true);
        var targetObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
            target,
            "NameText",
            static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyView)__o).NameText,
            true);

            var d1 = global::ReactiveUI.Binding.Observables.ObservableExtensions.Subscribe(sourceObs, value =>
            {
                target.NameText = value;
            });

            var __targetSkipped = global::ReactiveUI.Binding.Observables.ObservableExtensions.Skip(targetObs, 1);
            var d2 = global::ReactiveUI.Binding.Observables.ObservableExtensions.Subscribe(__targetSkipped, value =>
            {
                source.Name = value;
            });

            return new global::ReactiveUI.Binding.Observables.CompositeDisposable2(d1, d2);
        }

    }
}
