//HintName: BindOneWayDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindOneWay from global::SharedScenarios.BindOneWay.SinglePropertyWithScheduler.MyViewModel to global::SharedScenarios.BindOneWay.SinglePropertyWithScheduler.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindOneWay(
            this global::SharedScenarios.BindOneWay.SinglePropertyWithScheduler.MyViewModel source,
            global::SharedScenarios.BindOneWay.SinglePropertyWithScheduler.MyView target,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindOneWay.SinglePropertyWithScheduler.MyViewModel, string>> sourceProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindOneWay.SinglePropertyWithScheduler.MyView, string>> targetProperty,
            global::System.Reactive.Concurrency.IScheduler? scheduler,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("sourceProperty")] string sourcePropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("targetProperty")] string targetPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            sourcePropertyExpression = sourcePropertyExpression.StartsWith("static ") ? sourcePropertyExpression.Substring(7) : sourcePropertyExpression;
            targetPropertyExpression = targetPropertyExpression.StartsWith("static ") ? targetPropertyExpression.Substring(7) : targetPropertyExpression;

            if (sourcePropertyExpression == "x => x.Name"
                && targetPropertyExpression == "x => x.NameText")
            {
                return __BindOneWay_000023CFCD42C5EE(source, target, scheduler);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindOneWay_000023CFCD42C5EE(global::SharedScenarios.BindOneWay.SinglePropertyWithScheduler.MyViewModel source, global::SharedScenarios.BindOneWay.SinglePropertyWithScheduler.MyView target, global::System.Reactive.Concurrency.IScheduler? scheduler)
        {
            // BindOneWay: Name -> NameText (with scheduler)
        var sourceObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
            source,
            "Name",
            static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindOneWay.SinglePropertyWithScheduler.MyViewModel)__o).Name,
            true);
        var bindObs = new global::ReactiveUI.Binding.Reactive.ObserveOnObservable<string>(sourceObs, scheduler);

            return global::ReactiveUI.Binding.Observables.ObservableExtensions.Subscribe(bindObs, value =>
            {
                target.NameText = value;
            });
        }

    }
}
