//HintName: BindTwoWayDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindTwoWay from global::SharedScenarios.BindTwoWay.SinglePropertyIntToInt.MyViewModel to global::SharedScenarios.BindTwoWay.SinglePropertyIntToInt.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindTwoWay(
            this global::SharedScenarios.BindTwoWay.SinglePropertyIntToInt.MyViewModel source,
            global::SharedScenarios.BindTwoWay.SinglePropertyIntToInt.MyView target,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.SinglePropertyIntToInt.MyViewModel, int>> sourceProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.SinglePropertyIntToInt.MyView, int>> targetProperty,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("sourceProperty")] string sourcePropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("targetProperty")] string targetPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            sourcePropertyExpression = sourcePropertyExpression.StartsWith("static ") ? sourcePropertyExpression.Substring(7) : sourcePropertyExpression;
            targetPropertyExpression = targetPropertyExpression.StartsWith("static ") ? targetPropertyExpression.Substring(7) : targetPropertyExpression;

            if (sourcePropertyExpression == "x => x.Count"
                && targetPropertyExpression == "x => x.DisplayCount")
            {
                return __BindTwoWay_000002183E719079(source, target);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindTwoWay_000002183E719079(global::SharedScenarios.BindTwoWay.SinglePropertyIntToInt.MyViewModel source, global::SharedScenarios.BindTwoWay.SinglePropertyIntToInt.MyView target)
        {
            // BindTwoWay: Count <-> DisplayCount
        var sourceObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<int>(
            source,
            "Count",
            static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindTwoWay.SinglePropertyIntToInt.MyViewModel)__o).Count,
            true);
        var targetObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<int>(
            target,
            "DisplayCount",
            static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindTwoWay.SinglePropertyIntToInt.MyView)__o).DisplayCount,
            true);

            var d1 = global::ReactiveUI.Binding.Observables.ObservableExtensions.Subscribe(sourceObs, value =>
            {
                target.DisplayCount = value;
            });

            var __targetSkipped = global::ReactiveUI.Binding.Observables.ObservableExtensions.Skip(targetObs, 1);
            var d2 = global::ReactiveUI.Binding.Observables.ObservableExtensions.Subscribe(__targetSkipped, value =>
            {
                source.Count = value;
            });

            return new global::ReactiveUI.Binding.Observables.CompositeDisposable2(d1, d2);
        }

    }
}
