//HintName: BindOneWayDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindOneWay from global::SharedScenarios.BindOneWay.SinglePropertyWithConverter.MyViewModel to global::SharedScenarios.BindOneWay.SinglePropertyWithConverter.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindOneWay(
            this global::SharedScenarios.BindOneWay.SinglePropertyWithConverter.MyViewModel source,
            global::SharedScenarios.BindOneWay.SinglePropertyWithConverter.MyView target,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindOneWay.SinglePropertyWithConverter.MyViewModel, int>> sourceProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindOneWay.SinglePropertyWithConverter.MyView, string>> targetProperty,
            global::System.Func<int, string> conversionFunc,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("sourceProperty")] string sourcePropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("targetProperty")] string targetPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            sourcePropertyExpression = sourcePropertyExpression.StartsWith("static ") ? sourcePropertyExpression.Substring(7) : sourcePropertyExpression;
            targetPropertyExpression = targetPropertyExpression.StartsWith("static ") ? targetPropertyExpression.Substring(7) : targetPropertyExpression;

            if (sourcePropertyExpression == "x => x.Count"
                && targetPropertyExpression == "x => x.CountText")
            {
                return __BindOneWay_7FFFE88AB8C0524F(source, target, conversionFunc);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindOneWay_7FFFE88AB8C0524F(global::SharedScenarios.BindOneWay.SinglePropertyWithConverter.MyViewModel source, global::SharedScenarios.BindOneWay.SinglePropertyWithConverter.MyView target, global::System.Func<int, string> conversionFunc)
        {
            // BindOneWay: Count -> CountText (with conversion)
        var sourceObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<int>(
            source,
            "Count",
            static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindOneWay.SinglePropertyWithConverter.MyViewModel)__o).Count,
            true);
        var bindObs = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Select(sourceObs, conversionFunc);

            return global::ReactiveUI.Binding.Observables.RxBindingExtensions.Subscribe(bindObs, value =>
            {
                target.CountText = value;
            });
        }

    }
}
