//HintName: BindOneWayDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindOneWay from global::SharedScenarios.BindOneWay.MultipleSameTypeBindings.MyViewModel to global::SharedScenarios.BindOneWay.MultipleSameTypeBindings.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindOneWay(
            this global::SharedScenarios.BindOneWay.MultipleSameTypeBindings.MyViewModel source,
            global::SharedScenarios.BindOneWay.MultipleSameTypeBindings.MyView target,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindOneWay.MultipleSameTypeBindings.MyViewModel, string?>> sourceProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindOneWay.MultipleSameTypeBindings.MyView, string?>> targetProperty,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("sourceProperty")] string sourcePropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("targetProperty")] string targetPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            if (sourcePropertyExpression == "x => x.FirstName"
                && targetPropertyExpression == "x => x.FirstNameText")
            {
                return __BindOneWay_0000177DD18B9EB4(source, target);
            }
            else if (sourcePropertyExpression == "x => x.LastName"
                && targetPropertyExpression == "x => x.LastNameText")
            {
                return __BindOneWay_0000177D9FC0450C(source, target);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindOneWay_0000177DD18B9EB4(global::SharedScenarios.BindOneWay.MultipleSameTypeBindings.MyViewModel source, global::SharedScenarios.BindOneWay.MultipleSameTypeBindings.MyView target)
        {
            // BindOneWay: FirstName -> FirstNameText
        if (global::ReactiveUI.Binding.BindingHooks.Any
            && !global::ReactiveUI.Binding.BindingHooks.ShouldBind(
                source,
                target,
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(source, null, source),
                },
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(target, null, target),
                },
                global::ReactiveUI.Binding.BindingDirection.OneWay))
        {
            return global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
        }
            var sourceObsMechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(source, "FirstName", (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindOneWay.MultipleSameTypeBindings.MyViewModel)__o).FirstName, true);
        var sourceObsRegistration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(source.GetType(), "FirstName", 5, false);
        var sourceObs = sourceObsRegistration == null
            ? (global::System.IObservable<string>)sourceObsMechanism
            : (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<string>(
                sourceObsRegistration,
                source,
                ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindOneWay.MultipleSameTypeBindings.MyViewModel, string>>)(__e => __e.FirstName)).Body,
                "FirstName",
                (object __o) => ((global::SharedScenarios.BindOneWay.MultipleSameTypeBindings.MyViewModel)__o).FirstName,
                false,
                true);
            global::ReactiveUI.Binding.IBindingTypeConverter __convertedForwardConverter = null;
            if (__convertedForwardConverter == null)
            {
                __convertedForwardConverter = global::ReactiveUI.Binding.BindingConverters.Current.TypedConverters.TryGetConverter(typeof(string), typeof(string));
                if (__convertedForwardConverter != null && __convertedForwardConverter.GetAffinityForObjects() <= 2)
                {
                    __convertedForwardConverter = null;
                }
            }
            var __convertedForward = __convertedForwardConverter == null ? (global::System.IObservable<string>)sourceObs : global::ReactiveUI.Primitives.LinqExtensions.Choose<string, string>(
                sourceObs,
                __value =>
                {
                    object __hint = null;
                    if (__convertedForwardConverter != null)
                    {
                        if (__convertedForwardConverter is global::ReactiveUI.Binding.IBindingTypeConverter<string, string> __typed)
                        {
                            string __converted;
                            if (__typed.TryConvert(__value, __hint, out __converted))
                            {
                                return (true, __converted);
                            }
                        }
                        else
                        {
                            object __boxed;
                            if (__convertedForwardConverter.TryConvertTyped(__value, __hint, out __boxed))
                            {
                                return (true, (string)__boxed);
                            }
                        }
                        if (null == null)
                        {
                            return (true, (string)__value);
                        }
                        return (false, default(string));
                    }
                    return __value != null ? (true, __value) : (true, (string)__value);
                });
            var targetThreadObs = global::ReactiveUI.Binding.BindingSchedulers.ObserveOnViewThread(__convertedForward, target);

            return global::ReactiveUI.Binding.BindingErrors.Subscribe(targetThreadObs, value =>
            {
                if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(target.FirstNameText, value))
                {
                    return;
                }

                target.FirstNameText = value;
            }, "x => x.FirstNameText");
        }

        private static global::System.IDisposable __BindOneWay_0000177D9FC0450C(global::SharedScenarios.BindOneWay.MultipleSameTypeBindings.MyViewModel source, global::SharedScenarios.BindOneWay.MultipleSameTypeBindings.MyView target)
        {
            // BindOneWay: LastName -> LastNameText
        if (global::ReactiveUI.Binding.BindingHooks.Any
            && !global::ReactiveUI.Binding.BindingHooks.ShouldBind(
                source,
                target,
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(source, null, source),
                },
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(target, null, target),
                },
                global::ReactiveUI.Binding.BindingDirection.OneWay))
        {
            return global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
        }
            var sourceObsMechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(source, "LastName", (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindOneWay.MultipleSameTypeBindings.MyViewModel)__o).LastName, true);
        var sourceObsRegistration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(source.GetType(), "LastName", 5, false);
        var sourceObs = sourceObsRegistration == null
            ? (global::System.IObservable<string>)sourceObsMechanism
            : (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<string>(
                sourceObsRegistration,
                source,
                ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindOneWay.MultipleSameTypeBindings.MyViewModel, string>>)(__e => __e.LastName)).Body,
                "LastName",
                (object __o) => ((global::SharedScenarios.BindOneWay.MultipleSameTypeBindings.MyViewModel)__o).LastName,
                false,
                true);
            global::ReactiveUI.Binding.IBindingTypeConverter __convertedForwardConverter = null;
            if (__convertedForwardConverter == null)
            {
                __convertedForwardConverter = global::ReactiveUI.Binding.BindingConverters.Current.TypedConverters.TryGetConverter(typeof(string), typeof(string));
                if (__convertedForwardConverter != null && __convertedForwardConverter.GetAffinityForObjects() <= 2)
                {
                    __convertedForwardConverter = null;
                }
            }
            var __convertedForward = __convertedForwardConverter == null ? (global::System.IObservable<string>)sourceObs : global::ReactiveUI.Primitives.LinqExtensions.Choose<string, string>(
                sourceObs,
                __value =>
                {
                    object __hint = null;
                    if (__convertedForwardConverter != null)
                    {
                        if (__convertedForwardConverter is global::ReactiveUI.Binding.IBindingTypeConverter<string, string> __typed)
                        {
                            string __converted;
                            if (__typed.TryConvert(__value, __hint, out __converted))
                            {
                                return (true, __converted);
                            }
                        }
                        else
                        {
                            object __boxed;
                            if (__convertedForwardConverter.TryConvertTyped(__value, __hint, out __boxed))
                            {
                                return (true, (string)__boxed);
                            }
                        }
                        if (null == null)
                        {
                            return (true, (string)__value);
                        }
                        return (false, default(string));
                    }
                    return __value != null ? (true, __value) : (true, (string)__value);
                });
            var targetThreadObs = global::ReactiveUI.Binding.BindingSchedulers.ObserveOnViewThread(__convertedForward, target);

            return global::ReactiveUI.Binding.BindingErrors.Subscribe(targetThreadObs, value =>
            {
                if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(target.LastNameText, value))
                {
                    return;
                }

                target.LastNameText = value;
            }, "x => x.LastNameText");
        }

    }
}
