//HintName: BindOneWayDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindOneWay from global::SharedScenarios.BindOneWay.SinglePropertyStringToString.MyViewModel to global::SharedScenarios.BindOneWay.SinglePropertyStringToString.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindOneWay(
            this global::SharedScenarios.BindOneWay.SinglePropertyStringToString.MyViewModel source,
            global::SharedScenarios.BindOneWay.SinglePropertyStringToString.MyView target,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindOneWay.SinglePropertyStringToString.MyViewModel, string?>> sourceProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindOneWay.SinglePropertyStringToString.MyView, string?>> targetProperty,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("sourceProperty")] string sourcePropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("targetProperty")] string targetPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            if (sourcePropertyExpression == "x => x.Name"
                && targetPropertyExpression == "x => x.NameText")
            {
                return __BindOneWay_7FFFD267615F26EC(source, target);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindOneWay_7FFFD267615F26EC(global::SharedScenarios.BindOneWay.SinglePropertyStringToString.MyViewModel source, global::SharedScenarios.BindOneWay.SinglePropertyStringToString.MyView target)
        {
            // BindOneWay: Name -> NameText
            if (global::ReactiveUI.Binding.BindingHooks.Any)
            {
                var __hookSource = source;
                var __hookTarget = target;
                if (!global::ReactiveUI.Binding.BindingHooks.ShouldBind(
                    __hookSource,
                    __hookTarget,
                    () =>
                    {
                        var __hookChanges = new global::System.Collections.Generic.List<global::ReactiveUI.Binding.IObservedChange<object, object>>(1);
                        var __hookOwner0 = __hookSource;
                        if (__hookOwner0 is null)
                        {
                            return __hookChanges.ToArray();
                        }
                        var __hookValue0 = __hookOwner0.Name;
                        __hookChanges.Add(new global::ReactiveUI.Binding.ObservedChange<object, object>(__hookOwner0, ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindOneWay.SinglePropertyStringToString.MyViewModel, string>>)(__property => __property.Name)).Body, __hookValue0));
                        return __hookChanges.ToArray();
                    },
                    () =>
                    {
                        var __hookChanges = new global::System.Collections.Generic.List<global::ReactiveUI.Binding.IObservedChange<object, object>>(1);
                        var __hookOwner0 = __hookTarget;
                        if (__hookOwner0 is null)
                        {
                            return __hookChanges.ToArray();
                        }
                        var __hookValue0 = __hookOwner0.NameText;
                        __hookChanges.Add(new global::ReactiveUI.Binding.ObservedChange<object, object>(__hookOwner0, ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindOneWay.SinglePropertyStringToString.MyView, string>>)(__property => __property.NameText)).Body, __hookValue0));
                        return __hookChanges.ToArray();
                    },
                    global::ReactiveUI.Binding.BindingDirection.OneWay))
                {
                    return global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                }
            }
            var sourceObsMechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(source, "Name", (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindOneWay.SinglePropertyStringToString.MyViewModel)__o).Name, true);
            var sourceObsRegistration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(source.GetType(), "Name", 5, false);
            var sourceObs = sourceObsRegistration == null
                ? (global::System.IObservable<string>)sourceObsMechanism
                : (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<string>(
                    sourceObsRegistration,
                    source,
                    ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindOneWay.SinglePropertyStringToString.MyViewModel, string>>)(__e => __e.Name)).Body,
                    "Name",
                    (object __o) => ((global::SharedScenarios.BindOneWay.SinglePropertyStringToString.MyViewModel)__o).Name,
                    false,
                    true);
            global::ReactiveUI.Binding.IBindingTypeConverter __convertedForwardConverter = null;
            if (__convertedForwardConverter == null)
            {
                __convertedForwardConverter = global::ReactiveUI.Binding.BindingConverters.Current.TypedConverters.TryGetConverter(typeof(string), typeof(string));
                if (__convertedForwardConverter != null && __convertedForwardConverter.GetAffinityForObjects() <= 2)
                {
                    __convertedForwardConverter = null;
                }
            }
            var __convertedForward = __convertedForwardConverter == null ? (global::System.IObservable<string>)sourceObs : global::ReactiveUI.Primitives.LinqExtensions.Choose<string, string>(
                sourceObs,
                __value =>
                {
                    object __hint = null;
                    if (__convertedForwardConverter != null)
                    {
                        if (__convertedForwardConverter is global::ReactiveUI.Binding.IBindingTypeConverter<string, string> __typed)
                        {
                            string __converted;
                            if (__typed.TryConvert(__value, __hint, out __converted))
                            {
                                return (true, __converted);
                            }
                        }
                        else
                        {
                            object __boxed;
                            if (__convertedForwardConverter.TryConvertTyped(__value, __hint, out __boxed))
                            {
                                return (true, (string)__boxed);
                            }
                        }
                        if (null == null)
                        {
                            return (true, (string)__value);
                        }
                        return (false, default(string));
                    }
                    return __value != null ? (true, __value) : (true, (string)__value);
                });
            var targetThreadObs = global::ReactiveUI.Binding.BindingSchedulers.ObserveOnViewThread(__convertedForward, target);

            return global::ReactiveUI.Binding.BindingErrors.Subscribe(targetThreadObs, value =>
            {
                if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(target.NameText, value))
                {
                    return;
                }

                target.NameText = value;
            }, "x => x.NameText");
        }

    }
}
