//HintName: BindTwoWayDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindTwoWay from global::SharedScenarios.BindTwoWay.SinglePropertyWithConverters.MyViewModel to global::SharedScenarios.BindTwoWay.SinglePropertyWithConverters.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindTwoWay(
            this global::SharedScenarios.BindTwoWay.SinglePropertyWithConverters.MyViewModel source,
            global::SharedScenarios.BindTwoWay.SinglePropertyWithConverters.MyView target,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.SinglePropertyWithConverters.MyViewModel, int>> sourceProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.SinglePropertyWithConverters.MyView, string?>> targetProperty,
            global::System.Func<int, string> sourceToTargetConv,
            global::System.Func<string, int> targetToSourceConv,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("sourceProperty")] string sourcePropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("targetProperty")] string targetPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            sourcePropertyExpression = sourcePropertyExpression.StartsWith("static ") ? sourcePropertyExpression.Substring(7) : sourcePropertyExpression;
            targetPropertyExpression = targetPropertyExpression.StartsWith("static ") ? targetPropertyExpression.Substring(7) : targetPropertyExpression;

            if (sourcePropertyExpression == "x => x.Count"
                && targetPropertyExpression == "x => x.CountText")
            {
                return __BindTwoWay_000013957A2E9442(source, target, sourceToTargetConv, targetToSourceConv);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindTwoWay_000013957A2E9442(global::SharedScenarios.BindTwoWay.SinglePropertyWithConverters.MyViewModel source, global::SharedScenarios.BindTwoWay.SinglePropertyWithConverters.MyView target, global::System.Func<int, string> sourceToTargetConv, global::System.Func<string, int> targetToSourceConv)
        {
            // BindTwoWay: Count <-> CountText (with conversion)
        var sourceObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<int>(
            source,
            "Count",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindTwoWay.SinglePropertyWithConverters.MyViewModel)__o).Count,
            true);
        var targetObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
            target,
            "CountText",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindTwoWay.SinglePropertyWithConverters.MyView)__o).CountText,
            true);
        var sourceBind = new global::ReactiveUI.Primitives.Signals.MapSignal<int, string>(sourceObs, sourceToTargetConv);
        var targetBind = new global::ReactiveUI.Primitives.Signals.MapSignal<string, int>(targetObs, targetToSourceConv);

            var d1 = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(sourceBind, value =>
            {
                target.CountText = value;
            });

            var __targetSkipped = global::ReactiveUI.Primitives.LinqExtensions.Skip(targetBind, 1);
            var d2 = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(__targetSkipped, value =>
            {
                source.Count = value;
            });

            return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(d1, d2);
        }

    }
}
