//HintName: GeneratedBindingsAttributes.g.cs
// <auto-generated/>
#pragma warning disable
global using global::ReactiveUI.Binding.Generated.TestAssembly;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal static partial class __ReactiveUIGeneratedBindings
    {
    }
}
