//HintName: BindTwoWayDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindTwoWay from global::TestApp.MyViewModel to global::TestApp.MyAppleView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindTwoWay(
            this global::TestApp.MyViewModel source,
            global::TestApp.MyAppleView target,
            global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.MyViewModel, string?>> sourceProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.MyAppleView, string?>> targetProperty,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("sourceProperty")] string sourcePropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("targetProperty")] string targetPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            sourcePropertyExpression = sourcePropertyExpression.StartsWith("static ") ? sourcePropertyExpression.Substring(7) : sourcePropertyExpression;
            targetPropertyExpression = targetPropertyExpression.StartsWith("static ") ? targetPropertyExpression.Substring(7) : targetPropertyExpression;

            if (sourcePropertyExpression == "x => x.Name"
                && targetPropertyExpression == "x => x.Text")
            {
                return __BindTwoWay_7FFFD5B3E84DC0B6(source, target);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindTwoWay_7FFFD5B3E84DC0B6(global::TestApp.MyViewModel source, global::TestApp.MyAppleView target)
        {
            // BindTwoWay: Name <-> Text
        var sourceObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
            source,
            "Name",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::TestApp.MyViewModel)__o).Name,
            true);
        var targetObs = new __KVOObservable<string>(
            (global::Foundation.NSObject)target,
            "text",
            (global::Foundation.NSObject __o) => ((global::TestApp.MyAppleView)__o).Text,
            true,
            false);

            var d1 = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Subscribe(sourceObs, value =>
            {
                target.Text = value;
            });

            var __targetSkipped = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Skip(targetObs, 1);
            var d2 = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Subscribe(__targetSkipped, value =>
            {
                source.Name = value;
            });

            return new global::ReactiveUI.Binding.Observables.CompositeDisposable2(d1, d2);
        }

    }
}
