//HintName: BindTwoWayDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindTwoWay from global::SharedScenarios.BindTwoWay.SinglePropertyWithScheduler.MyViewModel to global::SharedScenarios.BindTwoWay.SinglePropertyWithScheduler.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindTwoWay(
            this global::SharedScenarios.BindTwoWay.SinglePropertyWithScheduler.MyViewModel source,
            global::SharedScenarios.BindTwoWay.SinglePropertyWithScheduler.MyView target,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.SinglePropertyWithScheduler.MyViewModel, string?>> sourceProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.SinglePropertyWithScheduler.MyView, string?>> targetProperty,
            global::ReactiveUI.Primitives.Concurrency.ISequencer? scheduler,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("sourceProperty")] string sourcePropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("targetProperty")] string targetPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            if (sourcePropertyExpression == "x => x.Name"
                && targetPropertyExpression == "x => x.NameText")
            {
                return __BindTwoWay_7FFFF863C3AFAD0A(source, target, scheduler);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindTwoWay_7FFFF863C3AFAD0A(global::SharedScenarios.BindTwoWay.SinglePropertyWithScheduler.MyViewModel source, global::SharedScenarios.BindTwoWay.SinglePropertyWithScheduler.MyView target, global::ReactiveUI.Primitives.Concurrency.ISequencer scheduler)
        {
            // BindTwoWay: Name <-> NameText (with scheduler)
        if (global::ReactiveUI.Binding.BindingHooks.Any
            && !global::ReactiveUI.Binding.BindingHooks.ShouldBind(
                source,
                target,
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(source, null, source),
                },
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(target, null, target),
                },
                global::ReactiveUI.Binding.BindingDirection.TwoWay))
        {
            return global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
        }
            var sourceObsMechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(source, "Name", (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindTwoWay.SinglePropertyWithScheduler.MyViewModel)__o).Name, true);
        var sourceObsRegistration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(source.GetType(), "Name", 5, false);
        var sourceObs = sourceObsRegistration == null
            ? (global::System.IObservable<string>)sourceObsMechanism
            : (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<string>(
                sourceObsRegistration,
                source,
                ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.SinglePropertyWithScheduler.MyViewModel, string>>)(__e => __e.Name)).Body,
                "Name",
                (object __o) => ((global::SharedScenarios.BindTwoWay.SinglePropertyWithScheduler.MyViewModel)__o).Name,
                false,
                true);
            var targetObsMechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(target, "NameText", (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindTwoWay.SinglePropertyWithScheduler.MyView)__o).NameText, true);
        var targetObsRegistration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(target.GetType(), "NameText", 5, false);
        var targetObs = targetObsRegistration == null
            ? (global::System.IObservable<string>)targetObsMechanism
            : (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<string>(
                targetObsRegistration,
                target,
                ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.SinglePropertyWithScheduler.MyView, string>>)(__e => __e.NameText)).Body,
                "NameText",
                (object __o) => ((global::SharedScenarios.BindTwoWay.SinglePropertyWithScheduler.MyView)__o).NameText,
                false,
                true);
            global::ReactiveUI.Binding.IBindingTypeConverter __convertedForwardConverter = null;
            if (__convertedForwardConverter == null)
            {
                __convertedForwardConverter = global::ReactiveUI.Binding.BindingConverters.Current.TypedConverters.TryGetConverter(typeof(string), typeof(string));
                if (__convertedForwardConverter != null && __convertedForwardConverter.GetAffinityForObjects() <= 2)
                {
                    __convertedForwardConverter = null;
                }
            }
            var __convertedForward = __convertedForwardConverter == null ? (global::System.IObservable<string>)sourceObs : global::ReactiveUI.Primitives.LinqExtensions.Choose<string, string>(
                sourceObs,
                __value =>
                {
                    object __hint = null;
                    if (__convertedForwardConverter != null)
                    {
                        if (__convertedForwardConverter is global::ReactiveUI.Binding.IBindingTypeConverter<string, string> __typed)
                        {
                            string __converted;
                            if (__typed.TryConvert(__value, __hint, out __converted))
                            {
                                return (true, __converted);
                            }
                        }
                        else
                        {
                            object __boxed;
                            if (__convertedForwardConverter.TryConvertTyped(__value, __hint, out __boxed))
                            {
                                return (true, (string)__boxed);
                            }
                        }
                        if (null == null)
                        {
                            return (true, (string)__value);
                        }
                        return (false, default(string));
                    }
                    return __value != null ? (true, __value) : (true, (string)__value);
                });
            global::ReactiveUI.Binding.IBindingTypeConverter __convertedReverseConverter = null;
            if (__convertedReverseConverter == null)
            {
                __convertedReverseConverter = global::ReactiveUI.Binding.BindingConverters.Current.TypedConverters.TryGetConverter(typeof(string), typeof(string));
                if (__convertedReverseConverter != null && __convertedReverseConverter.GetAffinityForObjects() <= 2)
                {
                    __convertedReverseConverter = null;
                }
            }
            var __convertedReverse = __convertedReverseConverter == null ? (global::System.IObservable<string>)targetObs : global::ReactiveUI.Primitives.LinqExtensions.Choose<string, string>(
                targetObs,
                __value =>
                {
                    object __hint = null;
                    if (__convertedReverseConverter != null)
                    {
                        if (__convertedReverseConverter is global::ReactiveUI.Binding.IBindingTypeConverter<string, string> __typed)
                        {
                            string __converted;
                            if (__typed.TryConvert(__value, __hint, out __converted))
                            {
                                return (true, __converted);
                            }
                        }
                        else
                        {
                            object __boxed;
                            if (__convertedReverseConverter.TryConvertTyped(__value, __hint, out __boxed))
                            {
                                return (true, (string)__boxed);
                            }
                        }
                        if (null == null)
                        {
                            return (true, (string)__value);
                        }
                        return (false, default(string));
                    }
                    return __value != null ? (true, __value) : (true, (string)__value);
                });
        var sourceBind = scheduler == null || scheduler == global::ReactiveUI.Primitives.Concurrency.Sequencer.Immediate ? (global::System.IObservable<string>)__convertedForward : global::ReactiveUI.Binding.BindingSchedulers.ObserveOnSequencer<string>(__convertedForward, scheduler);
        var targetBind = scheduler == null || scheduler == global::ReactiveUI.Primitives.Concurrency.Sequencer.Immediate ? (global::System.IObservable<string>)__convertedReverse : global::ReactiveUI.Binding.BindingSchedulers.ObserveOnSequencer<string>(__convertedReverse, scheduler);
            var targetThreadObs = scheduler == null ? global::ReactiveUI.Binding.BindingSchedulers.ObserveOnViewThread(sourceBind, target) : sourceBind;
            var sourceThreadObs = scheduler == null ? global::ReactiveUI.Binding.BindingSchedulers.ObserveOnViewThread(targetBind, source) : targetBind;

            var d1 = global::ReactiveUI.Binding.BindingErrors.Subscribe(targetThreadObs, value =>
            {
                if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(target.NameText, value))
                {
                    return;
                }

                target.NameText = value;
            }, "x => x.NameText");

            var d2 = global::ReactiveUI.Binding.BindingErrors.Subscribe(sourceThreadObs, value =>
            {
                if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(source.Name, value))
                {
                    return;
                }

                source.Name = value;
            }, "x => x.Name");

            return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(d1, d2);
        }

    }
}
