//HintName: BindTwoWayDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindTwoWay from global::SharedScenarios.BindTwoWay.SinglePropertyWithConvertersAndScheduler.MyViewModel to global::SharedScenarios.BindTwoWay.SinglePropertyWithConvertersAndScheduler.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindTwoWay(
            this global::SharedScenarios.BindTwoWay.SinglePropertyWithConvertersAndScheduler.MyViewModel source,
            global::SharedScenarios.BindTwoWay.SinglePropertyWithConvertersAndScheduler.MyView target,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.SinglePropertyWithConvertersAndScheduler.MyViewModel, int>> sourceProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.SinglePropertyWithConvertersAndScheduler.MyView, string?>> targetProperty,
            global::System.Func<int, string> sourceToTargetConv,
            global::System.Func<string, int> targetToSourceConv,
            global::ReactiveUI.Primitives.Concurrency.ISequencer scheduler,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("sourceProperty")] string sourcePropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("targetProperty")] string targetPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            sourcePropertyExpression = sourcePropertyExpression.StartsWith("static ", global::System.StringComparison.Ordinal)
                ? sourcePropertyExpression.Substring(7)
                : sourcePropertyExpression;
            targetPropertyExpression = targetPropertyExpression.StartsWith("static ", global::System.StringComparison.Ordinal)
                ? targetPropertyExpression.Substring(7)
                : targetPropertyExpression;

            // A registered plugin that outranks the generated one drives the binding instead
            if (global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.HasHigherAffinityPlugin(typeof(global::SharedScenarios.BindTwoWay.SinglePropertyWithConvertersAndScheduler.MyViewModel), 5, false)
                || global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.HasHigherAffinityPlugin(typeof(global::SharedScenarios.BindTwoWay.SinglePropertyWithConvertersAndScheduler.MyView), 5, false))
            {
                return global::ReactiveUI.Binding.Fallback.RuntimeBindingFallback.BindTwoWay(
                    source, target, sourceProperty, targetProperty, global::ReactiveUI.Binding.Fallback.TwoWayConverters.Create(sourceToTargetConv, targetToSourceConv), scheduler, targetPropertyExpression);
            }

            if (sourcePropertyExpression == "x => x.Count"
                && targetPropertyExpression == "x => x.CountText")
            {
                return __BindTwoWay_00000972B7EA334A(source, target, sourceToTargetConv, targetToSourceConv, scheduler);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindTwoWay_00000972B7EA334A(global::SharedScenarios.BindTwoWay.SinglePropertyWithConvertersAndScheduler.MyViewModel source, global::SharedScenarios.BindTwoWay.SinglePropertyWithConvertersAndScheduler.MyView target, global::System.Func<int, string> sourceToTargetConv, global::System.Func<string, int> targetToSourceConv, global::ReactiveUI.Primitives.Concurrency.ISequencer scheduler)
        {
            // BindTwoWay: Count <-> CountText (with conversion) (with scheduler)
        if (global::ReactiveUI.Binding.BindingHooks.Any
            && !global::ReactiveUI.Binding.BindingHooks.ShouldBind(
                source,
                target,
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(source, null, source),
                },
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(target, null, target),
                },
                global::ReactiveUI.Binding.BindingDirection.TwoWay))
        {
            return global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
        }
        var sourceObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<int>(
            source,
            "Count",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindTwoWay.SinglePropertyWithConvertersAndScheduler.MyViewModel)__o).Count,
            true);
        var targetObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
            target,
            "CountText",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindTwoWay.SinglePropertyWithConvertersAndScheduler.MyView)__o).CountText,
            true);
        var __srcSelected = new global::ReactiveUI.Primitives.Signals.MapSignal<int, string>(sourceObs, sourceToTargetConv);
        var __tgtSelected = new global::ReactiveUI.Primitives.Signals.MapSignal<string, int>(targetObs, targetToSourceConv);
        var sourceBind = global::ReactiveUI.Primitives.LinqExtensions.ObserveOn<string>(__srcSelected, scheduler);
        var targetBind = global::ReactiveUI.Primitives.LinqExtensions.ObserveOn<int>(__tgtSelected, scheduler);

            var d1 = global::ReactiveUI.Binding.BindingErrors.Subscribe(sourceBind, value =>
            {
                target.CountText = value;
            }, "x => x.CountText");

            var __targetSkipped = global::ReactiveUI.Primitives.LinqExtensions.Skip(targetBind, 1);
            var d2 = global::ReactiveUI.Binding.BindingErrors.Subscribe(__targetSkipped, value =>
            {
                source.Count = value;
            }, "x => x.Count");

            return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(d1, d2);
        }

    }
}
