//HintName: BindTwoWayDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindTwoWay from global::SharedScenarios.BindTwoWay.SinglePropertyStringToString.MyViewModel to global::SharedScenarios.BindTwoWay.SinglePropertyStringToString.MyView.
        /// Uses CallerFilePath + CallerLineNumber for dispatch.
        /// </summary>
        public static global::System.IDisposable BindTwoWay(
            this global::SharedScenarios.BindTwoWay.SinglePropertyStringToString.MyViewModel source,
            global::SharedScenarios.BindTwoWay.SinglePropertyStringToString.MyView target,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.SinglePropertyStringToString.MyViewModel, string>> sourceProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.SinglePropertyStringToString.MyView, string>> targetProperty,
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            if (callerLineNumber == 84
                && callerFilePath.EndsWith("", global::System.StringComparison.OrdinalIgnoreCase))
            {
                return __BindTwoWay_7FFFEF88F2A77A84(source, target);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindTwoWay_7FFFEF88F2A77A84(global::SharedScenarios.BindTwoWay.SinglePropertyStringToString.MyViewModel source, global::SharedScenarios.BindTwoWay.SinglePropertyStringToString.MyView target)
        {
            // BindTwoWay: Name <-> NameText
        var sourceObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
            source,
            "Name",
            static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindTwoWay.SinglePropertyStringToString.MyViewModel)__o).Name,
            true);
        var targetObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
            target,
            "NameText",
            static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindTwoWay.SinglePropertyStringToString.MyView)__o).NameText,
            true);

            var d1 = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Subscribe(sourceObs, value =>
            {
                target.NameText = value;
            });

            var __targetSkipped = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Skip(targetObs, 1);
            var d2 = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Subscribe(__targetSkipped, value =>
            {
                source.Name = value;
            });

            return new global::ReactiveUI.Binding.Observables.CompositeDisposable2(d1, d2);
        }

    }
}
