//HintName: BindOneWayDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindOneWay from global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyViewModel to global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindOneWay(
            this global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyViewModel source,
            global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyView target,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyViewModel, int>> sourceProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyView, int>> targetProperty,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("sourceProperty")] string sourcePropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("targetProperty")] string targetPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            sourcePropertyExpression = sourcePropertyExpression.StartsWith("static ", global::System.StringComparison.Ordinal)
                ? sourcePropertyExpression.Substring(7)
                : sourcePropertyExpression;
            targetPropertyExpression = targetPropertyExpression.StartsWith("static ", global::System.StringComparison.Ordinal)
                ? targetPropertyExpression.Substring(7)
                : targetPropertyExpression;

            if (sourcePropertyExpression == "x => x.ReadOnlyCount"
                && targetPropertyExpression == "x => x.CountDisplay")
            {
                return __BindOneWay_7FFFF5775C63CE08(source, target);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindOneWay_7FFFF5775C63CE08(global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyViewModel source, global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyView target)
        {
            // BindOneWay: ReadOnlyCount -> CountDisplay
        if (global::ReactiveUI.Binding.BindingHooks.Any
            && !global::ReactiveUI.Binding.BindingHooks.ShouldBind(
                source,
                target,
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(source, null, source),
                },
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(target, null, target),
                },
                global::ReactiveUI.Binding.BindingDirection.OneWay))
        {
            return global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
        }
        var sourceObsMechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<int>(
            source,
            "ReadOnlyCount",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyViewModel)__o).ReadOnlyCount,
            true);
        var sourceObsRegistration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(typeof(global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyViewModel), "ReadOnlyCount", 5, false);
        var sourceObs = sourceObsRegistration == null
            ? (global::System.IObservable<int>)sourceObsMechanism
            : (global::System.IObservable<int>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<int>(
                sourceObsRegistration,
                source,
                ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyViewModel, int>>)(__e => __e.ReadOnlyCount)).Body,
                "ReadOnlyCount",
                (object __o) => ((global::SharedScenarios.BindTwoWay.MixedWithBindOneWay.MyViewModel)__o).ReadOnlyCount,
                false,
                true);
            var targetThreadObs = global::ReactiveUI.Binding.BindingSchedulers.ObserveOnViewThread(sourceObs, target);

            return global::ReactiveUI.Binding.BindingErrors.Subscribe(targetThreadObs, value =>
            {
                if (global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(target.CountDisplay, value))
                {
                    return;
                }

                target.CountDisplay = value;
            }, "x => x.CountDisplay");
        }

    }
}
