//HintName: BindTwoWayDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindTwoWay from global::SharedScenarios.BindTwoWay.MultipleBindings.MyViewModel to global::SharedScenarios.BindTwoWay.MultipleBindings.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindTwoWay(
            this global::SharedScenarios.BindTwoWay.MultipleBindings.MyViewModel source,
            global::SharedScenarios.BindTwoWay.MultipleBindings.MyView target,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.MultipleBindings.MyViewModel, string?>> sourceProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.MultipleBindings.MyView, string?>> targetProperty,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("sourceProperty")] string sourcePropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("targetProperty")] string targetPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            sourcePropertyExpression = sourcePropertyExpression.StartsWith("static ", global::System.StringComparison.Ordinal)
                ? sourcePropertyExpression.Substring(7)
                : sourcePropertyExpression;
            targetPropertyExpression = targetPropertyExpression.StartsWith("static ", global::System.StringComparison.Ordinal)
                ? targetPropertyExpression.Substring(7)
                : targetPropertyExpression;

            // A registered plugin that outranks the generated one drives the binding instead
            if (global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.HasHigherAffinityPlugin(typeof(global::SharedScenarios.BindTwoWay.MultipleBindings.MyViewModel), 5, false)
                || global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.HasHigherAffinityPlugin(typeof(global::SharedScenarios.BindTwoWay.MultipleBindings.MyView), 5, false))
            {
                return global::ReactiveUI.Binding.Fallback.RuntimeBindingFallback.BindTwoWay(
                    source, target, sourceProperty, targetProperty, null, targetPropertyExpression);
            }

            if (sourcePropertyExpression == "x => x.Name"
                && targetPropertyExpression == "x => x.NameText")
            {
                return __BindTwoWay_00002294527D4F4C(source, target);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindTwoWay_00002294527D4F4C(global::SharedScenarios.BindTwoWay.MultipleBindings.MyViewModel source, global::SharedScenarios.BindTwoWay.MultipleBindings.MyView target)
        {
            // BindTwoWay: Name <-> NameText
        if (global::ReactiveUI.Binding.BindingHooks.Any
            && !global::ReactiveUI.Binding.BindingHooks.ShouldBind(
                source,
                target,
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(source, null, source),
                },
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(target, null, target),
                },
                global::ReactiveUI.Binding.BindingDirection.TwoWay))
        {
            return global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
        }
        var sourceObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
            source,
            "Name",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindTwoWay.MultipleBindings.MyViewModel)__o).Name,
            true);
        var targetObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
            target,
            "NameText",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindTwoWay.MultipleBindings.MyView)__o).NameText,
            true);
            var targetThreadObs = global::ReactiveUI.Binding.BindingSchedulers.ObserveOnMainThread(sourceObs);

            var d1 = global::ReactiveUI.Binding.BindingErrors.Subscribe(targetThreadObs, value =>
            {
                target.NameText = value;
            }, "x => x.NameText");

            var __targetSkipped = global::ReactiveUI.Primitives.LinqExtensions.Skip(targetObs, 1);
            var d2 = global::ReactiveUI.Binding.BindingErrors.Subscribe(__targetSkipped, value =>
            {
                source.Name = value;
            }, "x => x.Name");

            return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(d1, d2);
        }

        /// <summary>
        /// Concrete typed overload for BindTwoWay from global::SharedScenarios.BindTwoWay.MultipleBindings.MyViewModel to global::SharedScenarios.BindTwoWay.MultipleBindings.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindTwoWay(
            this global::SharedScenarios.BindTwoWay.MultipleBindings.MyViewModel source,
            global::SharedScenarios.BindTwoWay.MultipleBindings.MyView target,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.MultipleBindings.MyViewModel, int>> sourceProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.MultipleBindings.MyView, int>> targetProperty,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("sourceProperty")] string sourcePropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("targetProperty")] string targetPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            sourcePropertyExpression = sourcePropertyExpression.StartsWith("static ", global::System.StringComparison.Ordinal)
                ? sourcePropertyExpression.Substring(7)
                : sourcePropertyExpression;
            targetPropertyExpression = targetPropertyExpression.StartsWith("static ", global::System.StringComparison.Ordinal)
                ? targetPropertyExpression.Substring(7)
                : targetPropertyExpression;

            // A registered plugin that outranks the generated one drives the binding instead
            if (global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.HasHigherAffinityPlugin(typeof(global::SharedScenarios.BindTwoWay.MultipleBindings.MyViewModel), 5, false)
                || global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.HasHigherAffinityPlugin(typeof(global::SharedScenarios.BindTwoWay.MultipleBindings.MyView), 5, false))
            {
                return global::ReactiveUI.Binding.Fallback.RuntimeBindingFallback.BindTwoWay(
                    source, target, sourceProperty, targetProperty, null, targetPropertyExpression);
            }

            if (sourcePropertyExpression == "x => x.Age"
                && targetPropertyExpression == "x => x.AgeDisplay")
            {
                return __BindTwoWay_00002294440563AB(source, target);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindTwoWay_00002294440563AB(global::SharedScenarios.BindTwoWay.MultipleBindings.MyViewModel source, global::SharedScenarios.BindTwoWay.MultipleBindings.MyView target)
        {
            // BindTwoWay: Age <-> AgeDisplay
        if (global::ReactiveUI.Binding.BindingHooks.Any
            && !global::ReactiveUI.Binding.BindingHooks.ShouldBind(
                source,
                target,
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(source, null, source),
                },
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(target, null, target),
                },
                global::ReactiveUI.Binding.BindingDirection.TwoWay))
        {
            return global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
        }
        var sourceObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<int>(
            source,
            "Age",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindTwoWay.MultipleBindings.MyViewModel)__o).Age,
            true);
        var targetObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<int>(
            target,
            "AgeDisplay",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindTwoWay.MultipleBindings.MyView)__o).AgeDisplay,
            true);
            var targetThreadObs = global::ReactiveUI.Binding.BindingSchedulers.ObserveOnMainThread(sourceObs);

            var d1 = global::ReactiveUI.Binding.BindingErrors.Subscribe(targetThreadObs, value =>
            {
                target.AgeDisplay = value;
            }, "x => x.AgeDisplay");

            var __targetSkipped = global::ReactiveUI.Primitives.LinqExtensions.Skip(targetObs, 1);
            var d2 = global::ReactiveUI.Binding.BindingErrors.Subscribe(__targetSkipped, value =>
            {
                source.Age = value;
            }, "x => x.Age");

            return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(d1, d2);
        }

    }
}
