//HintName: BindTwoWayDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindTwoWay from global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyViewModel to global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindTwoWay(
            this global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyViewModel source,
            global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyView target,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyViewModel, string?>> sourceProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyView, string?>> targetProperty,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("sourceProperty")] string sourcePropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("targetProperty")] string targetPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            sourcePropertyExpression = sourcePropertyExpression.StartsWith("static ", global::System.StringComparison.Ordinal)
                ? sourcePropertyExpression.Substring(7)
                : sourcePropertyExpression;
            targetPropertyExpression = targetPropertyExpression.StartsWith("static ", global::System.StringComparison.Ordinal)
                ? targetPropertyExpression.Substring(7)
                : targetPropertyExpression;

            if (sourcePropertyExpression == "x => x.FirstName"
                && targetPropertyExpression == "x => x.FirstNameText")
            {
                return __BindTwoWay_7FFFD5F622CF2D6A(source, target);
            }
            else if (sourcePropertyExpression == "x => x.LastName"
                && targetPropertyExpression == "x => x.LastNameText")
            {
                return __BindTwoWay_7FFFD5F5F103D3C2(source, target);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindTwoWay_7FFFD5F622CF2D6A(global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyViewModel source, global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyView target)
        {
            // BindTwoWay: FirstName <-> FirstNameText
        if (global::ReactiveUI.Binding.BindingHooks.Any
            && !global::ReactiveUI.Binding.BindingHooks.ShouldBind(
                source,
                target,
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(source, null, source),
                },
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(target, null, target),
                },
                global::ReactiveUI.Binding.BindingDirection.TwoWay))
        {
            return global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
        }
        var sourceObsMechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
            source,
            "FirstName",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyViewModel)__o).FirstName,
            true);
        var sourceObsRegistration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(typeof(global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyViewModel), "FirstName", 5, false);
        var sourceObs = sourceObsRegistration == null
            ? (global::System.IObservable<string>)sourceObsMechanism
            : (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<string>(
                sourceObsRegistration,
                source,
                ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyViewModel, string>>)(__e => __e.FirstName)).Body,
                "FirstName",
                (object __o) => ((global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyViewModel)__o).FirstName,
                false,
                true);
        var targetObsMechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
            target,
            "FirstNameText",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyView)__o).FirstNameText,
            true);
        var targetObsRegistration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(typeof(global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyView), "FirstNameText", 5, false);
        var targetObs = targetObsRegistration == null
            ? (global::System.IObservable<string>)targetObsMechanism
            : (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<string>(
                targetObsRegistration,
                target,
                ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyView, string>>)(__e => __e.FirstNameText)).Body,
                "FirstNameText",
                (object __o) => ((global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyView)__o).FirstNameText,
                false,
                true);
            var targetThreadObs = global::ReactiveUI.Binding.BindingSchedulers.ObserveOnMainThread(sourceObs);

            var d1 = global::ReactiveUI.Binding.BindingErrors.Subscribe(targetThreadObs, value =>
            {
                if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(target.FirstNameText, value))
                {
                    return;
                }

                target.FirstNameText = value;
            }, "x => x.FirstNameText");

            var __targetSkipped = global::ReactiveUI.Primitives.LinqExtensions.Skip(targetObs, 1);
            var d2 = global::ReactiveUI.Binding.BindingErrors.Subscribe(__targetSkipped, value =>
            {
                if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(source.FirstName, value))
                {
                    return;
                }

                source.FirstName = value;
            }, "x => x.FirstName");

            return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(d1, d2);
        }

        private static global::System.IDisposable __BindTwoWay_7FFFD5F5F103D3C2(global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyViewModel source, global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyView target)
        {
            // BindTwoWay: LastName <-> LastNameText
        if (global::ReactiveUI.Binding.BindingHooks.Any
            && !global::ReactiveUI.Binding.BindingHooks.ShouldBind(
                source,
                target,
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(source, null, source),
                },
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(target, null, target),
                },
                global::ReactiveUI.Binding.BindingDirection.TwoWay))
        {
            return global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
        }
        var sourceObsMechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
            source,
            "LastName",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyViewModel)__o).LastName,
            true);
        var sourceObsRegistration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(typeof(global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyViewModel), "LastName", 5, false);
        var sourceObs = sourceObsRegistration == null
            ? (global::System.IObservable<string>)sourceObsMechanism
            : (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<string>(
                sourceObsRegistration,
                source,
                ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyViewModel, string>>)(__e => __e.LastName)).Body,
                "LastName",
                (object __o) => ((global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyViewModel)__o).LastName,
                false,
                true);
        var targetObsMechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
            target,
            "LastNameText",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyView)__o).LastNameText,
            true);
        var targetObsRegistration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(typeof(global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyView), "LastNameText", 5, false);
        var targetObs = targetObsRegistration == null
            ? (global::System.IObservable<string>)targetObsMechanism
            : (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<string>(
                targetObsRegistration,
                target,
                ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyView, string>>)(__e => __e.LastNameText)).Body,
                "LastNameText",
                (object __o) => ((global::SharedScenarios.BindTwoWay.MultipleSameTypeBindings.MyView)__o).LastNameText,
                false,
                true);
            var targetThreadObs = global::ReactiveUI.Binding.BindingSchedulers.ObserveOnMainThread(sourceObs);

            var d1 = global::ReactiveUI.Binding.BindingErrors.Subscribe(targetThreadObs, value =>
            {
                if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(target.LastNameText, value))
                {
                    return;
                }

                target.LastNameText = value;
            }, "x => x.LastNameText");

            var __targetSkipped = global::ReactiveUI.Primitives.LinqExtensions.Skip(targetObs, 1);
            var d2 = global::ReactiveUI.Binding.BindingErrors.Subscribe(__targetSkipped, value =>
            {
                if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(source.LastName, value))
                {
                    return;
                }

                source.LastName = value;
            }, "x => x.LastName");

            return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(d1, d2);
        }

    }
}
