//HintName: BindToDispatch.g.cs
// <auto-generated/>
#pragma warning disable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for BindTo of global::System.IObservable&lt;int&gt; to global::SharedScenarios.BindTo.DifferingTypes.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::System.IDisposable BindTo(
            this global::System.IObservable<int> source,
            global::SharedScenarios.BindTo.DifferingTypes.MyView target,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.BindTo.DifferingTypes.MyView, string>> property,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property")] string propertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            propertyExpression = propertyExpression.StartsWith("static ") ? propertyExpression.Substring(7) : propertyExpression;

            if (propertyExpression == "x => x.Caption")
            {
                return __BindTo_7FFFF0EE063CE3E4(source, target);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IDisposable __BindTo_7FFFF0EE063CE3E4(global::System.IObservable<int> source, global::SharedScenarios.BindTo.DifferingTypes.MyView target)
        {
            // BindTo: observable -> Caption
            return global::ReactiveUI.Binding.Observables.RxBindingExtensions.Subscribe(source, value =>
            {
                if (global::ReactiveUI.Binding.Fallback.RuntimeBindingConverter.TryConvert<int, string>(value, null, null, out var __converted))
                {
                    target.Caption = __converted;
                }
            });
        }

    }
}
