//HintName: OneWayBindDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for OneWayBind from global::NullableSchedulerProbe.ProbeViewModel to global::NullableSchedulerProbe.ProbeView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::ReactiveUI.Binding.IReactiveBinding<global::NullableSchedulerProbe.ProbeView, string> OneWayBind(
            this global::NullableSchedulerProbe.ProbeView view,
            global::NullableSchedulerProbe.ProbeViewModel? viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::NullableSchedulerProbe.ProbeViewModel, string?>> viewModelProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::NullableSchedulerProbe.ProbeView, string?>> viewProperty,
            global::System.Func<string, string> selector,
            global::ReactiveUI.Primitives.Concurrency.ISequencer? scheduler,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("viewModelProperty")] string viewModelPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("viewProperty")] string viewPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            if (viewModelPropertyExpression == "x => x.Name"
                && viewPropertyExpression == "v => v.DisplayName")
            {
                return __OneWayBind_000037E47803D22B(viewModel, view, selector, scheduler);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::ReactiveUI.Binding.IReactiveBinding<global::NullableSchedulerProbe.ProbeView, string> __OneWayBind_000037E47803D22B(global::NullableSchedulerProbe.ProbeViewModel viewModel, global::NullableSchedulerProbe.ProbeView view, global::System.Func<string, string> selector, global::ReactiveUI.Primitives.Concurrency.ISequencer scheduler)
        {
            // OneWayBind: Name -> DisplayName (with conversion) (with scheduler)
        if (global::ReactiveUI.Binding.BindingHooks.Any
            && !global::ReactiveUI.Binding.BindingHooks.ShouldBind(
                viewModel,
                view,
                () =>
                {
                    var __hookChanges = new global::System.Collections.Generic.List<global::ReactiveUI.Binding.IObservedChange<object, object>>(1);
                    var __hookOwner0 = viewModel;
                    if (__hookOwner0 is null)
                    {
                        return __hookChanges.ToArray();
                    }
                    var __hookValue0 = __hookOwner0.Name;
                    __hookChanges.Add(new global::ReactiveUI.Binding.ObservedChange<object, object>(__hookOwner0, ((global::System.Linq.Expressions.Expression<global::System.Func<global::NullableSchedulerProbe.ProbeViewModel, string>>)(__property => __property.Name)).Body, __hookValue0));
                    return __hookChanges.ToArray();
                },
                () =>
                {
                    var __hookChanges = new global::System.Collections.Generic.List<global::ReactiveUI.Binding.IObservedChange<object, object>>(1);
                    var __hookOwner0 = view;
                    if (__hookOwner0 is null)
                    {
                        return __hookChanges.ToArray();
                    }
                    var __hookValue0 = __hookOwner0.DisplayName;
                    __hookChanges.Add(new global::ReactiveUI.Binding.ObservedChange<object, object>(__hookOwner0, ((global::System.Linq.Expressions.Expression<global::System.Func<global::NullableSchedulerProbe.ProbeView, string>>)(__property => __property.DisplayName)).Body, __hookValue0));
                    return __hookChanges.ToArray();
                },
                global::ReactiveUI.Binding.BindingDirection.OneWay))
        {
            return null;
        }
            var sourceObsMechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(viewModel, "Name", (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::NullableSchedulerProbe.ProbeViewModel)__o).Name, true);
        var sourceObsRegistration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(viewModel.GetType(), "Name", 5, false);
        var sourceObs = sourceObsRegistration == null
            ? (global::System.IObservable<string>)sourceObsMechanism
            : (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<string>(
                sourceObsRegistration,
                viewModel,
                ((global::System.Linq.Expressions.Expression<global::System.Func<global::NullableSchedulerProbe.ProbeViewModel, string>>)(__e => __e.Name)).Body,
                "Name",
                (object __o) => ((global::NullableSchedulerProbe.ProbeViewModel)__o).Name,
                false,
                true);
        var __selected = new global::ReactiveUI.Primitives.Signals.MapSignal<string, string>(sourceObs, selector);
        var bindObs = scheduler == null || scheduler == global::ReactiveUI.Primitives.Concurrency.Sequencer.Immediate ? (global::System.IObservable<string>)__selected : new global::ReactiveUI.Primitives.Advanced.WitnessOnSignal<string>(__selected, scheduler);
            var viewThreadObs = scheduler == null ? global::ReactiveUI.Binding.BindingSchedulers.ObserveOnViewThread(bindObs, view) : bindObs;

            var sub = global::ReactiveUI.Binding.BindingErrors.Subscribe(viewThreadObs, value =>
            {
                if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(view.DisplayName, value))
                    {
                        return;
                    }

                    view.DisplayName = value;
            }, "v => v.DisplayName");

            return new global::ReactiveUI.Binding.ReactiveBinding<global::NullableSchedulerProbe.ProbeView, string>(
                view,
                viewThreadObs,
                global::ReactiveUI.Binding.BindingDirection.OneWay,
                sub);
        }

    }
}
