//HintName: OneWayBindDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for OneWayBind from global::SharedScenarios.OneWayBind.SinglePropertyStringToString.MyViewModel to global::SharedScenarios.OneWayBind.SinglePropertyStringToString.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::ReactiveUI.Binding.IReactiveBinding<global::SharedScenarios.OneWayBind.SinglePropertyStringToString.MyView, string> OneWayBind(
            this global::SharedScenarios.OneWayBind.SinglePropertyStringToString.MyView view,
            global::SharedScenarios.OneWayBind.SinglePropertyStringToString.MyViewModel viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.OneWayBind.SinglePropertyStringToString.MyViewModel, string?>> viewModelProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.OneWayBind.SinglePropertyStringToString.MyView, string?>> viewProperty,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("viewModelProperty")] string viewModelPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("viewProperty")] string viewPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            if (viewModelPropertyExpression == "x => x.Name"
                && viewPropertyExpression == "x => x.NameText")
            {
                return __OneWayBind_7FFFC4A056D62A91(viewModel, view);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::ReactiveUI.Binding.IReactiveBinding<global::SharedScenarios.OneWayBind.SinglePropertyStringToString.MyView, string> __OneWayBind_7FFFC4A056D62A91(global::SharedScenarios.OneWayBind.SinglePropertyStringToString.MyViewModel viewModel, global::SharedScenarios.OneWayBind.SinglePropertyStringToString.MyView view)
        {
            // OneWayBind: Name -> NameText
        if (global::ReactiveUI.Binding.BindingHooks.Any
            && !global::ReactiveUI.Binding.BindingHooks.ShouldBind(
                viewModel,
                view,
                () =>
                {
                    var __hookChanges = new global::System.Collections.Generic.List<global::ReactiveUI.Binding.IObservedChange<object, object>>(1);
                    var __hookOwner0 = viewModel;
                    if (__hookOwner0 is null)
                    {
                        return __hookChanges.ToArray();
                    }
                    var __hookValue0 = __hookOwner0.Name;
                    __hookChanges.Add(new global::ReactiveUI.Binding.ObservedChange<object, object>(__hookOwner0, ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.OneWayBind.SinglePropertyStringToString.MyViewModel, string>>)(__property => __property.Name)).Body, __hookValue0));
                    return __hookChanges.ToArray();
                },
                () =>
                {
                    var __hookChanges = new global::System.Collections.Generic.List<global::ReactiveUI.Binding.IObservedChange<object, object>>(1);
                    var __hookOwner0 = view;
                    if (__hookOwner0 is null)
                    {
                        return __hookChanges.ToArray();
                    }
                    var __hookValue0 = __hookOwner0.NameText;
                    __hookChanges.Add(new global::ReactiveUI.Binding.ObservedChange<object, object>(__hookOwner0, ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.OneWayBind.SinglePropertyStringToString.MyView, string>>)(__property => __property.NameText)).Body, __hookValue0));
                    return __hookChanges.ToArray();
                },
                global::ReactiveUI.Binding.BindingDirection.OneWay))
        {
            return null;
        }
            var sourceObsMechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(viewModel, "Name", (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.OneWayBind.SinglePropertyStringToString.MyViewModel)__o).Name, true);
        var sourceObsRegistration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(viewModel.GetType(), "Name", 5, false);
        var sourceObs = sourceObsRegistration == null
            ? (global::System.IObservable<string>)sourceObsMechanism
            : (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<string>(
                sourceObsRegistration,
                viewModel,
                ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.OneWayBind.SinglePropertyStringToString.MyViewModel, string>>)(__e => __e.Name)).Body,
                "Name",
                (object __o) => ((global::SharedScenarios.OneWayBind.SinglePropertyStringToString.MyViewModel)__o).Name,
                false,
                true);
            global::ReactiveUI.Binding.IBindingTypeConverter __convertedForwardConverter = null;
            if (__convertedForwardConverter == null)
            {
                __convertedForwardConverter = global::ReactiveUI.Binding.BindingConverters.Current.TypedConverters.TryGetConverter(typeof(string), typeof(string));
                if (__convertedForwardConverter != null && __convertedForwardConverter.GetAffinityForObjects() <= 2)
                {
                    __convertedForwardConverter = null;
                }
            }
            var __convertedForward = __convertedForwardConverter == null ? (global::System.IObservable<string>)sourceObs : global::ReactiveUI.Primitives.LinqExtensions.Choose<string, string>(
                sourceObs,
                __value =>
                {
                    object __hint = null;
                    if (__convertedForwardConverter != null)
                    {
                        if (__convertedForwardConverter is global::ReactiveUI.Binding.IBindingTypeConverter<string, string> __typed)
                        {
                            string __converted;
                            if (__typed.TryConvert(__value, __hint, out __converted))
                            {
                                return (true, __converted);
                            }
                        }
                        else
                        {
                            object __boxed;
                            if (__convertedForwardConverter.TryConvertTyped(__value, __hint, out __boxed))
                            {
                                return (true, (string)__boxed);
                            }
                        }
                        if (null == null)
                        {
                            return (true, (string)__value);
                        }
                        return (false, default(string));
                    }
                    return __value != null ? (true, __value) : (true, (string)__value);
                });
            var viewThreadObs = global::ReactiveUI.Binding.BindingSchedulers.ObserveOnViewThread(__convertedForward, view);

            var sub = global::ReactiveUI.Binding.BindingErrors.Subscribe(viewThreadObs, value =>
            {
                if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(view.NameText, value))
                    {
                        return;
                    }

                    view.NameText = value;
            }, "x => x.NameText");

            return new global::ReactiveUI.Binding.ReactiveBinding<global::SharedScenarios.OneWayBind.SinglePropertyStringToString.MyView, string>(
                view,
                viewThreadObs,
                global::ReactiveUI.Binding.BindingDirection.OneWay,
                sub);
        }

    }
}
