//HintName: OneWayBindDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for OneWayBind from global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel to global::SharedScenarios.OneWayBind.MultipleBindings.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::ReactiveUI.Binding.IReactiveBinding<global::SharedScenarios.OneWayBind.MultipleBindings.MyView, string> OneWayBind(
            this global::SharedScenarios.OneWayBind.MultipleBindings.MyView view,
            global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel, string?>> viewModelProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.OneWayBind.MultipleBindings.MyView, string?>> viewProperty,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("viewModelProperty")] string viewModelPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("viewProperty")] string viewPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            // A registered plugin that outranks the generated one drives the binding instead
            if (global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.HasHigherAffinityPlugin(typeof(global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel), 5, false))
            {
                return global::ReactiveUI.Binding.Fallback.RuntimeBindingFallback.OneWayBind(
                    view, viewModel, viewModelProperty, viewProperty, null, viewPropertyExpression);
            }

            if (viewModelPropertyExpression == "x => x.Name"
                && viewPropertyExpression == "x => x.NameText")
            {
                return __OneWayBind_00002D734282E686(viewModel, view);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::ReactiveUI.Binding.IReactiveBinding<global::SharedScenarios.OneWayBind.MultipleBindings.MyView, string> __OneWayBind_00002D734282E686(global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel viewModel, global::SharedScenarios.OneWayBind.MultipleBindings.MyView view)
        {
            // OneWayBind: Name -> NameText
        if (global::ReactiveUI.Binding.BindingHooks.Any
            && !global::ReactiveUI.Binding.BindingHooks.ShouldBind(
                viewModel,
                view,
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(viewModel, null, viewModel),
                },
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(view, null, view),
                },
                global::ReactiveUI.Binding.BindingDirection.OneWay))
        {
            return null;
        }
        var sourceObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
            viewModel,
            "Name",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel)__o).Name,
            true);
            var viewThreadObs = global::ReactiveUI.Binding.BindingSchedulers.ObserveOnMainThread(sourceObs);

            var sub = global::ReactiveUI.Binding.BindingErrors.Subscribe(viewThreadObs, value =>
            {
                view.NameText = value;
            }, "x => x.NameText");

            return new global::ReactiveUI.Binding.ReactiveBinding<global::SharedScenarios.OneWayBind.MultipleBindings.MyView, string>(
                view,
                viewThreadObs,
                global::ReactiveUI.Binding.BindingDirection.OneWay,
                sub);
        }

        /// <summary>
        /// Concrete typed overload for OneWayBind from global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel to global::SharedScenarios.OneWayBind.MultipleBindings.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::ReactiveUI.Binding.IReactiveBinding<global::SharedScenarios.OneWayBind.MultipleBindings.MyView, int> OneWayBind(
            this global::SharedScenarios.OneWayBind.MultipleBindings.MyView view,
            global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel, int>> viewModelProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.OneWayBind.MultipleBindings.MyView, int>> viewProperty,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("viewModelProperty")] string viewModelPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("viewProperty")] string viewPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            // A registered plugin that outranks the generated one drives the binding instead
            if (global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.HasHigherAffinityPlugin(typeof(global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel), 5, false))
            {
                return global::ReactiveUI.Binding.Fallback.RuntimeBindingFallback.OneWayBind(
                    view, viewModel, viewModelProperty, viewProperty, null, viewPropertyExpression);
            }

            if (viewModelPropertyExpression == "x => x.Age"
                && viewPropertyExpression == "x => x.AgeText")
            {
                return __OneWayBind_00002D72E431FB45(viewModel, view);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::ReactiveUI.Binding.IReactiveBinding<global::SharedScenarios.OneWayBind.MultipleBindings.MyView, int> __OneWayBind_00002D72E431FB45(global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel viewModel, global::SharedScenarios.OneWayBind.MultipleBindings.MyView view)
        {
            // OneWayBind: Age -> AgeText
        if (global::ReactiveUI.Binding.BindingHooks.Any
            && !global::ReactiveUI.Binding.BindingHooks.ShouldBind(
                viewModel,
                view,
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(viewModel, null, viewModel),
                },
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(view, null, view),
                },
                global::ReactiveUI.Binding.BindingDirection.OneWay))
        {
            return null;
        }
        var sourceObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<int>(
            viewModel,
            "Age",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel)__o).Age,
            true);
            var viewThreadObs = global::ReactiveUI.Binding.BindingSchedulers.ObserveOnMainThread(sourceObs);

            var sub = global::ReactiveUI.Binding.BindingErrors.Subscribe(viewThreadObs, value =>
            {
                view.AgeText = value;
            }, "x => x.AgeText");

            return new global::ReactiveUI.Binding.ReactiveBinding<global::SharedScenarios.OneWayBind.MultipleBindings.MyView, int>(
                view,
                viewThreadObs,
                global::ReactiveUI.Binding.BindingDirection.OneWay,
                sub);
        }

    }
}
