//HintName: OneWayBindDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for OneWayBind from global::SharedScenarios.OneWayBind.SinglePropertyWithSelectorAndScheduler.MyViewModel to global::SharedScenarios.OneWayBind.SinglePropertyWithSelectorAndScheduler.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::ReactiveUI.Binding.IReactiveBinding<global::SharedScenarios.OneWayBind.SinglePropertyWithSelectorAndScheduler.MyView, string> OneWayBind(
            this global::SharedScenarios.OneWayBind.SinglePropertyWithSelectorAndScheduler.MyView view,
            global::SharedScenarios.OneWayBind.SinglePropertyWithSelectorAndScheduler.MyViewModel? viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.OneWayBind.SinglePropertyWithSelectorAndScheduler.MyViewModel, int>> viewModelProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.OneWayBind.SinglePropertyWithSelectorAndScheduler.MyView, string?>> viewProperty,
            global::System.Func<int, string> selector,
            global::ReactiveUI.Primitives.Concurrency.ISequencer? scheduler,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("viewModelProperty")] string viewModelPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("viewProperty")] string viewPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            if (viewModelPropertyExpression == "x => x.Count"
                && viewPropertyExpression == "x => x.CountText")
            {
                return __OneWayBind_7FFFFAB8DECC37EC(viewModel, view, selector, scheduler);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::ReactiveUI.Binding.IReactiveBinding<global::SharedScenarios.OneWayBind.SinglePropertyWithSelectorAndScheduler.MyView, string> __OneWayBind_7FFFFAB8DECC37EC(global::SharedScenarios.OneWayBind.SinglePropertyWithSelectorAndScheduler.MyViewModel viewModel, global::SharedScenarios.OneWayBind.SinglePropertyWithSelectorAndScheduler.MyView view, global::System.Func<int, string> selector, global::ReactiveUI.Primitives.Concurrency.ISequencer scheduler)
        {
            // OneWayBind: Count -> CountText (with conversion) (with scheduler)
        if (global::ReactiveUI.Binding.BindingHooks.Any)
        {
            var __hookSource = viewModel;
            var __hookTarget = view;
            if (!global::ReactiveUI.Binding.BindingHooks.ShouldBind(
                __hookSource,
                __hookTarget,
                () =>
                {
                    var __hookChanges = new global::System.Collections.Generic.List<global::ReactiveUI.Binding.IObservedChange<object, object>>(1);
                    var __hookOwner0 = __hookSource;
                    if (__hookOwner0 is null)
                    {
                        return __hookChanges.ToArray();
                    }
                    var __hookValue0 = __hookOwner0.Count;
                    __hookChanges.Add(new global::ReactiveUI.Binding.ObservedChange<object, object>(__hookOwner0, ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.OneWayBind.SinglePropertyWithSelectorAndScheduler.MyViewModel, int>>)(__property => __property.Count)).Body, __hookValue0));
                    return __hookChanges.ToArray();
                },
                () =>
                {
                    var __hookChanges = new global::System.Collections.Generic.List<global::ReactiveUI.Binding.IObservedChange<object, object>>(1);
                    var __hookOwner0 = __hookTarget;
                    if (__hookOwner0 is null)
                    {
                        return __hookChanges.ToArray();
                    }
                    var __hookValue0 = __hookOwner0.CountText;
                    __hookChanges.Add(new global::ReactiveUI.Binding.ObservedChange<object, object>(__hookOwner0, ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.OneWayBind.SinglePropertyWithSelectorAndScheduler.MyView, string>>)(__property => __property.CountText)).Body, __hookValue0));
                    return __hookChanges.ToArray();
                },
                global::ReactiveUI.Binding.BindingDirection.OneWay))
            {
                return null;
            }
        }
            var sourceObsMechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<int>(viewModel, "Count", (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.OneWayBind.SinglePropertyWithSelectorAndScheduler.MyViewModel)__o).Count, true);
        var sourceObsRegistration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(viewModel.GetType(), "Count", 5, false);
        var sourceObs = sourceObsRegistration == null
            ? (global::System.IObservable<int>)sourceObsMechanism
            : (global::System.IObservable<int>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<int>(
                sourceObsRegistration,
                viewModel,
                ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.OneWayBind.SinglePropertyWithSelectorAndScheduler.MyViewModel, int>>)(__e => __e.Count)).Body,
                "Count",
                (object __o) => ((global::SharedScenarios.OneWayBind.SinglePropertyWithSelectorAndScheduler.MyViewModel)__o).Count,
                false,
                true);
        var __selected = new global::ReactiveUI.Primitives.Signals.MapSignal<int, string>(sourceObs, selector);
        var bindObs = scheduler == null || scheduler == global::ReactiveUI.Primitives.Concurrency.Sequencer.Immediate ? (global::System.IObservable<string>)__selected : new global::ReactiveUI.Primitives.Advanced.WitnessOnSignal<string>(__selected, scheduler);
            var viewThreadObs = scheduler == null ? global::ReactiveUI.Binding.BindingSchedulers.ObserveOnViewThread(bindObs, view) : bindObs;

            var sub = global::ReactiveUI.Binding.BindingErrors.Subscribe(viewThreadObs, value =>
            {
                if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(view.CountText, value))
                    {
                        return;
                    }

                    view.CountText = value;
            }, "x => x.CountText");

            return new global::ReactiveUI.Binding.ReactiveBinding<global::SharedScenarios.OneWayBind.SinglePropertyWithSelectorAndScheduler.MyView, string>(
                view,
                viewThreadObs,
                global::ReactiveUI.Binding.BindingDirection.OneWay,
                sub);
        }

    }
}
