//HintName: OneWayBindDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for OneWayBind from global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel to global::SharedScenarios.OneWayBind.MultipleBindings.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::ReactiveUI.Binding.IReactiveBinding<global::SharedScenarios.OneWayBind.MultipleBindings.MyView, string> OneWayBind(
            this global::SharedScenarios.OneWayBind.MultipleBindings.MyView view,
            global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel, string>> vmProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.OneWayBind.MultipleBindings.MyView, string>> viewProperty,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("vmProperty")] string vmPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("viewProperty")] string viewPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            if (vmPropertyExpression == "x => x.Name"
                && viewPropertyExpression == "x => x.NameText")
            {
                return __OneWayBind_00002D734282E857(viewModel, view);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::ReactiveUI.Binding.IReactiveBinding<global::SharedScenarios.OneWayBind.MultipleBindings.MyView, string> __OneWayBind_00002D734282E857(global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel viewModel, global::SharedScenarios.OneWayBind.MultipleBindings.MyView view)
        {
            // OneWayBind: Name -> NameText
        var sourceObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
            viewModel,
            "Name",
            static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel)__o).Name,
            true);

            var sub = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Subscribe(sourceObs, value =>
            {
                view.NameText = value;
            });

            return new global::ReactiveUI.Binding.ReactiveBinding<global::SharedScenarios.OneWayBind.MultipleBindings.MyView, string>(
                view,
                sourceObs,
                global::ReactiveUI.Binding.BindingDirection.OneWay,
                sub);
        }

        /// <summary>
        /// Concrete typed overload for OneWayBind from global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel to global::SharedScenarios.OneWayBind.MultipleBindings.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::ReactiveUI.Binding.IReactiveBinding<global::SharedScenarios.OneWayBind.MultipleBindings.MyView, int> OneWayBind(
            this global::SharedScenarios.OneWayBind.MultipleBindings.MyView view,
            global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel, int>> vmProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.OneWayBind.MultipleBindings.MyView, int>> viewProperty,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("vmProperty")] string vmPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("viewProperty")] string viewPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            if (vmPropertyExpression == "x => x.Age"
                && viewPropertyExpression == "x => x.AgeText")
            {
                return __OneWayBind_00002D72E431FD16(viewModel, view);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::ReactiveUI.Binding.IReactiveBinding<global::SharedScenarios.OneWayBind.MultipleBindings.MyView, int> __OneWayBind_00002D72E431FD16(global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel viewModel, global::SharedScenarios.OneWayBind.MultipleBindings.MyView view)
        {
            // OneWayBind: Age -> AgeText
        var sourceObs = new global::ReactiveUI.Binding.Observables.PropertyObservable<int>(
            viewModel,
            "Age",
            static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.OneWayBind.MultipleBindings.MyViewModel)__o).Age,
            true);

            var sub = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Subscribe(sourceObs, value =>
            {
                view.AgeText = value;
            });

            return new global::ReactiveUI.Binding.ReactiveBinding<global::SharedScenarios.OneWayBind.MultipleBindings.MyView, int>(
                view,
                sourceObs,
                global::ReactiveUI.Binding.BindingDirection.OneWay,
                sub);
        }

    }
}
