//HintName: ToPropertyDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for ToProperty of global::SharedScenarios.ToProperty.PublicRaiseMethod.MyViewModel.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::ReactiveUI.Binding.ObservableAsPropertyHelper<int> ToProperty(
            this global::System.IObservable<int> target,
            global::SharedScenarios.ToProperty.PublicRaiseMethod.MyViewModel source,
            global::System.Func<global::SharedScenarios.ToProperty.PublicRaiseMethod.MyViewModel, int> property,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property")] string propertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            if (propertyExpression == "x => x.Count")
            {
                return __ToProperty_0000373D831604FA(target, source, default(int), false, null);
            }
            throw new global::System.InvalidOperationException(
                "No generated ToProperty dispatch matched this call site. Name the property with a lambda of the form x => x.Property or with a constant.");
        }

        private static global::ReactiveUI.Binding.ObservableAsPropertyHelper<int> __ToProperty_0000373D831604FA(
            global::System.IObservable<int> target,
            global::SharedScenarios.ToProperty.PublicRaiseMethod.MyViewModel source,
            int initialValue,
            bool deferSubscription,
            global::ReactiveUI.Primitives.Concurrency.ISequencer? scheduler)
        {
            // ToProperty: global::SharedScenarios.ToProperty.PublicRaiseMethod.MyViewModel.Count raised through RaiseMethod
            return global::ReactiveUI.Binding.ObservableAsPropertyHelper<int>.Create(
                target,
                source,
                (__owner, __value) => ((global::SharedScenarios.ToProperty.PublicRaiseMethod.MyViewModel)__owner).RaisePropertyChanged("Count"),
                null,
                initialValue,
                deferSubscription,
                scheduler);
        }

    }
}
