//HintName: BindCommandDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.Interceptors.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        [global::System.Runtime.CompilerServices.InterceptsLocation(1, "Zs4qObJpfhfSQ83m5yXFVaIMAAA=")]
        internal static global::System.IDisposable __InterceptHosted_7FFFDC4D3D7713C4<__S0, __S1, __S2, __S3>(
            this __S0 view,
            __S1? viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<__S1, __S2?>> propertyName,
            global::System.Linq.Expressions.Expression<global::System.Func<__S0, __S3>> controlName,
            string? toEvent,
            string propertyNameExpression,
            string controlNameExpression,
            string callerFilePath,
            int callerLineNumber)
            where __S0 : class, global::ReactiveUI.Binding.IViewFor
            where __S1 : class
            where __S2 : global::System.Windows.Input.ICommand
            where __S3 : class
            => global::TestApp.Scenario.__ReactiveUIHostedEntries.__Entry_7FFFDC4D3D7713C4<__S0, __S1, __S2, __S3>(view, viewModel, propertyName, controlName, toEvent, propertyNameExpression, controlNameExpression, callerFilePath, callerLineNumber);

    }
}

namespace TestApp
{
    partial class Scenario
    {
        internal static partial class __ReactiveUIHostedEntries
        {
            internal static global::System.IDisposable __Entry_7FFFDC4D3D7713C4<__S0, __S1, __S2, __S3>(
                __S0 view,
                __S1? viewModel,
                global::System.Linq.Expressions.Expression<global::System.Func<__S1, __S2?>> propertyName,
                global::System.Linq.Expressions.Expression<global::System.Func<__S0, __S3>> controlName,
                string? toEvent,
                string propertyNameExpression,
                string controlNameExpression,
                string callerFilePath,
                int callerLineNumber)
                where __S0 : class, global::ReactiveUI.Binding.IViewFor
                where __S1 : class
                where __S2 : global::System.Windows.Input.ICommand
                where __S3 : class
                => __ReactiveUIHostedBindings.__Intercept_BindCommand_00001EF5029F9CF6((global::TestApp.Scenario.View)(object)view, (global::TestApp.Scenario.ViewModel?)(object)viewModel, (global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.Scenario.ViewModel, global::System.Windows.Input.ICommand?>>)(object)propertyName, (global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.Scenario.View, global::TestApp.MyButton>>)(object)controlName, toEvent, propertyNameExpression, controlNameExpression, callerFilePath, callerLineNumber);

            private static partial class __ReactiveUIHostedBindings
            {
                internal static global::System.IDisposable __Intercept_BindCommand_00001EF5029F9CF6(
                    global::TestApp.Scenario.View view,
                    global::TestApp.Scenario.ViewModel? viewModel,
                    global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.Scenario.ViewModel, global::System.Windows.Input.ICommand?>> propertyName,
                    global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.Scenario.View, global::TestApp.MyButton>> controlName,
                    string? toEvent = null,
                    [global::System.Runtime.CompilerServices.CallerArgumentExpression("propertyName")] string propertyNameExpression = "",
                    [global::System.Runtime.CompilerServices.CallerArgumentExpression("controlName")] string controlNameExpression = "",
                    [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
                    [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
                    => __BindCommand_00001EF5029F9CF6(view, viewModel);


                private static global::System.IDisposable __BindCommand_00001EF5029F9CF6(
                    global::TestApp.Scenario.View view,
                    global::TestApp.Scenario.ViewModel viewModel)
                {
                    // BindCommand: Save -> SaveButton (event: Click)

                    var ____commandChanges_s0Mechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<global::TestApp.Scenario.ViewModel>(view, "ViewModel", (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::TestApp.Scenario.View)__o).ViewModel, false);
                    var ____commandChanges_s0Registration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(view.GetType(), "ViewModel", 5, false);
                    var ____commandChanges_s0 = ____commandChanges_s0Registration == null
                        ? (global::System.IObservable<global::TestApp.Scenario.ViewModel>)____commandChanges_s0Mechanism
                        : (global::System.IObservable<global::TestApp.Scenario.ViewModel>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<global::TestApp.Scenario.ViewModel>(
                            ____commandChanges_s0Registration,
                            view,
                            ((global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.Scenario.View, global::TestApp.Scenario.ViewModel>>)(__e => __e.ViewModel)).Body,
                            "ViewModel",
                            (object __o) => ((global::TestApp.Scenario.View)__o).ViewModel,
                            false,
                            true);
                    var ____commandChanges_s1 = new global::ReactiveUI.Primitives.Advanced.SwitchMapSignal<global::TestApp.Scenario.ViewModel, global::System.Windows.Input.ICommand>(____commandChanges_s0,
                        __p1 => __p1 != null
                            ? (global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(__p1.GetType(), "Save", 5, false) is global::ReactiveUI.Binding.ICreatesObservableForProperty __registration___p1
                                ? (global::System.IObservable<global::System.Windows.Input.ICommand>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<global::System.Windows.Input.ICommand>(
                                    __registration___p1,
                                    __p1,
                                    ((global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.Scenario.ViewModel, global::System.Windows.Input.ICommand>>)(__e => __e.Save)).Body,
                                    "Save",
                                    (object __o) => ((global::TestApp.Scenario.ViewModel)__o).Save,
                                    false, false)
                                : (global::System.IObservable<global::System.Windows.Input.ICommand>)
                                new global::ReactiveUI.Binding.Observables.PropertyObservable<global::System.Windows.Input.ICommand>(__p1, "Save", (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::TestApp.Scenario.ViewModel)__o).Save, false))
                            : (global::System.IObservable<global::System.Windows.Input.ICommand>)new global::ReactiveUI.Primitives.Advanced.ImmediateReturnSignal<global::System.Windows.Input.ICommand>(default(global::System.Windows.Input.ICommand)));
                    var __commandChanges = new global::ReactiveUI.Primitives.Advanced.UniqueSignal<global::System.Windows.Input.ICommand>(____commandChanges_s1, global::System.Collections.Generic.EqualityComparer<global::System.Windows.Input.ICommand>.Default);
                    var commandObs = global::ReactiveUI.Binding.BindingSchedulers.ObserveOnViewThread(__commandChanges, view);
                    var __controlChangesMechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<global::TestApp.MyButton>(view, "SaveButton", (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::TestApp.Scenario.View)__o).SaveButton, true);
                    var __controlChangesRegistration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(view.GetType(), "SaveButton", 5, false);
                    var __controlChanges = __controlChangesRegistration == null
                        ? (global::System.IObservable<global::TestApp.MyButton>)__controlChangesMechanism
                        : (global::System.IObservable<global::TestApp.MyButton>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<global::TestApp.MyButton>(
                            __controlChangesRegistration,
                            view,
                            ((global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.Scenario.View, global::TestApp.MyButton>>)(__e => __e.SaveButton)).Body,
                            "SaveButton",
                            (object __o) => ((global::TestApp.Scenario.View)__o).SaveButton,
                            false,
                            true);
                    var __controls = global::ReactiveUI.Binding.BindingSchedulers.ObserveOnViewThread(__controlChanges, view);
                    var __controlBinding = new global::ReactiveUI.Primitives.Disposables.SwapDisposable();
                    var __controlSub = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(__controls, __control =>
                    {
                        __controlBinding.Disposable = global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                        if (__control != null)
                        {
                            __controlBinding.Disposable = __BindCommandCore_00001EF5029F9CF6(__control, commandObs);
                        }
                    });
                    return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(__controlSub, __controlBinding);
                }

                private static global::System.IDisposable __BindCommandCore_00001EF5029F9CF6(global::TestApp.MyButton __control, global::System.IObservable<global::System.Windows.Input.ICommand> commandObs)
                {

                    if (global::ReactiveUI.Binding.Fallback.CommandBindingAffinityChecker
                        .HasHigherAffinityPlugin<global::TestApp.MyButton>(3, false))
                    {
                        var __customBinder = global::ReactiveUI.Binding.CommandBinding.CommandBinderService
                            .GetBinder<global::TestApp.MyButton>(false);
                        if (__customBinder != null)
                        {
                            var __serial = new global::ReactiveUI.Primitives.Disposables.SwapDisposable();
                            var __binderCmdSub = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(commandObs, __cmd =>
                            {
                                __serial.Disposable = global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                                global::System.IObservable<object> __paramObs = global::ReactiveUI.Primitives.Advanced.ImmutableEmptySignal<object>.Instance;
                                __serial.Disposable = __customBinder.BindCommandToObject<global::TestApp.MyButton>(
                                    __cmd, __control, __paramObs)
                                    ?? global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                            });
                            return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(__binderCmdSub, __serial);
                        }
                    }


                    var serial = new global::ReactiveUI.Primitives.Disposables.SwapDisposable();
                    var __cmdSub = global::ReactiveUI.Primitives.SubscribeExtensions.Subscribe(commandObs, (global::System.Windows.Input.ICommand cmd) =>
                    {
                        serial.Disposable = global::ReactiveUI.Primitives.Disposables.EmptyDisposable.Instance;
                        if (cmd == null)
                        {
                            return;
                        }

                        void __Handler(object? sender, global::System.EventArgs e)
                        {
                            if (cmd.CanExecute(null))
                            {
                                cmd.Execute(null);
                            }
                        }

                        __control.Click += __Handler;
                        serial.Disposable = new global::ReactiveUI.Primitives.Disposables.ActionDisposable(() =>
                            __control.Click -= __Handler);
                    });
                    return new global::ReactiveUI.Primitives.Disposables.MultipleDisposable(__cmdSub, serial);
                }

            }
        }
    }
}

namespace System.Runtime.CompilerServices
{
    /// <summary>Binds a generated method to the call site it replaces.</summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : global::System.Attribute
    {
        /// <summary>Initializes a new instance of the <see cref="InterceptsLocationAttribute"/> class.</summary>
        /// <param name="version">The encoding of <paramref name="data"/>.</param>
        /// <param name="data">The call site being replaced.</param>
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}
