//HintName: OneWayBindDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.Interceptors.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        [global::System.Runtime.CompilerServices.InterceptsLocation(1, "s7sD/tQJ3xEt3L7BnYDcIwIQAAA=")]
        internal static global::ReactiveUI.Binding.IReactiveBinding<__S1, __S3> __InterceptHosted_7FFFC6E18C012F99<__S0, __S1, __S2, __S3>(
            this __S1 view,
            __S0? viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<__S0, __S2>> viewModelProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<__S1, __S3>> viewProperty,
            string viewModelPropertyExpression,
            string viewPropertyExpression,
            string callerFilePath,
            int callerLineNumber)
            where __S0 : class, global::TestApp.IHasA
            where __S1 : class, global::ReactiveUI.Binding.IViewFor
            => global::ReactiveUI.Binding.Generated.Interceptors.TestAssembly.__ReactiveUIGeneratedBindings.__ReactiveUIHostedEntries_00003708F4D34315<__S0>.__Entry_7FFFC6E18C012F99<__S0, __S1, __S2, __S3>(view, viewModel, viewModelProperty, viewProperty, viewModelPropertyExpression, viewPropertyExpression, callerFilePath, callerLineNumber);

    }
}

namespace ReactiveUI.Binding.Generated.Interceptors.TestAssembly
{
    static partial class __ReactiveUIGeneratedBindings
    {
        internal static partial class __ReactiveUIHostedEntries_00003708F4D34315<TViewModel>
            where TViewModel : class, global::TestApp.IHasA
        {
            internal static global::ReactiveUI.Binding.IReactiveBinding<__S1, __S3> __Entry_7FFFC6E18C012F99<__S0, __S1, __S2, __S3>(
                __S1 view,
                __S0? viewModel,
                global::System.Linq.Expressions.Expression<global::System.Func<__S0, __S2>> viewModelProperty,
                global::System.Linq.Expressions.Expression<global::System.Func<__S1, __S3>> viewProperty,
                string viewModelPropertyExpression,
                string viewPropertyExpression,
                string callerFilePath,
                int callerLineNumber)
                where __S0 : class, global::TestApp.IHasA
                where __S1 : class, global::ReactiveUI.Binding.IViewFor
                => (global::ReactiveUI.Binding.IReactiveBinding<__S1, __S3>)(object)__ReactiveUIHostedBindings.__Intercept_OneWayBind_00001DF1662723E5((global::TestApp.ViewBase<TViewModel>)(object)view, (TViewModel?)(object)viewModel, (global::System.Linq.Expressions.Expression<global::System.Func<TViewModel, int>>)(object)viewModelProperty, (global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.ViewBase<TViewModel>, int>>)(object)viewProperty, viewModelPropertyExpression, viewPropertyExpression, callerFilePath, callerLineNumber);

            private static partial class __ReactiveUIHostedBindings
            {
                internal static global::ReactiveUI.Binding.IReactiveBinding<global::TestApp.ViewBase<TViewModel>, int> __Intercept_OneWayBind_00001DF1662723E5(
                    global::TestApp.ViewBase<TViewModel> view,
                    TViewModel? viewModel,
                    global::System.Linq.Expressions.Expression<global::System.Func<TViewModel, int>> viewModelProperty,
                    global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.ViewBase<TViewModel>, int>> viewProperty,
                    [global::System.Runtime.CompilerServices.CallerArgumentExpression("viewModelProperty")] string viewModelPropertyExpression = "",
                    [global::System.Runtime.CompilerServices.CallerArgumentExpression("viewProperty")] string viewPropertyExpression = "",
                    [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
                    [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
                    => __OneWayBind_00001DF1662723E5(viewModel, view);


                private static global::ReactiveUI.Binding.IReactiveBinding<global::TestApp.ViewBase<TViewModel>, int> __OneWayBind_00001DF1662723E5(TViewModel viewModel, global::TestApp.ViewBase<TViewModel> view)
                {
                    // OneWayBind: A -> Shown
                    if (global::ReactiveUI.Binding.BindingHooks.Any)
                    {
                        var __hookSource = viewModel;
                        var __hookTarget = view;
                        if (!global::ReactiveUI.Binding.BindingHooks.ShouldBind(
                            __hookSource,
                            __hookTarget,
                            () =>
                            {
                                var __hookChanges = new global::System.Collections.Generic.List<global::ReactiveUI.Binding.IObservedChange<object, object>>(1);
                                var __hookOwner0 = __hookSource;
                                if (__hookOwner0 is null)
                                {
                                    return __hookChanges.ToArray();
                                }
                                var __hookValue0 = __hookOwner0.A;
                                __hookChanges.Add(new global::ReactiveUI.Binding.ObservedChange<object, object>(__hookOwner0, ((global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.IHasA, int>>)(__property => __property.A)).Body, __hookValue0));
                                return __hookChanges.ToArray();
                            },
                            () =>
                            {
                                var __hookChanges = new global::System.Collections.Generic.List<global::ReactiveUI.Binding.IObservedChange<object, object>>(1);
                                var __hookOwner0 = __hookTarget;
                                if (__hookOwner0 is null)
                                {
                                    return __hookChanges.ToArray();
                                }
                                var __hookValue0 = __hookOwner0.Shown;
                                __hookChanges.Add(new global::ReactiveUI.Binding.ObservedChange<object, object>(__hookOwner0, ((global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.ViewBase<TViewModel>, int>>)(__property => __property.Shown)).Body, __hookValue0));
                                return __hookChanges.ToArray();
                            },
                            global::ReactiveUI.Binding.BindingDirection.OneWay))
                        {
                            return null;
                        }
                    }
                    var __sourceObs_s0Mechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<TViewModel>(view, "ViewModel", (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::TestApp.ViewBase<TViewModel>)__o).ViewModel, false);
                    var __sourceObs_s0Registration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(view.GetType(), "ViewModel", 5, false);
                    var __sourceObs_s0 = __sourceObs_s0Registration == null
                        ? (global::System.IObservable<TViewModel>)__sourceObs_s0Mechanism
                        : (global::System.IObservable<TViewModel>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<TViewModel>(
                            __sourceObs_s0Registration,
                            view,
                            ((global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.ViewBase<TViewModel>, TViewModel>>)(__e => __e.ViewModel)).Body,
                            "ViewModel",
                            (object __o) => ((global::TestApp.ViewBase<TViewModel>)__o).ViewModel,
                            false,
                            true);
                    var __sourceObs_s1 = new global::ReactiveUI.Primitives.Advanced.SwitchMapSignal<global::TestApp.IHasA, int>(__sourceObs_s0,
                        __p1 => __p1 != null
                            ? (global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(__p1.GetType(), "A", 5, false) is global::ReactiveUI.Binding.ICreatesObservableForProperty __registration___p1
                                ? (global::System.IObservable<int>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<int>(
                                    __registration___p1,
                                    __p1,
                                    ((global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.IHasA, int>>)(__e => __e.A)).Body,
                                    "A",
                                    (object __o) => ((global::TestApp.IHasA)__o).A,
                                    false, false)
                                : (global::System.IObservable<int>)
                                new global::ReactiveUI.Binding.Observables.PropertyObservable<int>(__p1, "A", (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::TestApp.IHasA)__o).A, false))
                            : (global::System.IObservable<int>)global::ReactiveUI.Primitives.Advanced.ImmutableEmptySignal<int>.Instance);
                    var sourceObs = new global::ReactiveUI.Primitives.Advanced.UniqueSignal<int>(__sourceObs_s1, global::System.Collections.Generic.EqualityComparer<int>.Default);
                    global::ReactiveUI.Binding.IBindingTypeConverter __convertedForwardConverter = null;
                    if (__convertedForwardConverter == null)
                    {
                        __convertedForwardConverter = global::ReactiveUI.Binding.BindingConverters.Current.TypedConverters.TryGetConverter(typeof(int), typeof(int));
                        if (__convertedForwardConverter != null && __convertedForwardConverter.GetAffinityForObjects() <= 1)
                        {
                            __convertedForwardConverter = null;
                        }
                    }
                    var __convertedForward = __convertedForwardConverter == null ? (global::System.IObservable<int>)sourceObs : global::ReactiveUI.Primitives.LinqExtensions.Choose<int, int>(
                        sourceObs,
                        __value =>
                        {
                            object __hint = null;
                            if (__convertedForwardConverter != null)
                            {
                                if (__convertedForwardConverter is global::ReactiveUI.Binding.IBindingTypeConverter<int, int> __typed)
                                {
                                    int __converted;
                                    if (__typed.TryConvert(__value, __hint, out __converted))
                                    {
                                        return (true, __converted);
                                    }
                                }
                                else
                                {
                                    object __boxed;
                                    if (__convertedForwardConverter.TryConvertTyped(__value, __hint, out __boxed))
                                    {
                                        return (true, (int)__boxed);
                                    }
                                }
                                if (null == null)
                                {
                                    return (true, (int)__value);
                                }
                                return (false, default(int));
                            }
                            return true ? (true, (int)__value) : (true, (int)__value);
                        });
                    var viewThreadObs = global::ReactiveUI.Binding.BindingSchedulers.ObserveOnViewThread(__convertedForward, view);

                    var sub = global::ReactiveUI.Binding.BindingErrors.Subscribe(viewThreadObs, value =>
                    {
                        if (global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(view.Shown, value))
                        {
                            return;
                        }

                        view.Shown = value;
                    }, "v => v.Shown");

                    return new global::ReactiveUI.Binding.ReactiveBinding<global::TestApp.ViewBase<TViewModel>, int>(
                        view,
                        viewThreadObs,
                        global::ReactiveUI.Binding.BindingDirection.OneWay,
                        sub);
                }

            }
        }
    }
}

namespace System.Runtime.CompilerServices
{
    /// <summary>Binds a generated method to the call site it replaces.</summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : global::System.Attribute
    {
        /// <summary>Initializes a new instance of the <see cref="InterceptsLocationAttribute"/> class.</summary>
        /// <param name="version">The encoding of <paramref name="data"/>.</param>
        /// <param name="data">The call site being replaced.</param>
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}
