//HintName: ViewDispatch.g.cs
// <auto-generated/>
#pragma warning disable

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
            /// <summary>
            /// Triggers view dispatch registration when the generated bindings class is loaded.
            /// </summary>
            private static readonly bool __viewDispatchRegistered = __RegisterViewDispatch();

            /// <summary>
            /// Registers the source-generated view dispatch function with
            /// <see cref="global::ReactiveUI.Binding.DefaultViewLocator"/>.
            /// Called once via static field initializer when this class is first accessed.
            /// </summary>
            /// <returns>Always returns <see langword="true"/>.</returns>
            private static bool __RegisterViewDispatch()
            {
                global::ReactiveUI.Binding.DefaultViewLocator.SetGeneratedViewDispatch(
                    __TryResolveView);
                return true;
            }

            /// <summary>
            /// Compile-time generated type-switch dispatch for view resolution.
            /// Attempts to resolve a view for the given view model instance without reflection.
            /// </summary>
            /// <param name="instance">The view model instance to resolve a view for.</param>
            /// <param name="contract">The contract string (empty string for default).</param>
            /// <returns>The resolved view, or <see langword="null"/> if no generated mapping exists.</returns>
            private static global::ReactiveUI.Binding.IViewFor __TryResolveView(
                object instance, string contract)
            {
            // global::TestApp.NoCtorSingletonViewModel -> global::TestApp.NoCtorSingletonView
            if (instance is global::TestApp.NoCtorSingletonViewModel)
            {
                return __ResolveView_0(contract);
            }

                // No compile-time mapping found; fall back to runtime resolution.
                return null;
            }

            /// <summary>
            /// Resolves a view for <see cref="global::TestApp.NoCtorSingletonViewModel"/>.
        /// Service locator only — [SingleInstanceView] without parameterless constructor.
            /// </summary>
            /// <param name="contract">The contract string (empty string for default).</param>
            /// <returns>The resolved view, or <see langword="null"/> if resolution fails.</returns>
            private static global::ReactiveUI.Binding.IViewFor __ResolveView_0(string contract)
            {
                // Normalize contract: empty string means no contract (null for Splat lookup).
                string svcContract = contract.Length == 0 ? null : contract;

                // Prefer service-locator-registered view (supports DI-configured instances).
                var view = global::Splat.AppLocator.Current
                    .GetService<global::ReactiveUI.Binding.IViewFor<global::TestApp.NoCtorSingletonViewModel>>(
                        svcContract);
                if (view != null)
                {
                    return view;
                }
                return null;
            }
    }
}