//HintName: ViewThreadInvokers.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        private sealed class __WpfViewThreadInvoker : global::ReactiveUI.Binding.IViewThreadInvoker
        {
            internal static readonly __WpfViewThreadInvoker Instance = new __WpfViewThreadInvoker();

            public bool Claims(object target)
            {
                return target is global::System.Windows.Threading.DispatcherObject;
            }

            public bool CheckAccess(object target)
            {
                return ((global::System.Windows.Threading.DispatcherObject)target).CheckAccess();
            }

            public void Post(object target, global::System.Action<object?> callback, object? state)
            {
                var dispatcher = ((global::System.Windows.Threading.DispatcherObject)target).Dispatcher;
                if (dispatcher == null)
                {
                    callback(state);
                    return;
                }

                dispatcher.BeginInvoke(global::System.Windows.Threading.DispatcherPriority.Normal, callback, state);
            }
        }
    }
}
