//HintName: OneWayBindDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for OneWayBind from global::TestApp.MyViewModel to global::TestApp.MyView.
        /// Uses CallerArgumentExpression for dispatch.
        /// </summary>
        public static global::ReactiveUI.Binding.IReactiveBinding<global::TestApp.MyView, string> OneWayBind(
            this global::TestApp.MyView view,
            global::TestApp.MyViewModel viewModel,
            global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.MyViewModel, string?>> viewModelProperty,
            global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.MyView, string?>> viewProperty,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("viewModelProperty")] string viewModelPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("viewProperty")] string viewPropertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            if (viewModelPropertyExpression == "x => x.Name"
                && viewPropertyExpression == "x => x.Title")
            {
                return __OneWayBind_7FFFD5B3EB89C0AE(viewModel, view);
            }
            throw new global::System.InvalidOperationException(
                "No generated binding found. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::ReactiveUI.Binding.IReactiveBinding<global::TestApp.MyView, string> __OneWayBind_7FFFD5B3EB89C0AE(global::TestApp.MyViewModel viewModel, global::TestApp.MyView view)
        {
            // OneWayBind: Name -> Title
        if (global::ReactiveUI.Binding.BindingHooks.Any
            && !global::ReactiveUI.Binding.BindingHooks.ShouldBind(
                viewModel,
                view,
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(viewModel, null, viewModel),
                },
                () => new global::ReactiveUI.Binding.IObservedChange<object, object>[]
                {
                    new global::ReactiveUI.Binding.ObservedChange<object, object>(view, null, view),
                },
                global::ReactiveUI.Binding.BindingDirection.OneWay))
        {
            return null;
        }
        var sourceObsMechanism = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
            viewModel,
            "Name",
            (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::TestApp.MyViewModel)__o).Name,
            true);
        var sourceObsRegistration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(typeof(global::TestApp.MyViewModel), "Name", 5, false);
        var sourceObs = sourceObsRegistration == null
            ? (global::System.IObservable<string>)sourceObsMechanism
            : (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<string>(
                sourceObsRegistration,
                viewModel,
                ((global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.MyViewModel, string>>)(__e => __e.Name)).Body,
                "Name",
                (object __o) => ((global::TestApp.MyViewModel)__o).Name,
                false,
                true);
            var viewThreadObs = global::ReactiveUI.Binding.BindingSchedulers.ObserveOnViewThread(sourceObs, view, __WpfViewThreadInvoker.Instance);

            var sub = global::ReactiveUI.Binding.BindingErrors.Subscribe(viewThreadObs, value =>
            {
                if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(view.Title, value))
                    {
                        return;
                    }

                    view.Title = value;
            }, "x => x.Title");

            return new global::ReactiveUI.Binding.ReactiveBinding<global::TestApp.MyView, string>(
                view,
                viewThreadObs,
                global::ReactiveUI.Binding.BindingDirection.OneWay,
                sub);
        }

    }
}
