//HintName: ViewThreadInvokers.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        private sealed class __MauiViewThreadInvoker : global::ReactiveUI.Binding.IViewThreadInvoker
        {
            internal static readonly __MauiViewThreadInvoker Instance = new __MauiViewThreadInvoker();

            public bool Claims(object target)
            {
                return target is global::Microsoft.Maui.Controls.BindableObject;
            }

            public bool CheckAccess(object target)
            {
                var dispatcher = FindDispatcher((global::Microsoft.Maui.Controls.BindableObject)target);
                return dispatcher == null || !dispatcher.IsDispatchRequired;
            }

            public void Post(object target, global::System.Action<object?> callback, object? state)
            {
                var dispatcher = FindDispatcher((global::Microsoft.Maui.Controls.BindableObject)target);
                if (dispatcher == null)
                {
                    callback(state);
                    return;
                }

                dispatcher.Dispatch(() => callback(state));
            }

            private static global::Microsoft.Maui.Dispatching.IDispatcher? FindDispatcher(global::Microsoft.Maui.Controls.BindableObject owner)
            {
                try
                {
                    return owner.Dispatcher;
                }
                catch (global::System.InvalidOperationException)
                {
                    return null;
                }
            }
        }
    }
}
