//HintName: WhenAnyDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for WhenAny on global::SharedScenarios.WhenAny.DeepPropertyChain.ParentViewModel.
        /// </summary>
        public static global::System.IObservable<string> WhenAny(
            this global::SharedScenarios.WhenAny.DeepPropertyChain.ParentViewModel objectToMonitor,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.WhenAny.DeepPropertyChain.ParentViewModel, string>> property1,
            global::System.Func<global::ReactiveUI.Binding.IObservedChange<global::SharedScenarios.WhenAny.DeepPropertyChain.ParentViewModel, string>, string> selector,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property1")] string property1Expression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            property1Expression = property1Expression.StartsWith("static ") ? property1Expression.Substring(7) : property1Expression;

            if (property1Expression == "x => x.Child.Name")
            {
                return __WhenAny_0000044C01973FC2(objectToMonitor, selector);
            }
            throw new global::System.InvalidOperationException("No generated WhenAny dispatch matched. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IObservable<string> __WhenAny_0000044C01973FC2(global::SharedScenarios.WhenAny.DeepPropertyChain.ParentViewModel obj, global::System.Func<global::ReactiveUI.Binding.IObservedChange<global::SharedScenarios.WhenAny.DeepPropertyChain.ParentViewModel, string>, string> selector)
        {
            var __propObs0_s0 = (global::System.IObservable<global::SharedScenarios.WhenAny.DeepPropertyChain.ChildModel?>)new global::ReactiveUI.Binding.Observables.PropertyObservable<global::SharedScenarios.WhenAny.DeepPropertyChain.ChildModel?>(
                obj,
                "Child",
                static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.WhenAny.DeepPropertyChain.ParentViewModel)__o).Child,
                false);

        var __propObs0_s1 = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Switch(
            global::ReactiveUI.Binding.Observables.RxBindingExtensions.Select(__propObs0_s0,
                __propObs0_p1 => __propObs0_p1 != null
                    ? (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
                        __propObs0_p1,
                        "Name",
                        static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.WhenAny.DeepPropertyChain.ChildModel)__o).Name,
                        false)
                    : (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.ReturnObservable<string>(default(string))));
            var __propObs0 = global::ReactiveUI.Binding.Observables.RxBindingExtensions.DistinctUntilChanged(__propObs0_s1);


            return global::ReactiveUI.Binding.Observables.RxBindingExtensions.Select(__propObs0,
                value => selector(new global::ReactiveUI.Binding.ObservedChange<global::SharedScenarios.WhenAny.DeepPropertyChain.ParentViewModel, string>(obj, null, value)));
        }

    }
}
