//HintName: WhenAnyObservableDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for WhenAnyObservable on global::SharedScenarios.WhenAnyObservable.DeepObservableCombineLatest.ParentViewModel.
        /// </summary>
        public static global::System.IObservable<string> WhenAnyObservable(
            this global::SharedScenarios.WhenAnyObservable.DeepObservableCombineLatest.ParentViewModel objectToMonitor,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.WhenAnyObservable.DeepObservableCombineLatest.ParentViewModel, global::System.IObservable<int>?>> obs1,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.WhenAnyObservable.DeepObservableCombineLatest.ParentViewModel, global::System.IObservable<string>?>> obs2,
            global::System.Func<int, string, string> selector,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("obs1")] string obs1Expression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("obs2")] string obs2Expression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            obs1Expression = obs1Expression.StartsWith("static ") ? obs1Expression.Substring(7) : obs1Expression;
            obs2Expression = obs2Expression.StartsWith("static ") ? obs2Expression.Substring(7) : obs2Expression;

            if (obs1Expression == "x => x.Child.Count" && obs2Expression == "x => x.Child.Message")
            {
                return __WhenAnyObservable_7FFFF799BE875B2F(objectToMonitor, selector);
            }
            throw new global::System.InvalidOperationException("No generated WhenAnyObservable dispatch matched. This indicates a source generator caching issue.");
        }

        private static global::System.IObservable<string> __WhenAnyObservable_7FFFF799BE875B2F(global::SharedScenarios.WhenAnyObservable.DeepObservableCombineLatest.ParentViewModel obj, global::System.Func<int, string, string> selector)
        {
            var __obsProperty0_s0 = (global::System.IObservable<global::SharedScenarios.WhenAnyObservable.DeepObservableCombineLatest.ChildModel?>)new global::ReactiveUI.Binding.Observables.PropertyObservable<global::SharedScenarios.WhenAnyObservable.DeepObservableCombineLatest.ChildModel?>(
                obj,
                "Child",
                static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.WhenAnyObservable.DeepObservableCombineLatest.ParentViewModel)__o).Child,
                false);

        var __obsProperty0_s1 = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Switch(
            global::ReactiveUI.Binding.Observables.RxBindingExtensions.Select(__obsProperty0_s0,
                __obsProperty0_p1 => __obsProperty0_p1 != null
                    ? (global::System.IObservable<global::System.IObservable<int>>)new global::ReactiveUI.Binding.Observables.PropertyObservable<global::System.IObservable<int>>(
                        __obsProperty0_p1,
                        "Count",
                        static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.WhenAnyObservable.DeepObservableCombineLatest.ChildModel)__o).Count,
                        false)
                    : (global::System.IObservable<global::System.IObservable<int>>)new global::ReactiveUI.Binding.Observables.ReturnObservable<global::System.IObservable<int>>(default(global::System.IObservable<int>))));
            var __obsProperty0 = global::ReactiveUI.Binding.Observables.RxBindingExtensions.DistinctUntilChanged(__obsProperty0_s1);


            var __switched0 = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Switch(
                global::ReactiveUI.Binding.Observables.RxBindingExtensions.Select(__obsProperty0,
                    __obs => __obs ?? (global::System.IObservable<int>)global::ReactiveUI.Binding.Observables.EmptyObservable<int>.Instance));

            var __obsProperty1_s0 = (global::System.IObservable<global::SharedScenarios.WhenAnyObservable.DeepObservableCombineLatest.ChildModel?>)new global::ReactiveUI.Binding.Observables.PropertyObservable<global::SharedScenarios.WhenAnyObservable.DeepObservableCombineLatest.ChildModel?>(
                obj,
                "Child",
                static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.WhenAnyObservable.DeepObservableCombineLatest.ParentViewModel)__o).Child,
                false);

        var __obsProperty1_s1 = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Switch(
            global::ReactiveUI.Binding.Observables.RxBindingExtensions.Select(__obsProperty1_s0,
                __obsProperty1_p1 => __obsProperty1_p1 != null
                    ? (global::System.IObservable<global::System.IObservable<string>>)new global::ReactiveUI.Binding.Observables.PropertyObservable<global::System.IObservable<string>>(
                        __obsProperty1_p1,
                        "Message",
                        static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.WhenAnyObservable.DeepObservableCombineLatest.ChildModel)__o).Message,
                        false)
                    : (global::System.IObservable<global::System.IObservable<string>>)new global::ReactiveUI.Binding.Observables.ReturnObservable<global::System.IObservable<string>>(default(global::System.IObservable<string>))));
            var __obsProperty1 = global::ReactiveUI.Binding.Observables.RxBindingExtensions.DistinctUntilChanged(__obsProperty1_s1);


            var __switched1 = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Switch(
                global::ReactiveUI.Binding.Observables.RxBindingExtensions.Select(__obsProperty1,
                    __obs => __obs ?? (global::System.IObservable<string>)global::ReactiveUI.Binding.Observables.EmptyObservable<string>.Instance));

            return global::ReactiveUI.Binding.Observables.CombineLatestObservable.Create(
                __switched0,
                __switched1,
                selector);
        }

    }
}
