//HintName: WhenAnyObservableDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for WhenAnyObservable on global::SharedScenarios.WhenAnyObservable.DeepObservableSwitch.ParentViewModel.
        /// </summary>
        public static global::System.IObservable<string> WhenAnyObservable(
            this global::SharedScenarios.WhenAnyObservable.DeepObservableSwitch.ParentViewModel objectToMonitor,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.WhenAnyObservable.DeepObservableSwitch.ParentViewModel, global::System.IObservable<string>?>> obs1,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("obs1")] string obs1Expression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            obs1Expression = obs1Expression.StartsWith("static ") ? obs1Expression.Substring(7) : obs1Expression;

            if (obs1Expression == "x => x.Child.MyCommand")
            {
                return __WhenAnyObservable_7FFFD9447DB2EEEE(objectToMonitor);
            }
            throw new global::System.InvalidOperationException("No generated WhenAnyObservable dispatch matched. This indicates a source generator caching issue.");
        }

        private static global::System.IObservable<string> __WhenAnyObservable_7FFFD9447DB2EEEE(global::SharedScenarios.WhenAnyObservable.DeepObservableSwitch.ParentViewModel obj)
        {
            var __obsProperty_s0 = (global::System.IObservable<global::SharedScenarios.WhenAnyObservable.DeepObservableSwitch.ChildModel?>)new global::ReactiveUI.Binding.Observables.PropertyObservable<global::SharedScenarios.WhenAnyObservable.DeepObservableSwitch.ChildModel?>(
                obj,
                "Child",
                static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.WhenAnyObservable.DeepObservableSwitch.ParentViewModel)__o).Child,
                false);

        var __obsProperty_s1 = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Switch(
            global::ReactiveUI.Binding.Observables.RxBindingExtensions.Select(__obsProperty_s0,
                __obsProperty_p1 => __obsProperty_p1 != null
                    ? (global::System.IObservable<global::System.IObservable<string>>)new global::ReactiveUI.Binding.Observables.PropertyObservable<global::System.IObservable<string>>(
                        __obsProperty_p1,
                        "MyCommand",
                        static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.WhenAnyObservable.DeepObservableSwitch.ChildModel)__o).MyCommand,
                        false)
                    : (global::System.IObservable<global::System.IObservable<string>>)new global::ReactiveUI.Binding.Observables.ReturnObservable<global::System.IObservable<string>>(default(global::System.IObservable<string>))));
            var __obsProperty = global::ReactiveUI.Binding.Observables.RxBindingExtensions.DistinctUntilChanged(__obsProperty_s1);


            return global::ReactiveUI.Binding.Observables.RxBindingExtensions.Switch(
                global::ReactiveUI.Binding.Observables.RxBindingExtensions.Select(__obsProperty,
                    __obs => __obs ?? (global::System.IObservable<string>)global::ReactiveUI.Binding.Observables.EmptyObservable<string>.Instance));
        }

    }
}
