//HintName: WhenAnyValueDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for WhenAnyValue on global::SharedScenarios.WhenAnyValue.DeepPropertyChain.ParentViewModel.
        /// </summary>
        public static global::System.IObservable<string> WhenAnyValue(
            this global::SharedScenarios.WhenAnyValue.DeepPropertyChain.ParentViewModel objectToMonitor,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.WhenAnyValue.DeepPropertyChain.ParentViewModel, string>> property1,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property1")] string property1Expression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            property1Expression = property1Expression.StartsWith("static ", global::System.StringComparison.Ordinal) ? property1Expression.Substring(7) : property1Expression;

            if (property1Expression == "x => x.Child.Name")
            {
                return __WhenAnyValue_000009AD7646CA30(objectToMonitor);
            }
            return global::ReactiveUI.Binding.ReactiveUIBindingExtensions.WhenAnyValue<global::SharedScenarios.WhenAnyValue.DeepPropertyChain.ParentViewModel, string>(objectToMonitor, property1);
        }

        private static global::System.IObservable<string> __WhenAnyValue_000009AD7646CA30(global::SharedScenarios.WhenAnyValue.DeepPropertyChain.ParentViewModel obj)
        {
            var __obs0Mechanism = (global::System.IObservable<global::SharedScenarios.WhenAnyValue.DeepPropertyChain.ChildModel>)new global::ReactiveUI.Binding.Observables.PropertyObservable<global::SharedScenarios.WhenAnyValue.DeepPropertyChain.ChildModel>(
                obj,
                "Child",
                (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.WhenAnyValue.DeepPropertyChain.ParentViewModel)__o).Child,
                false);
            var __obs0Registration = global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(typeof(global::SharedScenarios.WhenAnyValue.DeepPropertyChain.ParentViewModel), "Child", 5, false);
            var __obs0 = __obs0Registration == null
                ? (global::System.IObservable<global::SharedScenarios.WhenAnyValue.DeepPropertyChain.ChildModel>)__obs0Mechanism
                : (global::System.IObservable<global::SharedScenarios.WhenAnyValue.DeepPropertyChain.ChildModel>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<global::SharedScenarios.WhenAnyValue.DeepPropertyChain.ChildModel>(
                    __obs0Registration,
                    obj,
                    ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.WhenAnyValue.DeepPropertyChain.ParentViewModel, global::SharedScenarios.WhenAnyValue.DeepPropertyChain.ChildModel>>)(__e => __e.Child)).Body,
                    "Child",
                    (object __o) => ((global::SharedScenarios.WhenAnyValue.DeepPropertyChain.ParentViewModel)__o).Child,
                    false,
                    true);
        var __obs1 = new global::ReactiveUI.Primitives.Advanced.SwitchMapSignal<global::SharedScenarios.WhenAnyValue.DeepPropertyChain.ChildModel, string>(__obs0,
            __parent1 => __parent1 != null
                ? global::ReactiveUI.Binding.Observables.PluginObservationSource.Choose<string>(
                    __parent1,
                    ((global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.WhenAnyValue.DeepPropertyChain.ChildModel, string>>)(__e => __e.Name)).Body,
                    "Name",
                    false,
                    5,
                    (object __o) => ((global::SharedScenarios.WhenAnyValue.DeepPropertyChain.ChildModel)__o).Name,
                    new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
                        (global::System.ComponentModel.INotifyPropertyChanged)__parent1,
                        "Name",
                        (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.WhenAnyValue.DeepPropertyChain.ChildModel)__o).Name,
                        false))
                : (global::System.IObservable<string>)global::ReactiveUI.Primitives.Advanced.ImmutableEmptySignal<string>.Instance);
            return global::ReactiveUI.Primitives.LinqExtensions.DistinctUntilChanged(__obs1);
        }

    }
}
