//HintName: WhenChangedDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for WhenChanged on global::TestApp.MyWinFormsControl.
        /// </summary>
        public static global::System.IObservable<string> WhenChanged(
            this global::TestApp.MyWinFormsControl objectToMonitor,
            global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.MyWinFormsControl, string>> property1,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property1")] string property1Expression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            property1Expression = property1Expression.StartsWith("static ", global::System.StringComparison.Ordinal) ? property1Expression.Substring(7) : property1Expression;

            if (property1Expression == "x => x.Text")
            {
                return __WhenChanged_0000245FAC302C0E(objectToMonitor);
            }
            return global::ReactiveUI.Binding.ReactiveUIBindingExtensions.WhenChanged<global::TestApp.MyWinFormsControl, string>(objectToMonitor, property1);
        }

        private static global::System.IObservable<string> __WhenChanged_0000245FAC302C0E(global::TestApp.MyWinFormsControl obj)
        {
            return (global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(obj.GetType(), "Text", 8, false) is global::ReactiveUI.Binding.ICreatesObservableForProperty __registration_obj
                ? (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<string>(
                __registration_obj,
                obj,
                ((global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.MyWinFormsControl, string>>)(__e => __e.Text)).Body,
                "Text",
                (object __o) => ((global::TestApp.MyWinFormsControl)__o).Text,
                false, false)
                : (global::System.IObservable<string>)
                new __WinFormsObservable<global::TestApp.MyWinFormsControl, string>((global::TestApp.MyWinFormsControl)obj, (__source, __notify) =>
                    {
                        global::System.EventHandler __handler0 = (__sender, __args) => __notify();
                        __source.TextChanged += __handler0;
                        return new global::ReactiveUI.Primitives.Disposables.ActionDisposable(() =>
                        {
                            __source.TextChanged -= __handler0;
                        });
                    }, __source => __source.Text, true));
        }

    }
}
