//HintName: WhenChangedDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for WhenChanged on global::TestApp.MyWinUIControl.
        /// </summary>
        public static global::System.IObservable<string> WhenChanged(
            this global::TestApp.MyWinUIControl objectToMonitor,
            global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.MyWinUIControl, string>> property1,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property1")] string property1Expression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            property1Expression = property1Expression.StartsWith("static ") ? property1Expression.Substring(7) : property1Expression;

            // Allow user-registered plugins with higher affinity to override generated observation
            if (global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.HasHigherAffinityPlugin(typeof(global::TestApp.MyWinUIControl), 6, false))
            {
                return global::ReactiveUI.Binding.Fallback.RuntimeObservationFallback.WhenChanged(objectToMonitor, property1);
            }

            if (property1Expression == "x => x.Text")
            {
                return __WhenChanged_7FFFDEC5A322381F(objectToMonitor);
            }
            throw new global::System.InvalidOperationException("No generated WhenChanged dispatch matched. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IObservable<string> __WhenChanged_7FFFDEC5A322381F(global::TestApp.MyWinUIControl obj)
        {
            return new __WinUIDPObservable<string>((global::Microsoft.UI.Xaml.DependencyObject)obj, global::TestApp.MyWinUIControl.TextProperty, (global::Microsoft.UI.Xaml.DependencyObject __o) => ((global::TestApp.MyWinUIControl)__o).Text, true);
        }

    }
}
