//HintName: WhenChangedDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for WhenChanged on global::TestApp.MyAppleView.
        /// </summary>
        public static global::System.IObservable<string> WhenChanged(
            this global::TestApp.MyAppleView objectToMonitor,
            global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.MyAppleView, string>> property1,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property1")] string property1Expression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            property1Expression = property1Expression.StartsWith("static ") ? property1Expression.Substring(7) : property1Expression;

            if (property1Expression == "x => x.Text")
            {
                return __WhenChanged_000018C06482B8DB(objectToMonitor);
            }
            throw new global::System.InvalidOperationException("No generated WhenChanged dispatch matched. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IObservable<string> __WhenChanged_000018C06482B8DB(global::TestApp.MyAppleView obj)
        {
            return new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
                obj,
                "Text",
                static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::TestApp.MyAppleView)__o).Text,
                true);
        }

    }
}
