//HintName: WhenChangedDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for WhenChanged on global::SharedScenarios.WhenChanged.NullableProperty.MyViewModel.
        /// </summary>
        public static global::System.IObservable<string> WhenChanged(
            this global::SharedScenarios.WhenChanged.NullableProperty.MyViewModel objectToMonitor,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.WhenChanged.NullableProperty.MyViewModel, string>> property1,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property1")] string property1Expression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            property1Expression = property1Expression.StartsWith("static ") ? property1Expression.Substring(7) : property1Expression;

            if (property1Expression == "x => x.NullableName!")
            {
                return __WhenChanged_7FFFF613BD504CA2(objectToMonitor);
            }
            throw new global::System.InvalidOperationException("No generated WhenChanged dispatch matched. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IObservable<string> __WhenChanged_7FFFF613BD504CA2(global::SharedScenarios.WhenChanged.NullableProperty.MyViewModel obj)
        {
            return new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
                obj,
                "NullableName",
                static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.WhenChanged.NullableProperty.MyViewModel)__o).NullableName,
                true);
        }

    }
}
