//HintName: WhenChangedDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for WhenChanged on global::SharedScenarios.WhenChanged.NullForgivingDeepChain.ParentViewModel.
        /// </summary>
        public static global::System.IObservable<string> WhenChanged(
            this global::SharedScenarios.WhenChanged.NullForgivingDeepChain.ParentViewModel objectToMonitor,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.WhenChanged.NullForgivingDeepChain.ParentViewModel, string>> property1,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property1")] string property1Expression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            property1Expression = property1Expression.StartsWith("static ") ? property1Expression.Substring(7) : property1Expression;

            if (property1Expression == "x => x.Child!.Name")
            {
                return __WhenChanged_7FFFCA7893201DA1(objectToMonitor);
            }
            throw new global::System.InvalidOperationException("No generated WhenChanged dispatch matched. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IObservable<string> __WhenChanged_7FFFCA7893201DA1(global::SharedScenarios.WhenChanged.NullForgivingDeepChain.ParentViewModel obj)
        {
            var __obs0 = (global::System.IObservable<global::SharedScenarios.WhenChanged.NullForgivingDeepChain.ChildModel?>)new global::ReactiveUI.Binding.Observables.PropertyObservable<global::SharedScenarios.WhenChanged.NullForgivingDeepChain.ChildModel?>(
                obj,
                "Child",
                static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.WhenChanged.NullForgivingDeepChain.ParentViewModel)__o).Child,
                false);

        var __obs1 = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Switch(
            global::ReactiveUI.Binding.Observables.RxBindingExtensions.Select(__obs0,
                __parent1 => __parent1 != null
                    ? (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
                        __parent1,
                        "Name",
                        static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.WhenChanged.NullForgivingDeepChain.ChildModel)__o).Name,
                        false)
                    : (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.ReturnObservable<string>(default(string))));
            return global::ReactiveUI.Binding.Observables.RxBindingExtensions.DistinctUntilChanged(__obs1);
        }

    }
}
