//HintName: WhenChangedDispatch.g.cs
// <auto-generated/>
#pragma warning disable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for WhenChanged on global::SharedScenarios.WhenChanged.MultiPropertyWithSelector.MyViewModel.
        /// </summary>
        public static global::System.IObservable<string> WhenChanged(
            this global::SharedScenarios.WhenChanged.MultiPropertyWithSelector.MyViewModel objectToMonitor,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.WhenChanged.MultiPropertyWithSelector.MyViewModel, string>> property1,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.WhenChanged.MultiPropertyWithSelector.MyViewModel, string>> property2,
            global::System.Func<string, string, string> selector,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property1")] string property1Expression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property2")] string property2Expression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            property1Expression = property1Expression.StartsWith("static ") ? property1Expression.Substring(7) : property1Expression;
            property2Expression = property2Expression.StartsWith("static ") ? property2Expression.Substring(7) : property2Expression;

            // Allow user-registered plugins with higher affinity to override generated observation
            if (global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.HasHigherAffinityPlugin(typeof(global::SharedScenarios.WhenChanged.MultiPropertyWithSelector.MyViewModel), 5, false))
            {
                return new global::ReactiveUI.Binding.Observables.SelectObservable<global::System.ValueTuple<string, string>, string>(
                    global::ReactiveUI.Binding.Fallback.RuntimeObservationFallback.WhenChanged(objectToMonitor, property1, property2),
                    __t => selector(__t.Item1, __t.Item2));
            }

            if (property1Expression == "x => x.FirstName" && property2Expression == "x => x.LastName")
            {
                return __WhenChanged_00002EE07F1838FC(objectToMonitor, selector);
            }
            throw new global::System.InvalidOperationException("No generated WhenChanged dispatch matched. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IObservable<string> __WhenChanged_00002EE07F1838FC(global::SharedScenarios.WhenChanged.MultiPropertyWithSelector.MyViewModel obj, global::System.Func<string, string, string> selector)
        {
            var __propObs0 = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
                obj,
                "FirstName",
                (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.WhenChanged.MultiPropertyWithSelector.MyViewModel)__o).FirstName,
                true);

            var __propObs1 = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
                obj,
                "LastName",
                (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.WhenChanged.MultiPropertyWithSelector.MyViewModel)__o).LastName,
                true);

            return global::ReactiveUI.Binding.Observables.CombineLatestObservable.Create(
                __propObs0,
                __propObs1,
                selector);
        }

    }
}
