//HintName: WhenChangedDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for WhenChanged on global::TestApp.MyUnoControl.
        /// </summary>
        public static global::System.IObservable<string> WhenChanged(
            this global::TestApp.MyUnoControl objectToMonitor,
            global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.MyUnoControl, string?>> property1,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property1")] string property1Expression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            if (property1Expression == "x => x.Text")
            {
                return __WhenChanged_000008A2EA56CFDF(objectToMonitor);
            }
            return global::ReactiveUI.Binding.ReactiveUIBindingExtensions.WhenChanged<global::TestApp.MyUnoControl, string>(objectToMonitor, property1);
        }

        private static global::System.IObservable<string> __WhenChanged_000008A2EA56CFDF(global::TestApp.MyUnoControl obj)
        {
            return (global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(obj.GetType(), "Text", 6, false) is global::ReactiveUI.Binding.ICreatesObservableForProperty __registration_obj
                ? (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<string>(
                    __registration_obj,
                    obj,
                    ((global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.MyUnoControl, string>>)(__e => __e.Text)).Body,
                    "Text",
                    (object __o) => ((global::TestApp.MyUnoControl)__o).Text,
                    false, false)
                : (global::System.IObservable<string>)
                new global::ReactiveUI.Binding.Observables.CallbackPropertyObservable<global::TestApp.MyUnoControl, string>((global::TestApp.MyUnoControl)obj, (__source, __notify) =>
                    {
                        var __token = __source.RegisterPropertyChangedCallback(global::TestApp.MyUnoControl.TextProperty, (__sender, __property) => __notify());
                        return new global::ReactiveUI.Primitives.Disposables.ActionDisposable(() =>
                            __source.UnregisterPropertyChangedCallback(global::TestApp.MyUnoControl.TextProperty, __token));
                    }, __source => __source.Text, true));
        }

    }
}
