//HintName: WhenChangedDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for WhenChanged on global::SharedScenarios.WhenChanged.SinglePropertyINPC.MyViewModel.
        /// </summary>
        public static global::System.IObservable<string> WhenChanged(
            this global::SharedScenarios.WhenChanged.SinglePropertyINPC.MyViewModel objectToMonitor,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.WhenChanged.SinglePropertyINPC.MyViewModel, string>> property1,
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            if (callerLineNumber == 53 && callerFilePath.EndsWith("", global::System.StringComparison.OrdinalIgnoreCase))
            {
                return __WhenChanged_7FFFD2E8D6FC87F9(objectToMonitor);
            }
            throw new global::System.InvalidOperationException("No generated WhenChanged dispatch matched. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IObservable<string> __WhenChanged_7FFFD2E8D6FC87F9(global::SharedScenarios.WhenChanged.SinglePropertyINPC.MyViewModel obj)
        {
            return new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
                obj,
                "Name",
                static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.WhenChanged.SinglePropertyINPC.MyViewModel)__o).Name,
                true);
        }

    }
}
