//HintName: ObservationHelpers.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {        private sealed class __WinFormsObservable<TSource, TValue> : global::System.IObservable<TValue>
        {
            private readonly TSource _source;
            private readonly global::System.Func<TSource, global::System.Action, global::System.IDisposable> _subscribe;
            private readonly global::System.Func<TSource, TValue> _getter;
            private readonly bool _distinct;
            internal __WinFormsObservable(TSource source,
                global::System.Func<TSource, global::System.Action, global::System.IDisposable> subscribe,
                global::System.Func<TSource, TValue> getter, bool distinct)
            {
                _source = source;
                _subscribe = subscribe;
                _getter = getter;
                _distinct = distinct;
            }
            public global::System.IDisposable Subscribe(global::System.IObserver<TValue> observer)
            {
                if (observer == null) throw new global::System.ArgumentNullException(nameof(observer));
                return new Subscription(this, observer);
            }
            private sealed class Subscription : global::System.IDisposable
            {
                private readonly __WinFormsObservable<TSource, TValue> _parent;
                private readonly global::System.IDisposable _inner;
                private global::System.IObserver<TValue> _observer;
                private TValue _lastValue;
                private bool _hasValue;
                internal Subscription(__WinFormsObservable<TSource, TValue> parent, global::System.IObserver<TValue> observer)
                {
                    _parent = parent;
                    _observer = observer;
                    _inner = parent._subscribe(parent._source, Publish);
                    try
                    {
                        Publish();
                    }
                    catch
                    {
                        Dispose();
                        throw;
                    }
                }
                public void Dispose()
                {
                    if (global::System.Threading.Interlocked.Exchange(ref _observer, null) != null)
                    {
                        _inner.Dispose();
                    }
                }
                private void Publish()
                {
                    var observer = global::System.Threading.Volatile.Read(ref _observer);
                    if (observer == null)
                    {
                        return;
                    }
                    var value = _parent._getter(_parent._source);
                    if (_parent._distinct && _hasValue && global::System.Collections.Generic.EqualityComparer<TValue>.Default.Equals(_lastValue, value))
                    {
                        return;
                    }
                    _lastValue = value;
                    _hasValue = true;
                    observer.OnNext(value);
                }
            }
        }
    }
}
