//HintName: WhenChangedDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for WhenChanged on global::TestApp.MyAppleView.
        /// </summary>
        public static global::System.IObservable<string> WhenChanged(
            this global::TestApp.MyAppleView objectToMonitor,
            global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.MyAppleView, string?>> property1,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property1")] string property1Expression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            if (property1Expression == "x => x.Text")
            {
                return __WhenChanged_000018C06482B4BD(objectToMonitor);
            }
            return global::ReactiveUI.Binding.ReactiveUIBindingExtensions.WhenChanged<global::TestApp.MyAppleView, string>(objectToMonitor, property1);
        }

        private static global::System.IObservable<string> __WhenChanged_000018C06482B4BD(global::TestApp.MyAppleView obj)
        {
            return (global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(obj.GetType(), "Text", 5, false) is global::ReactiveUI.Binding.ICreatesObservableForProperty __registration_obj
                ? (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.PluginPropertyObservable<string>(
                    __registration_obj,
                    obj,
                    ((global::System.Linq.Expressions.Expression<global::System.Func<global::TestApp.MyAppleView, string>>)(__e => __e.Text)).Body,
                    "Text",
                    (object __o) => ((global::TestApp.MyAppleView)__o).Text,
                    false, false)
                : (global::System.IObservable<string>)
                new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(obj, "Text", (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::TestApp.MyAppleView)__o).Text, true));
        }

    }
}
