//HintName: WhenChangingDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.TestAssembly
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for WhenChanging on global::SharedScenarios.WhenChanging.MultiPropertyThreeProperties.MyViewModel.
        /// </summary>
        public static global::System.IObservable<global::ReactiveUI.Binding.PropertyValues<string, int, double>> WhenChanging(
            this global::SharedScenarios.WhenChanging.MultiPropertyThreeProperties.MyViewModel objectToMonitor,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.WhenChanging.MultiPropertyThreeProperties.MyViewModel, string>> property1,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.WhenChanging.MultiPropertyThreeProperties.MyViewModel, int>> property2,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.WhenChanging.MultiPropertyThreeProperties.MyViewModel, double>> property3,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property1")] string property1Expression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property2")] string property2Expression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property3")] string property3Expression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            property1Expression = property1Expression.StartsWith("static ", global::System.StringComparison.Ordinal) ? property1Expression.Substring(7) : property1Expression;
            property2Expression = property2Expression.StartsWith("static ", global::System.StringComparison.Ordinal) ? property2Expression.Substring(7) : property2Expression;
            property3Expression = property3Expression.StartsWith("static ", global::System.StringComparison.Ordinal) ? property3Expression.Substring(7) : property3Expression;

            // Allow user-registered plugins with higher affinity to override generated observation
            if (global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.HasHigherAffinityPlugin(typeof(global::SharedScenarios.WhenChanging.MultiPropertyThreeProperties.MyViewModel), 5, true))
            {
                return global::ReactiveUI.Binding.Fallback.RuntimeObservationFallback.WhenChanging(objectToMonitor, property1, property2, property3);
            }

            if (property1Expression == "x => x.Name" && property2Expression == "x => x.Age" && property3Expression == "x => x.Score")
            {
                return __WhenChanging_7FFFF53EB8A56F90(objectToMonitor);
            }
            throw new global::System.InvalidOperationException("No generated WhenChanging dispatch matched. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IObservable<global::ReactiveUI.Binding.PropertyValues<string, int, double>> __WhenChanging_7FFFF53EB8A56F90(global::SharedScenarios.WhenChanging.MultiPropertyThreeProperties.MyViewModel obj)
        {
            var __propObs0 = new global::ReactiveUI.Binding.Observables.PropertyChangingObservable<string>(
                (global::System.ComponentModel.INotifyPropertyChanging)obj,
                "Name",
                (global::System.ComponentModel.INotifyPropertyChanging __o) => ((global::SharedScenarios.WhenChanging.MultiPropertyThreeProperties.MyViewModel)__o).Name);

            var __propObs1 = new global::ReactiveUI.Binding.Observables.PropertyChangingObservable<int>(
                (global::System.ComponentModel.INotifyPropertyChanging)obj,
                "Age",
                (global::System.ComponentModel.INotifyPropertyChanging __o) => ((global::SharedScenarios.WhenChanging.MultiPropertyThreeProperties.MyViewModel)__o).Age);

            var __propObs2 = new global::ReactiveUI.Binding.Observables.PropertyChangingObservable<double>(
                (global::System.ComponentModel.INotifyPropertyChanging)obj,
                "Score",
                (global::System.ComponentModel.INotifyPropertyChanging __o) => ((global::SharedScenarios.WhenChanging.MultiPropertyThreeProperties.MyViewModel)__o).Score);

            return global::ReactiveUI.Primitives.LinqExtensions.CombineLatest(
                __propObs0,
                __propObs1,
                __propObs2,
                (p1, p2, p3) => new global::ReactiveUI.Binding.PropertyValues<string, int, double>(p1, p2, p3));
        }

    }
}
