//HintName: WhenChangingDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for WhenChanging on global::SharedScenarios.WhenChanging.FourLevelDeepChain.Level1.
        /// </summary>
        public static global::System.IObservable<string> WhenChanging(
            this global::SharedScenarios.WhenChanging.FourLevelDeepChain.Level1 objectToMonitor,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.WhenChanging.FourLevelDeepChain.Level1, string>> property1,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property1")] string property1Expression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            property1Expression = property1Expression.StartsWith("static ") ? property1Expression.Substring(7) : property1Expression;

            if (property1Expression == "x => x.Model.Model.Model.Value")
            {
                return __WhenChanging_00001C315F48FB20(objectToMonitor);
            }
            throw new global::System.InvalidOperationException("No generated WhenChanging dispatch matched. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IObservable<string> __WhenChanging_00001C315F48FB20(global::SharedScenarios.WhenChanging.FourLevelDeepChain.Level1 obj)
        {
            var __obs0 = (global::System.IObservable<global::SharedScenarios.WhenChanging.FourLevelDeepChain.Level2?>)new global::ReactiveUI.Binding.Observables.PropertyChangingObservable<global::SharedScenarios.WhenChanging.FourLevelDeepChain.Level2?>(
                (global::System.ComponentModel.INotifyPropertyChanging)obj,
                "Model",
                static (global::System.ComponentModel.INotifyPropertyChanging __o) => ((global::SharedScenarios.WhenChanging.FourLevelDeepChain.Level1)__o).Model);

        var __obs1 = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Switch(
            global::ReactiveUI.Binding.Observables.RxBindingExtensions.Select(__obs0,
                __parent1 => __parent1 != null
                    ? (global::System.IObservable<global::SharedScenarios.WhenChanging.FourLevelDeepChain.Level3?>)new global::ReactiveUI.Binding.Observables.PropertyChangingObservable<global::SharedScenarios.WhenChanging.FourLevelDeepChain.Level3?>(
                        (global::System.ComponentModel.INotifyPropertyChanging)__parent1,
                        "Model",
                        static (global::System.ComponentModel.INotifyPropertyChanging __o) => ((global::SharedScenarios.WhenChanging.FourLevelDeepChain.Level2)__o).Model)
                    : (global::System.IObservable<global::SharedScenarios.WhenChanging.FourLevelDeepChain.Level3?>)new global::ReactiveUI.Binding.Observables.ReturnObservable<global::SharedScenarios.WhenChanging.FourLevelDeepChain.Level3?>(default(global::SharedScenarios.WhenChanging.FourLevelDeepChain.Level3?))));

        var __obs2 = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Switch(
            global::ReactiveUI.Binding.Observables.RxBindingExtensions.Select(__obs1,
                __parent2 => __parent2 != null
                    ? (global::System.IObservable<global::SharedScenarios.WhenChanging.FourLevelDeepChain.Model?>)new global::ReactiveUI.Binding.Observables.PropertyChangingObservable<global::SharedScenarios.WhenChanging.FourLevelDeepChain.Model?>(
                        (global::System.ComponentModel.INotifyPropertyChanging)__parent2,
                        "Model",
                        static (global::System.ComponentModel.INotifyPropertyChanging __o) => ((global::SharedScenarios.WhenChanging.FourLevelDeepChain.Level3)__o).Model)
                    : (global::System.IObservable<global::SharedScenarios.WhenChanging.FourLevelDeepChain.Model?>)new global::ReactiveUI.Binding.Observables.ReturnObservable<global::SharedScenarios.WhenChanging.FourLevelDeepChain.Model?>(default(global::SharedScenarios.WhenChanging.FourLevelDeepChain.Model?))));

        var __obs3 = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Switch(
            global::ReactiveUI.Binding.Observables.RxBindingExtensions.Select(__obs2,
                __parent3 => __parent3 != null
                    ? (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.PropertyChangingObservable<string>(
                        (global::System.ComponentModel.INotifyPropertyChanging)__parent3,
                        "Value",
                        static (global::System.ComponentModel.INotifyPropertyChanging __o) => ((global::SharedScenarios.WhenChanging.FourLevelDeepChain.Model)__o).Value)
                    : (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.ReturnObservable<string>(default(string))));
            return __obs3;
        }

    }
}
