//HintName: WhenChangingDispatch.g.cs
// <auto-generated/>
#pragma warning disable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for WhenChanging on global::SharedScenarios.WhenChanging.MultiPropertyWithDeepChains.MyViewModel.
        /// </summary>
        public static global::System.IObservable<string> WhenChanging(
            this global::SharedScenarios.WhenChanging.MultiPropertyWithDeepChains.MyViewModel objectToMonitor,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.WhenChanging.MultiPropertyWithDeepChains.MyViewModel, string>> property1,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.WhenChanging.MultiPropertyWithDeepChains.MyViewModel, string>> property2,
            global::System.Func<string, string, string> selector,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property1")] string property1Expression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property2")] string property2Expression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            property1Expression = property1Expression.StartsWith("static ") ? property1Expression.Substring(7) : property1Expression;
            property2Expression = property2Expression.StartsWith("static ") ? property2Expression.Substring(7) : property2Expression;

            // Allow user-registered plugins with higher affinity to override generated observation
            if (global::ReactiveUI.Binding.Fallback.ObservationAffinityChecker.HasHigherAffinityPlugin(typeof(global::SharedScenarios.WhenChanging.MultiPropertyWithDeepChains.MyViewModel), 5, true))
            {
                return new global::ReactiveUI.Binding.Observables.SelectObservable<global::System.ValueTuple<string, string>, string>(
                    global::ReactiveUI.Binding.Fallback.RuntimeObservationFallback.WhenChanging(objectToMonitor, property1, property2),
                    __t => selector(__t.Item1, __t.Item2));
            }

            if (property1Expression == "x => x.Address.City" && property2Expression == "x => x.Name")
            {
                return __WhenChanging_7FFFFF97E6DC5B33(objectToMonitor, selector);
            }
            throw new global::System.InvalidOperationException("No generated WhenChanging dispatch matched. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IObservable<string> __WhenChanging_7FFFFF97E6DC5B33(global::SharedScenarios.WhenChanging.MultiPropertyWithDeepChains.MyViewModel obj, global::System.Func<string, string, string> selector)
        {
            var __propObs0_s0 = (global::System.IObservable<global::SharedScenarios.WhenChanging.MultiPropertyWithDeepChains.AddressModel>)new global::ReactiveUI.Binding.Observables.PropertyChangingObservable<global::SharedScenarios.WhenChanging.MultiPropertyWithDeepChains.AddressModel>(
                (global::System.ComponentModel.INotifyPropertyChanging)obj,
                "Address",
                (global::System.ComponentModel.INotifyPropertyChanging __o) => ((global::SharedScenarios.WhenChanging.MultiPropertyWithDeepChains.MyViewModel)__o).Address);

        var __propObs0_s1 = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Switch(
            global::ReactiveUI.Binding.Observables.RxBindingExtensions.Select(__propObs0_s0,
                __propObs0_p1 => __propObs0_p1 != null
                    ? (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.PropertyChangingObservable<string>(
                        (global::System.ComponentModel.INotifyPropertyChanging)__propObs0_p1,
                        "City",
                        (global::System.ComponentModel.INotifyPropertyChanging __o) => ((global::SharedScenarios.WhenChanging.MultiPropertyWithDeepChains.AddressModel)__o).City)
                    : (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.ReturnObservable<string>(default(string))));
            var __propObs0 = __propObs0_s1;


            var __propObs1 = new global::ReactiveUI.Binding.Observables.PropertyChangingObservable<string>(
                (global::System.ComponentModel.INotifyPropertyChanging)obj,
                "Name",
                (global::System.ComponentModel.INotifyPropertyChanging __o) => ((global::SharedScenarios.WhenChanging.MultiPropertyWithDeepChains.MyViewModel)__o).Name);

            return global::ReactiveUI.Binding.Observables.CombineLatestObservable.Create(
                __propObs0,
                __propObs1,
                selector);
        }

    }
}
