//HintName: WhenChangedDispatch.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        /// <summary>
        /// Concrete typed overload for WhenChanged on global::SharedScenarios.WhenChanged.MultiPropertyWithDeepChains.MyViewModel.
        /// </summary>
        public static global::System.IObservable<string> WhenChanged(
            this global::SharedScenarios.WhenChanged.MultiPropertyWithDeepChains.MyViewModel objectToMonitor,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.WhenChanged.MultiPropertyWithDeepChains.MyViewModel, string>> property1,
            global::System.Linq.Expressions.Expression<global::System.Func<global::SharedScenarios.WhenChanged.MultiPropertyWithDeepChains.MyViewModel, string>> property2,
            global::System.Func<string, string, string> selector,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property1")] string property1Expression = "",
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property2")] string property2Expression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
        {
            property1Expression = property1Expression.StartsWith("static ") ? property1Expression.Substring(7) : property1Expression;
            property2Expression = property2Expression.StartsWith("static ") ? property2Expression.Substring(7) : property2Expression;

            if (property1Expression == "x => x.Address.City" && property2Expression == "x => x.Name")
            {
                return __WhenChanged_7FFFD8A9CF83B95B(objectToMonitor, selector);
            }
            throw new global::System.InvalidOperationException("No generated WhenChanged dispatch matched. Ensure the expression is an inline lambda for compile-time optimization.");
        }

        private static global::System.IObservable<string> __WhenChanged_7FFFD8A9CF83B95B(global::SharedScenarios.WhenChanged.MultiPropertyWithDeepChains.MyViewModel obj, global::System.Func<string, string, string> selector)
        {
            var __propObs0_s0 = (global::System.IObservable<global::SharedScenarios.WhenChanged.MultiPropertyWithDeepChains.AddressModel?>)new global::ReactiveUI.Binding.Observables.PropertyObservable<global::SharedScenarios.WhenChanged.MultiPropertyWithDeepChains.AddressModel?>(
                obj,
                "Address",
                static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.WhenChanged.MultiPropertyWithDeepChains.MyViewModel)__o).Address,
                false);

        var __propObs0_s1 = global::ReactiveUI.Binding.Observables.RxBindingExtensions.Switch(
            global::ReactiveUI.Binding.Observables.RxBindingExtensions.Select(__propObs0_s0,
                __propObs0_p1 => __propObs0_p1 != null
                    ? (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
                        __propObs0_p1,
                        "City",
                        static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.WhenChanged.MultiPropertyWithDeepChains.AddressModel)__o).City,
                        false)
                    : (global::System.IObservable<string>)new global::ReactiveUI.Binding.Observables.ReturnObservable<string>(default(string))));
            var __propObs0 = global::ReactiveUI.Binding.Observables.RxBindingExtensions.DistinctUntilChanged(__propObs0_s1);


            var __propObs1 = new global::ReactiveUI.Binding.Observables.PropertyObservable<string>(
                obj,
                "Name",
                static (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::SharedScenarios.WhenChanged.MultiPropertyWithDeepChains.MyViewModel)__o).Name,
                true);

            return global::ReactiveUI.Binding.Observables.CombineLatestObservable.Create(
                __propObs0,
                __propObs1,
                selector);
        }

    }
}
