// Copyright (c) 2019-2026 ReactiveUI and Contributors. All rights reserved.
// ReactiveUI and Contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using ReactiveUI.Binding.SourceGenerators.CodeGeneration;
using ReactiveUI.Binding.SourceGenerators.Models;

namespace ReactiveUI.Binding.SourceGenerators.Tests.CodeGeneration;

/// <summary>
/// Covers the C# constructs the emitters build generated code from. Each one owns a piece of syntax and the
/// level change that goes with it, so these pin both the text and where the writer is left afterwards.
/// </summary>
public class SourceWriterExtensionsTests
{
    /// <summary>The level a namespace and one type leave the writer at.</summary>
    private const int MemberLevel = 2;

    /// <summary>The level a namespace and two nested types leave the writer at.</summary>
    private const int NestedMemberLevel = 3;

    /// <summary>A number appended into a statement built in parts.</summary>
    private const int Addend = 2;

    /// <summary>The file header writes only the markers and directive asked for.</summary>
    /// <param name="markers">Whether to write the generated-code markers.</param>
    /// <param name="nullable">Whether to write the nullable directive.</param>
    /// <param name="expected">The expected header.</param>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    [Arguments(true, true, "// <auto-generated/>\n#pragma warning disable\n#nullable enable\n")]
    [Arguments(true, false, "// <auto-generated/>\n#pragma warning disable\n")]
    [Arguments(false, true, "#nullable enable\n")]
    [Arguments(false, false, "")]
    public async Task FileHeader_WritesWhatWasAskedFor(bool markers, bool nullable, string expected)
    {
        var rendered = new SourceWriter().FileHeader(markers, nullable).ToString();

        await Assert.That(rendered).IsEqualTo(expected);
    }

    /// <summary>A namespace and a type each open a block, leaving the writer at their members' level.</summary>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task NamespaceAndType_OpenNestedBlocks()
    {
        var writer = new SourceWriter()
            .Using("System")
            .BlankLine()
            .OpenNamespace("My.App")
            .OpenType("internal static partial class C");

        var levelInside = writer.Level;
        var rendered = writer.Line("member;").CloseBlock().CloseBlock().ToString();

        await Assert.That(levelInside).IsEqualTo(MemberLevel);
        await Assert.That(rendered).IsEqualTo(
            "using System;\n\nnamespace My.App\n{\n    internal static partial class C\n    {\n        member;\n    }\n}\n");
    }

    /// <summary>Documentation comments are written at the writer's level, as one line or several.</summary>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task DocComments_WriteSummaryLines()
    {
        var rendered = new SourceWriter().Indent()
            .Summary("One line.")
            .OpenSummary()
            .DocLine("First.")
            .BeginDocLine().Append("Second ").Line("line.")
            .CloseSummary()
            .ToString();

        await Assert.That(rendered).IsEqualTo(
            "    /// <summary>One line.</summary>\n    /// <summary>\n    /// First.\n    /// Second line.\n    /// </summary>\n");
    }

    /// <summary>Line comments and attributes each take a line of their own.</summary>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task CommentsAndAttributes_TakeTheirOwnLine()
    {
        var rendered = new SourceWriter()
            .Comment("note")
            .BeginComment().Append("built ").Line("comment")
            .Attribute("Obsolete")
            .ToString();

        await Assert.That(rendered).IsEqualTo("// note\n// built comment\n[Obsolete]\n");
    }

    /// <summary>A parameter list puts one parameter per line, one level deeper, and closes back at the signature's level.</summary>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task ParameterList_OneParameterPerLine()
    {
        var writer = new SourceWriter().Indent().Append("void M").OpenParameterList()
            .Parameter("int a")
            .LastParameter("string b");

        var levelAfter = writer.Level;
        var rendered = writer.OpenBlock().CloseBlock().ToString();

        await Assert.That(levelAfter).IsEqualTo(1);
        await Assert.That(rendered).IsEqualTo("    void M(\n        int a,\n        string b)\n    {\n    }\n");
    }

    /// <summary>A chain of branches opens with <c>if</c>, continues with <c>else if</c>, and ends with <c>else</c>.</summary>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task Branches_WriteIfElseIfElse()
    {
        var writer = new SourceWriter();
        _ = writer.BeginBranch(0).Append("a").CloseCondition().Line("one();").CloseBlock();
        _ = writer.BeginBranch(1).Append("b").CloseCondition().Line("two();").CloseBlock();
        _ = writer.Else().Line("three();").CloseBlock();
        _ = writer.If("c").CloseBlock();
        _ = writer.BeginIf().Append("d").CloseCondition().CloseBlock();
        _ = writer.BeginElseIf().Append("e").CloseCondition().CloseBlock();

        await Assert.That(writer.ToString()).IsEqualTo(
            "if (a)\n{\n    one();\n}\nelse if (b)\n{\n    two();\n}\nelse\n{\n    three();\n}\n"
            + "if (c)\n{\n}\nif (d)\n{\n}\nelse if (e)\n{\n}\n");
    }

    /// <summary>Statements end their line: locals, returns, and a statement built in parts.</summary>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task Statements_EndTheirLine()
    {
        var rendered = new SourceWriter()
            .Var("x", "1")
            .BeginVar("y").Append("x + ").Append(Addend).EndStatement()
            .Return("y")
            .BeginReturn().Append("x").EndStatement()
            .ToString();

        await Assert.That(rendered).IsEqualTo("var x = 1;\nvar y = x + 2;\nreturn y;\nreturn x;\n");
    }

    /// <summary>A try and a finally each open a block of their own.</summary>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task TryFinally_OpenTheirBlocks()
    {
        var rendered = new SourceWriter()
            .Try().Line("work();").CloseBlock()
            .Finally().Line("cleanUp();").CloseBlock()
            .ToString();

        await Assert.That(rendered).IsEqualTo("try\n{\n    work();\n}\nfinally\n{\n    cleanUp();\n}\n");
    }

    /// <summary>A continuation ends the line and moves the rest of the expression one level deeper.</summary>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task OpenContinuation_IndentsTheRestOfTheExpression()
    {
        var rendered = new SourceWriter().Append("var z = a").OpenContinuation().Line("+ b;").Outdent().Line("next;").ToString();

        await Assert.That(rendered).IsEqualTo("var z = a\n    + b;\nnext;\n");
    }

    /// <summary>A partial declaration opens its namespace and every enclosing type, and closes all of them.</summary>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task PartialDeclaration_OpensAndClosesEveryEnclosingType()
    {
        var declaration = new PartialTypeDeclaration("My.App", new(["partial class Outer", "partial class Inner"]));
        var writer = new SourceWriter();

        CodeGeneratorHelpers.OpenPartialDeclaration(writer, declaration);
        var levelInside = writer.Level;
        _ = writer.Line("int X;");
        CodeGeneratorHelpers.ClosePartialDeclaration(writer, declaration);

        await Assert.That(levelInside).IsEqualTo(NestedMemberLevel);
        await Assert.That(writer.Level).IsEqualTo(0);
        await Assert.That(writer.ToString()).IsEqualTo(
            "namespace My.App\n{\n    partial class Outer\n    {\n        partial class Inner\n        {\n            int X;\n        }\n    }\n}\n");
    }

    /// <summary>A partial declaration in the global namespace opens only its types.</summary>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task PartialDeclaration_InTheGlobalNamespace_OpensOnlyTheType()
    {
        var declaration = new PartialTypeDeclaration(null, new(["partial class Only"]));
        var writer = new SourceWriter();

        CodeGeneratorHelpers.OpenPartialDeclaration(writer, declaration);
        CodeGeneratorHelpers.ClosePartialDeclaration(writer, declaration);

        await Assert.That(writer.ToString()).IsEqualTo("partial class Only\n{\n}\n");
    }

    /// <summary>A guarded assignment walks each parent once, drops the write while one is missing, and skips an unchanged value.</summary>
    /// <returns>A task representing the asynchronous test operation.</returns>
    [Test]
    public async Task GuardedAssignment_GuardsEachParentThenTheValue()
    {
        var path = new EquatableArray<PropertyPathSegment>(
        [
            new("Address", "global::A", "global::Owner", true, null),
            new("City", "string", "global::A", true, null),
        ]);
        var writer = new SourceWriter().Indent();

        CodeGeneratorHelpers.AppendGuardedAssignment(writer, "target", path, "value");

        await Assert.That(writer.ToString()).IsEqualTo(
            "    var __parent0 = target.Address;\n"
            + "    if (__parent0 == null)\n    {\n        return;\n    }\n\n"
            + "    if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(__parent0.City, value))\n"
            + "    {\n        return;\n    }\n\n"
            + "    __parent0.City = value;\n");
        await Assert.That(writer.Level).IsEqualTo(1);
    }
}
