// Copyright (c) 2019-2026 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

using ReactiveUI.Binding.SourceGenerators.Generators;
using ReactiveUI.Binding.SourceGenerators.Helpers;
using ReactiveUI.Binding.SourceGenerators.Invocations;
using ReactiveUI.Binding.SourceGenerators.Models;
using ReactiveUI.Binding.SourceGenerators.Plugins;

namespace ReactiveUI.Binding.SourceGenerators;

/// <summary>
/// The main incremental source generator entry point for ReactiveUI property observation and binding.
/// Orchestrates three pipelines:
/// Pipeline A (Type Detection): Detects notification mechanisms and generates high-affinity fallback binders.
/// Pipeline B (Invocation Detection): Detects WhenChanged/WhenChanging/Bind calls and generates per-invocation code.
/// Pipeline C (View Dispatch): Scans IViewFor&lt;T&gt; implementations and generates AOT-safe view locator dispatch.
/// </summary>
[Generator]
public class BindingGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Emit the [ExcludeFromCodeCoverage] attribute on the partial class once,
        // so individual dispatch files don't duplicate it.
        context.RegisterPostInitializationOutput(static ctx =>
        {
            const string source = """
                // <auto-generated/>
                #pragma warning disable

                namespace ReactiveUI.Binding
                {
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    internal static partial class __ReactiveUIGeneratedBindings
                    {
                    }
                }
                """;
            ctx.AddSource("GeneratedBindingsAttributes.g.cs", source);
        });

        // Detect whether the consumer project supports CallerArgumentExpression (C# 10+ AND attribute available).
        // When supported, invocation generators use expression-text dispatch; otherwise file/line dispatch.
        var supportsCallerArgExpr = context.ParseOptionsProvider
            .Combine(context.CompilationProvider)
            .Select(static (data, _) =>
                data.Left is CSharpParseOptions { LanguageVersion: >= LanguageVersion.CSharp10 } && data.Right.GetTypeByMetadataName(
                    Constants.CallerArgumentExpressionAttributeMetadataName) is not null);

        // Pipeline A: Shared type detection
        // One pass: sets flags for IRO, INPC, WpfDP, WinUIDP, KVO, etc.
        var allClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: RoslynHelpers.IsClassWithBaseList,
                transform: TypeDetectionExtractor.ExtractClassBindingInfo)
            .Where(static x => x is not null)
            .Select(static (x, _) => x!);

        // Single plugin-based step replaces 7 separate filter calls.
        // Each type is matched against the plugin registry; the highest-affinity
        // matching plugin determines the observation kind and capabilities.
        var allObservableTypes = allClasses
            .Select(static (classInfo, _) =>
            {
                var plugin = ObservationPluginRegistry.GetBestPlugin(classInfo);
                if (plugin is null)
                {
                    return null;
                }

                return new ObservableTypeInfo(
                    classInfo.FullyQualifiedName,
                    classInfo.MetadataName,
                    plugin.ObservationKind,
                    plugin.Affinity,
                    plugin.SupportsBeforeChanged,
                    classInfo.Properties);
            })
            .Where(static x => x is not null)
            .Select(static (x, _) => x!);

        // Consolidate all observable types → single RegisterSourceOutput
        var consolidated = allObservableTypes.Collect();

        context.RegisterSourceOutput(
            consolidated,
            static (ctx, data) => RegistrationGenerator.Generate(ctx, data));

        // Pipeline C: View locator dispatch (IViewFor<T> scanning)
        ViewLocatorDispatchGenerator.Register(context);

        // Pipeline B: Invocation detection (separate pipelines per API)
        // Each invocation generator receives supportsCallerArgExpr to control dispatch strategy
        WhenChangedInvocationGenerator.Register(context, allClasses, supportsCallerArgExpr);
        WhenChangingInvocationGenerator.Register(context, allClasses, supportsCallerArgExpr);
        BindOneWayInvocationGenerator.Register(context, allClasses, supportsCallerArgExpr);
        BindTwoWayInvocationGenerator.Register(context, allClasses, supportsCallerArgExpr);
        OneWayBindInvocationGenerator.Register(context, allClasses, supportsCallerArgExpr);
        BindInvocationGenerator.Register(context, allClasses, supportsCallerArgExpr);
        WhenAnyValueInvocationGenerator.Register(context, allClasses, supportsCallerArgExpr);
        WhenAnyInvocationGenerator.Register(context, allClasses, supportsCallerArgExpr);
        WhenAnyObservableInvocationGenerator.Register(context, allClasses, supportsCallerArgExpr);
        BindInteractionInvocationGenerator.Register(context, allClasses, supportsCallerArgExpr);
        BindCommandInvocationGenerator.Register(context, allClasses, supportsCallerArgExpr);
    }
}
