// Copyright (c) 2019-2026 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using ReactiveUI.Binding.SourceGenerators.Generators;
using ReactiveUI.Binding.SourceGenerators.Helpers;
using ReactiveUI.Binding.SourceGenerators.Invocations;
using ReactiveUI.Binding.SourceGenerators.Models;
using ReactiveUI.Binding.SourceGenerators.Plugins;

namespace ReactiveUI.Binding.SourceGenerators;

/// <summary>
/// The main incremental source generator entry point for ReactiveUI property observation and binding.
/// Orchestrates three pipelines:
/// Pipeline A (Type Detection): Detects notification mechanisms and generates high-affinity fallback binders.
/// Pipeline B (Invocation Detection): Detects WhenChanged/WhenChanging/Bind calls and generates per-invocation code.
/// Pipeline C (View Dispatch): Scans IViewFor&lt;T&gt; implementations and generates AOT-safe view locator dispatch.
/// </summary>
[Generator]
public class BindingGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Emit the [ExcludeFromCodeCoverage] attribute on the partial class once,
        // so individual dispatch files don't duplicate it.
        context.RegisterPostInitializationOutput(static ctx =>
        {
            // Post-initialization output runs before analyzer config options are available, so this trivial
            // (empty) partial class always carries the generated-file markers; an empty class produces no
            // diagnostics worth surfacing even when ReactiveUIBindingEmitGeneratedCodeMarkers is disabled.
            const string source = """
                                  // <auto-generated/>
                                  #pragma warning disable
                                  namespace ReactiveUI.Binding
                                  {
                                      [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                                      internal static partial class __ReactiveUIGeneratedBindings
                                      {
                                      }
                                  }
                                  """;
            ctx.AddSource("GeneratedBindingsAttributes.g.cs", source);
        });

        // Snapshot the consumer's relevant C# language capabilities once, flowed through every invocation
        // pipeline. CallerArgumentExpression (C# 10+ AND attribute available) selects expression-text dispatch
        // over file/line dispatch; nullable reference types (C# 8+) makes generated files emit '#nullable enable'.
        var languageFeatures = context.ParseOptionsProvider
            .Combine(context.CompilationProvider)
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select(static (data, _) =>
            {
                var parseOptions = data.Left.Left;
                var compilation = data.Left.Right;
                var configOptions = data.Right;

                var languageVersion = (parseOptions as CSharpParseOptions)?.LanguageVersion ?? LanguageVersion.Default;
                var supportsCallerArgExpr = languageVersion >= LanguageVersion.CSharp10 &&
                    compilation.GetTypeByMetadataName(
                        Constants.CallerArgumentExpressionAttributeMetadataName) is not null;

                // Generated-file markers (// <auto-generated/> + #pragma warning disable) are emitted by default
                // (the shipping convention); consumers opt out with ReactiveUIBindingEmitGeneratedCodeMarkers=false
                // to surface analyzer diagnostics in the generated code. Absent property => default (markers on).
                var emitGeneratedCodeMarkers = !(configOptions.GlobalOptions.TryGetValue(
                        "build_property.ReactiveUIBindingEmitGeneratedCodeMarkers",
                        out var markersValue)
                    && string.Equals(markersValue, "false", System.StringComparison.OrdinalIgnoreCase));

                return new LanguageFeatures(
                    supportsCallerArgExpr,
                    languageVersion >= LanguageVersion.CSharp8,
                    emitGeneratedCodeMarkers);
            });

        // Pipeline A: Shared type detection
        // One pass: sets flags for IRO, INPC, WpfDP, WinUIDP, KVO, etc.
        var allClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                RoslynHelpers.IsClassWithBaseList,
                TypeDetectionExtractor.ExtractClassBindingInfo)
            .Where(static x => x is not null)
            .Select(static (x, _) => x!);

        // Single plugin-based step replaces 7 separate filter calls.
        // Each type is matched against the plugin registry; the highest-affinity
        // matching plugin determines the observation kind and capabilities.
        var allObservableTypes = allClasses
            .Select(static (classInfo, _) =>
            {
                var plugin = ObservationPluginRegistry.GetBestPlugin(classInfo);
                if (plugin is null)
                {
                    return null;
                }

                return new ObservableTypeInfo(
                    classInfo.FullyQualifiedName,
                    classInfo.MetadataName,
                    plugin.ObservationKind,
                    plugin.Affinity,
                    plugin.SupportsBeforeChanged,
                    classInfo.Properties);
            })
            .Where(static x => x is not null)
            .Select(static (x, _) => x!);

        // Consolidate all observable types → single RegisterSourceOutput
        var consolidated = allObservableTypes.Collect();

        context.RegisterSourceOutput(
            consolidated.Combine(languageFeatures),
            static (ctx, data) => RegistrationGenerator.Generate(ctx, data.Left, data.Right));

        // Pipeline C: View locator dispatch (IViewFor<T> scanning)
        ViewLocatorDispatchGenerator.Register(context, languageFeatures);

        // Pipeline B: Invocation detection (separate pipelines per API)
        // Each invocation generator receives the language-feature snapshot to control dispatch/output
        WhenChangedInvocationGenerator.Register(context, allClasses, languageFeatures);
        WhenChangingInvocationGenerator.Register(context, allClasses, languageFeatures);
        BindOneWayInvocationGenerator.Register(context, allClasses, languageFeatures);
        BindTwoWayInvocationGenerator.Register(context, allClasses, languageFeatures);
        OneWayBindInvocationGenerator.Register(context, allClasses, languageFeatures);
        BindInvocationGenerator.Register(context, allClasses, languageFeatures);
        WhenAnyValueInvocationGenerator.Register(context, allClasses, languageFeatures);
        WhenAnyInvocationGenerator.Register(context, allClasses, languageFeatures);
        WhenAnyObservableInvocationGenerator.Register(context, allClasses, languageFeatures);
        BindInteractionInvocationGenerator.Register(context, allClasses, languageFeatures);
        BindCommandInvocationGenerator.Register(context, allClasses, languageFeatures);
        BindToInvocationGenerator.Register(context, allClasses, languageFeatures);
    }
}
