// Copyright (c) 2019-2026 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

namespace ReactiveUI.Binding.SourceGenerators;

/// <summary>
/// Constants shared between the source generator and analyzer projects.
/// Contains well-known metadata names for platform detection and API stub definitions.
/// </summary>
internal static class Constants
{
    // Well-known metadata names for platform detection (zero platform dependencies in generator)
    internal const string INotifyPropertyChangedMetadataName = "System.ComponentModel.INotifyPropertyChanged";
    internal const string INotifyPropertyChangingMetadataName = "System.ComponentModel.INotifyPropertyChanging";
    internal const string IReactiveObjectMetadataName = "ReactiveUI.IReactiveObject";
    internal const string WpfDependencyObjectMetadataName = "System.Windows.DependencyObject";
    internal const string WinUIDependencyObjectMetadataName = "Microsoft.UI.Xaml.DependencyObject";
    internal const string NSObjectMetadataName = "Foundation.NSObject";
    internal const string WinFormsComponentMetadataName = "System.ComponentModel.Component";
    internal const string AndroidViewMetadataName = "Android.Views.View";
    internal const string INotifyDataErrorInfoMetadataName = "System.ComponentModel.INotifyDataErrorInfo";

    // Class names
    internal const string StubExtensionClassName = "ReactiveUIBindingExtensions";
    internal const string SchedulerExtensionClassName = "ReactiveSchedulerExtensions";
    internal const string GeneratedExtensionClassName = "__ReactiveUIGeneratedBindings";
    internal const string GeneratedBinderRegistrationClassName = "__GeneratedBinderRegistration";

    // Method names to detect
    internal const string WhenChangedMethodName = "WhenChanged";
    internal const string WhenChangingMethodName = "WhenChanging";
    internal const string BindOneWayMethodName = "BindOneWay";
    internal const string BindTwoWayMethodName = "BindTwoWay";
    internal const string OneWayBindMethodName = "OneWayBind";
    internal const string BindMethodName = "Bind";
    internal const string WhenAnyValueMethodName = "WhenAnyValue";
    internal const string WhenAnyMethodName = "WhenAny";
    internal const string WhenAnyObservableMethodName = "WhenAnyObservable";

    // Converter type names
    internal const string IBindingTypeConverterMetadataName = "ReactiveUI.Binding.IBindingTypeConverter";

    // Attribute names
    internal const string CallerFilePathAttributeName = "System.Runtime.CompilerServices.CallerFilePathAttribute";
    internal const string CallerLineNumberAttributeName = "System.Runtime.CompilerServices.CallerLineNumberAttribute";
    internal const string CallerArgumentExpressionAttributeMetadataName = "System.Runtime.CompilerServices.CallerArgumentExpressionAttribute";

    /// <summary>
    /// Polyfill source for CallerArgumentExpressionAttribute when targeting runtimes that don't include it.
    /// Only emitted when C# 10+ is detected and the attribute is not already available.
    /// </summary>
    internal const string CallerArgumentExpressionAttributeSource = """
        // <auto-generated/>
        #pragma warning disable
        namespace System.Runtime.CompilerServices
        {
            [global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
            internal sealed class CallerArgumentExpressionAttribute : global::System.Attribute
            {
                public CallerArgumentExpressionAttribute(string parameterName)
                {
                    ParameterName = parameterName;
                }

                public string ParameterName { get; }
            }
        }
        """;
}
