// Copyright (c) 2019-2026 ReactiveUI and Contributors. All rights reserved.
// ReactiveUI and Contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using ReactiveUI.Binding.Documentation.UnsafeIndex;

UnsafeIndexExamples.BuildApplication();

UnsafeIndexExamples.ObserveTitleChosenAtRunTime();

UnsafeIndexExamples.ObserveTwoColumnsChosenAtRunTime();

UnsafeIndexExamples.ObserveTwoColumnsWithSelector();

UnsafeIndexExamples.ObserveThreeColumnsChosenAtRunTime();

UnsafeIndexExamples.ObserveThreeColumnsWithSelector();

UnsafeIndexExamples.ObserveTitleBeforeChange();

UnsafeIndexExamples.ObserveTwoColumnsBeforeChange();

UnsafeIndexExamples.ObserveTwoColumnsBeforeChangeWithSelector();

UnsafeIndexExamples.ObserveAnyValueChosenAtRunTime();

UnsafeIndexExamples.ObserveAnyValueWithSelector();

UnsafeIndexExamples.ObserveTwoAnyValuesChosenAtRunTime();

UnsafeIndexExamples.ObserveTwoAnyValuesWithSelector();

UnsafeIndexExamples.ObserveAnyChosenAtRunTime();

UnsafeIndexExamples.ObserveTwoAnyChosenAtRunTime();

UnsafeIndexExamples.ObserveAnnouncementStreamChosenAtRunTime();

UnsafeIndexExamples.MergeAnnouncementStreams();

UnsafeIndexExamples.CombineAnnouncementStreams();

UnsafeIndexExamples.BindOneWayBetweenPathsChosenAtRunTime();

UnsafeIndexExamples.BindOneWayWithConversionChosenAtRunTime();

UnsafeIndexExamples.BindTwoWayBetweenPathsChosenAtRunTime();

UnsafeIndexExamples.BindTwoWayWithConversionsChosenAtRunTime();

UnsafeIndexExamples.OneWayBindChosenAtRunTime();

UnsafeIndexExamples.OneWayBindWithSelectorChosenAtRunTime();

UnsafeIndexExamples.BindChosenAtRunTime();

UnsafeIndexExamples.BindWithConversionsChosenAtRunTime();

UnsafeIndexExamples.BindToTargetChosenAtRunTime();

UnsafeIndexExamples.BindToWithConverterOverride();

UnsafeIndexExamples.BindToWithHintAndConverterOverride();

UnsafeIndexExamples.BindToWithConversionHint();

await UnsafeIndexExamples.InvokeCommandChosenAtRunTime();

await UnsafeIndexExamples.BindCommandToButtonChosenAtRunTime();

await UnsafeIndexExamples.BindCommandWithParameterStream();

await UnsafeIndexExamples.BindCommandWithParameterProperty();

await UnsafeIndexExamples.BindInteractionWithTaskHandler();

await UnsafeIndexExamples.BindInteractionWithObservableHandler();

UnsafeSequencerExamples.BindOneWayOnSequencer();

UnsafeSequencerExamples.BindOneWayWithConversionOnSequencer();

UnsafeSequencerExamples.BindOneWayWithConverterOnSequencer();

UnsafeSequencerExamples.BindTwoWayOnSequencer();

UnsafeSequencerExamples.BindTwoWayWithConversionsOnSequencer();

UnsafeSequencerExamples.BindTwoWayWithConvertersOnSequencer();

UnsafeSequencerExamples.BindWithConversionsOnSequencer();

UnsafeSequencerExamples.BindWithConvertersOnSequencer();

UnsafeSequencerExamples.OneWayBindWithSelectorOnSequencer();

UnsafeSequencerExamples.OneWayBindWithConverterOnSequencer();

UnsafeWhenChangedWideExamples.ObserveFourColumns();

UnsafeWhenChangedWideExamples.ObserveFiveColumns();

UnsafeWhenChangedWideExamples.ObserveSixColumns();

UnsafeWhenChangedWideExamples.ObserveSevenColumns();

UnsafeWhenChangedWideExamples.ObserveEightColumns();

UnsafeWhenChangedWideExamples.ObserveNineColumns();

UnsafeWhenChangedWideExamples.ObserveTenColumns();

UnsafeWhenChangedWideExamples.ObserveElevenColumns();

UnsafeWhenChangedWideExamples.ObserveTwelveColumns();

UnsafeWhenChangedWideExamples.ObserveThirteenColumns();

UnsafeWhenChangedWideExamples.ObserveFourteenColumns();

UnsafeWhenChangedWideExamples.ObserveFifteenColumns();

UnsafeWhenChangedWideExamples.ObserveSixteenColumns();

UnsafeWhenAnyValueWideExamples.ObserveThreeColumns();

UnsafeWhenAnyValueWideExamples.ObserveFourColumns();

UnsafeWhenAnyValueWideExamples.ObserveFiveColumns();

UnsafeWhenAnyValueWideExamples.ObserveSixColumns();

UnsafeWhenAnyValueWideExamples.ObserveSevenColumns();

UnsafeWhenAnyValueWideExamples.ObserveEightColumns();

UnsafeWhenAnyValueWideExamples.ObserveNineColumns();

UnsafeWhenAnyValueWideExamples.ObserveTenColumns();

UnsafeWhenAnyValueWideExamples.ObserveElevenColumns();

UnsafeWhenAnyValueWideExamples.ObserveTwelveColumns();

UnsafeWhenAnyValueWideExamples.ObserveThirteenColumns();

UnsafeWhenAnyValueWideExamples.ObserveFourteenColumns();

UnsafeWhenAnyValueWideExamples.ObserveFifteenColumns();

UnsafeWhenAnyValueWideExamples.ObserveSixteenColumns();

UnsafeWhenChangingWideExamples.ObserveThreeColumnsBeforeChange();

UnsafeWhenChangingWideExamples.ObserveFourColumnsBeforeChange();

UnsafeWhenChangingWideExamples.ObserveFiveColumnsBeforeChange();

UnsafeWhenChangingWideExamples.ObserveSixColumnsBeforeChange();

UnsafeWhenChangingWideExamples.ObserveSevenColumnsBeforeChange();

UnsafeWhenChangingWideExamples.ObserveEightColumnsBeforeChange();

UnsafeWhenChangingWideExamples.ObserveNineColumnsBeforeChange();

UnsafeWhenChangingWideExamples.ObserveTenColumnsBeforeChange();

UnsafeWhenChangingWideExamples.ObserveElevenColumnsBeforeChange();

UnsafeWhenChangingWideExamples.ObserveTwelveColumnsBeforeChange();

UnsafeWhenChangingWideExamples.ObserveThirteenColumnsBeforeChange();

UnsafeWhenChangingWideExamples.ObserveFourteenColumnsBeforeChange();

UnsafeWhenChangingWideExamples.ObserveFifteenColumnsBeforeChange();

UnsafeWhenChangingWideExamples.ObserveSixteenColumnsBeforeChange();

UnsafeWhenChangedWideSelectorExamples.ObserveFourColumnsWithSelector();

UnsafeWhenChangedWideSelectorExamples.ObserveFiveColumnsWithSelector();

UnsafeWhenChangedWideSelectorExamples.ObserveSixColumnsWithSelector();

UnsafeWhenChangedWideSelectorExamples.ObserveSevenColumnsWithSelector();

UnsafeWhenChangedWideSelectorExamples.ObserveEightColumnsWithSelector();

UnsafeWhenChangedWideSelectorExamples.ObserveNineColumnsWithSelector();

UnsafeWhenChangedWideSelectorExamples.ObserveTenColumnsWithSelector();

UnsafeWhenChangedWideSelectorExamples.ObserveElevenColumnsWithSelector();

UnsafeWhenChangedWideSelectorExamples.ObserveTwelveColumnsWithSelector();

UnsafeWhenChangedWideSelectorExamples.ObserveThirteenColumnsWithSelector();

UnsafeWhenChangedWideSelectorExamples.ObserveFourteenColumnsWithSelector();

UnsafeWhenChangedWideSelectorExamples.ObserveFifteenColumnsWithSelector();

UnsafeWhenChangedWideSelectorExamples.ObserveSixteenColumnsWithSelector();

UnsafeWhenAnyValueWideSelectorExamples.ObserveThreeColumnsWithSelector();

UnsafeWhenAnyValueWideSelectorExamples.ObserveFourColumnsWithSelector();

UnsafeWhenAnyValueWideSelectorExamples.ObserveFiveColumnsWithSelector();

UnsafeWhenAnyValueWideSelectorExamples.ObserveSixColumnsWithSelector();

UnsafeWhenAnyValueWideSelectorExamples.ObserveSevenColumnsWithSelector();

UnsafeWhenAnyValueWideSelectorExamples.ObserveEightColumnsWithSelector();

UnsafeWhenAnyValueWideSelectorExamples.ObserveNineColumnsWithSelector();

UnsafeWhenAnyValueWideSelectorExamples.ObserveTenColumnsWithSelector();

UnsafeWhenAnyValueWideSelectorExamples.ObserveElevenColumnsWithSelector();

UnsafeWhenAnyValueWideSelectorExamples.ObserveTwelveColumnsWithSelector();

UnsafeWhenAnyValueWideSelectorExamples.ObserveThirteenColumnsWithSelector();

UnsafeWhenAnyValueWideSelectorExamples.ObserveFourteenColumnsWithSelector();

UnsafeWhenAnyValueWideSelectorExamples.ObserveFifteenColumnsWithSelector();

UnsafeWhenAnyValueWideSelectorExamples.ObserveSixteenColumnsWithSelector();

UnsafeWhenChangingWideSelectorExamples.ObserveThreeColumnsBeforeChangeWithSelector();

UnsafeWhenChangingWideSelectorExamples.ObserveFourColumnsBeforeChangeWithSelector();

UnsafeWhenChangingWideSelectorExamples.ObserveFiveColumnsBeforeChangeWithSelector();

UnsafeWhenChangingWideSelectorExamples.ObserveSixColumnsBeforeChangeWithSelector();

UnsafeWhenChangingWideSelectorExamples.ObserveSevenColumnsBeforeChangeWithSelector();

UnsafeWhenChangingWideSelectorExamples.ObserveEightColumnsBeforeChangeWithSelector();

UnsafeWhenChangingWideSelectorExamples.ObserveNineColumnsBeforeChangeWithSelector();

UnsafeWhenChangingWideSelectorExamples.ObserveTenColumnsBeforeChangeWithSelector();

UnsafeWhenChangingWideSelectorExamples.ObserveElevenColumnsBeforeChangeWithSelector();

UnsafeWhenChangingWideSelectorExamples.ObserveTwelveColumnsBeforeChangeWithSelector();

UnsafeWhenChangingWideSelectorExamples.ObserveThirteenColumnsBeforeChangeWithSelector();

UnsafeWhenChangingWideSelectorExamples.ObserveFourteenColumnsBeforeChangeWithSelector();

UnsafeWhenChangingWideSelectorExamples.ObserveFifteenColumnsBeforeChangeWithSelector();

UnsafeWhenChangingWideSelectorExamples.ObserveSixteenColumnsBeforeChangeWithSelector();

UnsafeWhenAnyWideExamples.ObserveThreeColumnsWithChanges();

UnsafeWhenAnyWideExamples.ObserveFourColumnsWithChanges();

UnsafeWhenAnyWideExamples.ObserveFiveColumnsWithChanges();

UnsafeWhenAnyWideExamples.ObserveSixColumnsWithChanges();

UnsafeWhenAnyWideExamples.ObserveSevenColumnsWithChanges();

UnsafeWhenAnyWideExamples.ObserveEightColumnsWithChanges();

UnsafeWhenAnyWideExamples.ObserveNineColumnsWithChanges();

UnsafeWhenAnyWideExamples.ObserveTenColumnsWithChanges();

UnsafeWhenAnyWideExamples.ObserveElevenColumnsWithChanges();

UnsafeWhenAnyWideExamples.ObserveTwelveColumnsWithChanges();

UnsafeWhenAnyObservableWideExamples.MergeThreeAnnouncementStreams();

UnsafeWhenAnyObservableWideExamples.CombineThreeAnnouncementStreams();

UnsafeWhenAnyObservableWideExamples.MergeFourAnnouncementStreams();

UnsafeWhenAnyObservableWideExamples.CombineFourAnnouncementStreams();

UnsafeWhenAnyObservableWideExamples.MergeFiveAnnouncementStreams();

UnsafeWhenAnyObservableWideExamples.CombineFiveAnnouncementStreams();

UnsafeWhenAnyObservableWideExamples.MergeSixAnnouncementStreams();

UnsafeWhenAnyObservableWideExamples.CombineSixAnnouncementStreams();

UnsafeWhenAnyObservableWideExamples.MergeSevenAnnouncementStreams();

UnsafeWhenAnyObservableWideExamples.CombineSevenAnnouncementStreams();

UnsafeWhenAnyObservableWideExamples.MergeEightAnnouncementStreams();

UnsafeWhenAnyObservableWideExamples.CombineEightAnnouncementStreams();

UnsafeWhenAnyObservableWideExamples.MergeNineAnnouncementStreams();

UnsafeWhenAnyObservableWideExamples.CombineNineAnnouncementStreams();

UnsafeWhenAnyObservableWideExamples.MergeTenAnnouncementStreams();

UnsafeWhenAnyObservableWideExamples.CombineTenAnnouncementStreams();

UnsafeWhenAnyObservableWideExamples.MergeElevenAnnouncementStreams();

UnsafeWhenAnyObservableWideExamples.CombineElevenAnnouncementStreams();

UnsafeWhenAnyObservableWideExamples.MergeTwelveAnnouncementStreams();

UnsafeWhenAnyObservableWideExamples.CombineTwelveAnnouncementStreams();
