// Copyright (c) 2019-2026 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Collections.Immutable;
using System.Text;

using Microsoft.CodeAnalysis;

using ReactiveUI.Binding.SourceGenerators.Models;

namespace ReactiveUI.Binding.SourceGenerators.Generators;

/// <summary>
/// Consolidates all per-kind fallback generator results into a single RegisterSourceOutput.
/// Generates all ICreatesObservableForProperty implementations and a registration class.
/// </summary>
internal static class RegistrationGenerator
{
    /// <summary>
    /// Consolidates all per-kind filtered type providers into a single pipeline.
    /// </summary>
    internal static IncrementalValueProvider<ImmutableArray<ObservableTypeInfo>> Consolidate(
        IncrementalValuesProvider<ObservableTypeInfo> reactiveObj,
        IncrementalValuesProvider<ObservableTypeInfo> inpc,
        IncrementalValuesProvider<ObservableTypeInfo> wpf,
        IncrementalValuesProvider<ObservableTypeInfo> winui,
        IncrementalValuesProvider<ObservableTypeInfo> kvo,
        IncrementalValuesProvider<ObservableTypeInfo> winforms,
        IncrementalValuesProvider<ObservableTypeInfo> android)
    {
        // Collect all providers and combine into a single flattened array
        return reactiveObj.Collect()
            .Combine(inpc.Collect())
            .Combine(wpf.Collect())
            .Combine(winui.Collect())
            .Combine(kvo.Collect())
            .Combine(winforms.Collect())
            .Combine(android.Collect())
            .Select(static (x, _) =>
            {
                var builder = ImmutableArray.CreateBuilder<ObservableTypeInfo>();

                // Flatten the nested tuples
                var (((((reactiveObjTypes, inpcTypes), wpfTypes), winuiTypes), kvoTypes), winformsTypes) = x.Left;
                var androidTypes = x.Right;

                builder.AddRange(reactiveObjTypes);
                builder.AddRange(inpcTypes);
                builder.AddRange(wpfTypes);
                builder.AddRange(winuiTypes);
                builder.AddRange(kvoTypes);
                builder.AddRange(winformsTypes);
                builder.AddRange(androidTypes);

                return builder.ToImmutable();
            });
    }

    /// <summary>
    /// Generates the consolidated registration output: all per-kind binder classes.
    /// </summary>
    /// <param name="context">The source production context.</param>
    /// <param name="allTypes">All detected observable type infos across all notification kinds.</param>
    internal static void Generate(SourceProductionContext context, ImmutableArray<ObservableTypeInfo> allTypes)
    {
        if (allTypes.IsDefaultOrEmpty)
        {
            return;
        }

        // Collect unique observation kinds that were detected
        var uniqueKinds = new System.Collections.Generic.HashSet<string>();
        for (int i = 0; i < allTypes.Length; i++)
        {
            uniqueKinds.Add(allTypes[i].ObservationKind);
        }

        var sb = new StringBuilder(1024 + (allTypes.Length * 128));
        sb.AppendLine("""
            // <auto-generated/>
            #pragma warning disable
            #nullable enable

            namespace ReactiveUI.Binding.Generated
            {
                /// <summary>
                /// Auto-generated binder registration. Registers high-affinity
                /// ICreatesObservableForProperty implementations detected at compile time.
                /// </summary>
                internal static class __GeneratedBinderRegistration
                {
                    /// <summary>
                    /// Registers all generated binders with the Splat service locator.
                    /// </summary>
                    internal static void Initialize()
                    {
                        // Generated binder registrations will be added here in future phases.
                        // Each per-kind binder provides high-affinity observation for detected types.
            """);

        foreach (var kind in uniqueKinds)
        {
            sb.AppendLine($"            // Detected types for kind: {kind}");
        }

        sb.AppendLine("""
                    }
                }
            }
            """);

        context.AddSource("GeneratedBinderRegistration.g.cs", sb.ToString());
    }
}
