// Copyright (c) 2019-2026 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Collections.Immutable;
using System.Text;

using Microsoft.CodeAnalysis;

using ReactiveUI.Binding.SourceGenerators.Helpers;
using ReactiveUI.Binding.SourceGenerators.Models;

namespace ReactiveUI.Binding.SourceGenerators.Generators;

/// <summary>
/// Generates the AOT-safe view dispatch code for <see cref="ViewRegistrationInfo"/> entries.
/// Emits a type-switch function that resolves views without reflection.
/// </summary>
internal static class ViewLocatorDispatchGenerator
{
    /// <summary>
    /// Registers the view locator dispatch pipeline into the incremental generator.
    /// Scans for classes implementing <c>IViewFor&lt;T&gt;</c> and generates a dispatch method.
    /// </summary>
    /// <param name="context">The incremental generator initialization context.</param>
    internal static void Register(IncrementalGeneratorInitializationContext context)
    {
        // Reuse Pipeline A's class-with-base-list predicate
        var viewRegistrations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: RoslynHelpers.IsClassWithBaseList,
                transform: ViewRegistrationExtractor.ExtractFromIViewForImplementation)
            .Where(static x => x is not null)
            .Select(static (x, _) => x!);

        // Collect and deduplicate
        var collected = viewRegistrations.Collect();

        context.RegisterSourceOutput(collected, static (ctx, data) => Generate(ctx, data));
    }

    /// <summary>
    /// Generates the ViewDispatch.g.cs source file from collected view registrations.
    /// </summary>
    /// <param name="context">The source production context.</param>
    /// <param name="registrations">All detected view registration infos.</param>
    internal static void Generate(SourceProductionContext context, ImmutableArray<ViewRegistrationInfo> registrations)
    {
        if (!ExtractorValidation.HasItems(registrations))
        {
            return;
        }

        // Deduplicate by ViewModel fully qualified name (first occurrence wins)
        var deduplicated = Deduplicate(registrations);

        var sb = new StringBuilder(2048 + (deduplicated.Count * 512));
        GenerateSource(sb, deduplicated);
        context.AddSource("ViewDispatch.g.cs", sb.ToString());
    }

    /// <summary>
    /// Deduplicates view registrations by view model fully qualified name.
    /// </summary>
    /// <param name="registrations">The raw registrations.</param>
    /// <returns>A deduplicated list of registrations.</returns>
    private static List<ViewRegistrationInfo> Deduplicate(ImmutableArray<ViewRegistrationInfo> registrations)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var result = new List<ViewRegistrationInfo>(registrations.Length);

        for (var i = 0; i < registrations.Length; i++)
        {
            var reg = registrations[i];
            if (seen.Add(reg.ViewModelFullyQualifiedName))
            {
                result.Add(reg);
            }
        }

        return result;
    }

    /// <summary>
    /// Generates the full source output into the StringBuilder.
    /// </summary>
    /// <param name="sb">The string builder to write to.</param>
    /// <param name="registrations">The deduplicated registrations.</param>
    private static void GenerateSource(StringBuilder sb, List<ViewRegistrationInfo> registrations)
    {
        sb.AppendLine("// <auto-generated/>")
            .AppendLine("#pragma warning disable")
            .AppendLine()
            .AppendLine("namespace ReactiveUI.Binding")
            .AppendLine("{")
            .AppendLine("    internal static partial class __ReactiveUIGeneratedBindings")
            .AppendLine("    {");

        // Static field initializer to trigger registration
        sb.AppendLine("        /// <summary>")
            .AppendLine("        /// Triggers view dispatch registration when the generated bindings class is loaded.")
            .AppendLine("        /// </summary>")
            .AppendLine("        private static readonly bool __viewDispatchRegistered = __RegisterViewDispatch();")
            .AppendLine();

        // Registration method
        sb.AppendLine("        /// <summary>")
            .AppendLine("        /// Registers the source-generated view dispatch function with")
            .AppendLine("        /// <see cref=\"global::ReactiveUI.Binding.DefaultViewLocator\"/>.")
            .AppendLine("        /// Called once via static field initializer when this class is first accessed.")
            .AppendLine("        /// </summary>")
            .AppendLine("        /// <returns>Always returns <see langword=\"true\"/>.</returns>")
            .AppendLine("        private static bool __RegisterViewDispatch()")
            .AppendLine("        {")
            .AppendLine("            global::ReactiveUI.Binding.DefaultViewLocator.SetGeneratedViewDispatch(")
            .AppendLine("                __TryResolveView);")
            .AppendLine("            return true;")
            .AppendLine("        }")
            .AppendLine();

        // Dispatch method
        sb.AppendLine("        /// <summary>")
            .AppendLine("        /// Compile-time generated type-switch dispatch for view resolution.")
            .AppendLine("        /// Attempts to resolve a view for the given view model instance without reflection.")
            .AppendLine("        /// </summary>")
            .AppendLine("        /// <param name=\"instance\">The view model instance to resolve a view for.</param>")
            .AppendLine("        /// <param name=\"contract\">The contract string (empty string for default).</param>")
            .AppendLine("        /// <returns>The resolved view, or <see langword=\"null\"/> if no generated mapping exists.</returns>")
            .AppendLine("        private static global::ReactiveUI.Binding.IViewFor __TryResolveView(")
            .AppendLine("            object instance, string contract)")
            .AppendLine("        {");

        for (var i = 0; i < registrations.Count; i++)
        {
            var reg = registrations[i];
            var resolverMethodName = "__ResolveView_" + i;

            sb.Append("            // ").Append(reg.ViewModelFullyQualifiedName)
                .Append(" -> ").AppendLine(reg.ViewFullyQualifiedName)
                .Append("            if (instance is ").Append(reg.ViewModelFullyQualifiedName).AppendLine(")")
                .AppendLine("            {")
                .Append("                return ").Append(resolverMethodName).AppendLine("(contract);")
                .AppendLine("            }")
                .AppendLine();
        }

        sb.AppendLine("            // No compile-time mapping found; fall back to runtime resolution.")
            .AppendLine("            return null;")
            .AppendLine("        }");

        // Per-view resolver methods
        for (var i = 0; i < registrations.Count; i++)
        {
            GenerateResolverMethod(sb, registrations[i], i);
        }

        sb.AppendLine("    }")
            .AppendLine("}");
    }

    /// <summary>
    /// Generates a per-view-model resolver method.
    /// </summary>
    /// <param name="sb">The string builder.</param>
    /// <param name="reg">The view registration info.</param>
    /// <param name="index">The unique index for method naming.</param>
    private static void GenerateResolverMethod(StringBuilder sb, ViewRegistrationInfo reg, int index)
    {
        var methodName = "__ResolveView_" + index;

        sb.AppendLine()
            .AppendLine("        /// <summary>")
            .Append("        /// Resolves a view for <see cref=\"")
            .Append(reg.ViewModelFullyQualifiedName).AppendLine("\"/>.");

        if (reg.HasParameterlessConstructor)
        {
            sb.AppendLine("        /// Tries the service locator first, then falls back to direct construction.");
        }
        else
        {
            sb.AppendLine("        /// Service locator only — no direct construction available.");
        }

        sb.AppendLine("        /// </summary>")
            .AppendLine("        /// <param name=\"contract\">The contract string (empty string for default).</param>")
            .AppendLine("        /// <returns>The resolved view, or <see langword=\"null\"/> if resolution fails.</returns>")
            .Append("        private static global::ReactiveUI.Binding.IViewFor ")
            .Append(methodName).AppendLine("(string contract)")
            .AppendLine("        {");

        // Normalize contract
        sb.AppendLine("            // Normalize contract: empty string means no contract (null for Splat lookup).")
            .AppendLine("            string svcContract = contract.Length == 0 ? null : contract;")
            .AppendLine();

        // Service locator lookup
        sb.AppendLine("            // Prefer service-locator-registered view (supports DI-configured instances).")
            .AppendLine("            var view = global::Splat.AppLocator.Current")
            .Append("                .GetService<global::ReactiveUI.Binding.IViewFor<")
            .Append(reg.ViewModelFullyQualifiedName).AppendLine(">>(")
            .AppendLine("                    svcContract);")
            .AppendLine("            if (view != null)")
            .AppendLine("            {")
            .AppendLine("                return view;")
            .AppendLine("            }");

        // Direct construction fallback
        if (reg.HasParameterlessConstructor)
        {
            sb.AppendLine()
                .Append("            // Fallback: direct construction (")
                .Append(reg.ViewFullyQualifiedName).AppendLine(" has a parameterless constructor).")
                .Append("            return new ").Append(reg.ViewFullyQualifiedName).AppendLine("();");
        }
        else
        {
            sb.AppendLine()
                .AppendLine("            return null;");
        }

        sb.AppendLine("        }");
    }
}
