// Copyright (c) 2019-2026 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Collections.Immutable;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

using ReactiveUI.Binding.SourceGenerators.Helpers;
using ReactiveUI.Binding.SourceGenerators.Models;

namespace ReactiveUI.Binding.SourceGenerators.Generators;

/// <summary>
/// Generates the AOT-safe view dispatch code for <see cref="ViewRegistrationInfo"/> entries.
/// Emits a type-switch function that resolves views without reflection.
/// </summary>
internal static class ViewLocatorDispatchGenerator
{
    /// <summary>
    /// Registers the view locator dispatch pipeline into the incremental generator.
    /// Scans for classes implementing <c>IViewFor&lt;T&gt;</c> and generates a dispatch method.
    /// </summary>
    /// <param name="context">The incremental generator initialization context.</param>
    internal static void Register(IncrementalGeneratorInitializationContext context)
    {
        // Reuse Pipeline A's class-with-base-list predicate
        var viewRegistrations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: RoslynHelpers.IsClassWithBaseList,
                transform: ViewRegistrationExtractor.ExtractFromIViewForImplementation)
            .Where(static x => x is not null)
            .Select(static (x, _) => x!);

        // Collect and deduplicate
        var collected = viewRegistrations.Collect();

        context.RegisterSourceOutput(collected, static (ctx, data) => Generate(ctx, data));
    }

    /// <summary>
    /// Generates the ViewDispatch.g.cs source file from collected view registrations.
    /// </summary>
    /// <param name="context">The source production context.</param>
    /// <param name="registrations">All detected view registration infos.</param>
    internal static void Generate(SourceProductionContext context, ImmutableArray<ViewRegistrationInfo> registrations)
    {
        if (!ExtractorValidation.HasItems(registrations))
        {
            return;
        }

        // Deduplicate by (ViewModel FQN, Contract) pair — first occurrence wins
        var deduplicated = Deduplicate(registrations);

        var sb = new StringBuilder(2048 + (deduplicated.Count * 512));
        GenerateSource(sb, deduplicated);
        context.AddSource("ViewDispatch.g.cs", sb.ToString());
    }

    /// <summary>
    /// Deduplicates view registrations by (view model fully qualified name, contract) pair.
    /// </summary>
    /// <param name="registrations">The raw registrations.</param>
    /// <returns>A deduplicated list of registrations.</returns>
    private static List<ViewRegistrationInfo> Deduplicate(ImmutableArray<ViewRegistrationInfo> registrations)
    {
        var seen = new HashSet<(string, string?)>(EqualityComparer<(string, string?)>.Default);
        var result = new List<ViewRegistrationInfo>(registrations.Length);

        for (var i = 0; i < registrations.Length; i++)
        {
            var reg = registrations[i];
            if (seen.Add((reg.ViewModelFullyQualifiedName, reg.Contract)))
            {
                result.Add(reg);
            }
        }

        return result;
    }

    /// <summary>
    /// Generates the full source output into the StringBuilder.
    /// </summary>
    /// <param name="sb">The string builder to write to.</param>
    /// <param name="registrations">The deduplicated registrations.</param>
    private static void GenerateSource(StringBuilder sb, List<ViewRegistrationInfo> registrations)
    {
        sb.Append("""
                  // <auto-generated/>
                  #pragma warning disable

                  namespace ReactiveUI.Binding
                  {
                      internal static partial class __ReactiveUIGeneratedBindings
                      {
                  """);

        // Singleton cache fields for [SingleInstanceView] views
        for (var i = 0; i < registrations.Count; i++)
        {
            var reg = registrations[i];
            if (reg.IsSingleInstance && reg.HasParameterlessConstructor)
            {
                sb.AppendLine().Append($$"""
                              /// <summary>
                              /// Cached singleton instance for <see cref="{{reg.ViewFullyQualifiedName}}"/> (marked with [SingleInstanceView]).
                              /// </summary>
                              private static {{reg.ViewFullyQualifiedName}} __singletonView_{{i}};
                  """);
            }
        }

        // Static field initializer to trigger registration
        sb.AppendLine().Append("""
                              /// <summary>
                              /// Triggers view dispatch registration when the generated bindings class is loaded.
                              /// </summary>
                              private static readonly bool __viewDispatchRegistered = __RegisterViewDispatch();

                              /// <summary>
                              /// Registers the source-generated view dispatch function with
                              /// <see cref="global::ReactiveUI.Binding.DefaultViewLocator"/>.
                              /// Called once via static field initializer when this class is first accessed.
                              /// </summary>
                              /// <returns>Always returns <see langword="true"/>.</returns>
                              private static bool __RegisterViewDispatch()
                              {
                                  global::ReactiveUI.Binding.DefaultViewLocator.SetGeneratedViewDispatch(
                                      __TryResolveView);
                                  return true;
                              }

                              /// <summary>
                              /// Compile-time generated type-switch dispatch for view resolution.
                              /// Attempts to resolve a view for the given view model instance without reflection.
                              /// </summary>
                              /// <param name="instance">The view model instance to resolve a view for.</param>
                              /// <param name="contract">The contract string (empty string for default).</param>
                              /// <returns>The resolved view, or <see langword="null"/> if no generated mapping exists.</returns>
                              private static global::ReactiveUI.Binding.IViewFor __TryResolveView(
                                  object instance, string contract)
                              {
                  """);

        // Group registrations by ViewModel FQN so contract-specific checks
        // are emitted before the default (no-contract) branch within a single
        // type-switch block. Without grouping, a default branch emitted first
        // would unconditionally match and shadow contract-specific branches.
        var vmOrder = new List<string>(registrations.Count);
        var vmGroupIndices = new Dictionary<string, List<int>>(registrations.Count);
        for (var i = 0; i < registrations.Count; i++)
        {
            var vmFqn = registrations[i].ViewModelFullyQualifiedName;
            if (!vmGroupIndices.TryGetValue(vmFqn, out var indices))
            {
                indices = new List<int>();
                vmGroupIndices[vmFqn] = indices;
                vmOrder.Add(vmFqn);
            }

            indices.Add(i);
        }

        for (var g = 0; g < vmOrder.Count; g++)
        {
            var vmFqn = vmOrder[g];
            var indices = vmGroupIndices[vmFqn];

            sb.AppendLine();

            if (indices.Count == 1)
            {
                // Single registration per VM: emit the compact form.
                EmitSingleRegistrationDispatch(sb, registrations, indices[0]);
            }
            else
            {
                // Multiple registrations for same VM: group into single type-switch.
                EmitGroupedDispatch(sb, registrations, vmFqn, indices);
            }
        }

        sb.AppendLine().Append("""

                                  // No compile-time mapping found; fall back to runtime resolution.
                                  return null;
                              }
                  """);

        // Per-view resolver methods
        for (var i = 0; i < registrations.Count; i++)
        {
            GenerateResolverMethod(sb, registrations[i], i);
        }

        sb.AppendLine().Append("""
                      }
                  }
                  """);
    }

    /// <summary>
    /// Emits a dispatch branch for a single registration (one view per VM type).
    /// Preserves the compact output format used by existing tests.
    /// </summary>
    /// <param name="sb">The string builder.</param>
    /// <param name="registrations">All registrations.</param>
    /// <param name="index">The registration index.</param>
    private static void EmitSingleRegistrationDispatch(StringBuilder sb, List<ViewRegistrationInfo> registrations, int index)
    {
        var reg = registrations[index];
        var resolverMethodName = "__ResolveView_" + index;

        if (reg.Contract is not null)
        {
            var escapedLiteral = SymbolDisplay.FormatLiteral(reg.Contract, true);
            sb.Append($$"""
                                    // {{reg.ViewModelFullyQualifiedName}} -> {{reg.ViewFullyQualifiedName}} [contract: {{escapedLiteral}}]
                                    if (instance is {{reg.ViewModelFullyQualifiedName}})
                                    {
                                        if (contract == {{escapedLiteral}})
                                        {
                                            return {{resolverMethodName}}(contract);
                                        }
                                    }
                        """);
        }
        else
        {
            sb.Append($$"""
                                    // {{reg.ViewModelFullyQualifiedName}} -> {{reg.ViewFullyQualifiedName}}
                                    if (instance is {{reg.ViewModelFullyQualifiedName}})
                                    {
                                        return {{resolverMethodName}}(contract);
                                    }
                        """);
        }
    }

    /// <summary>
    /// Emits a grouped dispatch branch for a VM type with multiple registrations.
    /// Contract-specific checks are emitted first, with the default (no-contract) branch last.
    /// </summary>
    /// <param name="sb">The string builder.</param>
    /// <param name="registrations">All registrations.</param>
    /// <param name="vmFqn">The fully qualified VM type name.</param>
    /// <param name="indices">The registration indices for this VM type.</param>
    private static void EmitGroupedDispatch(StringBuilder sb, List<ViewRegistrationInfo> registrations, string vmFqn, List<int> indices)
    {
        sb.Append($$"""
                                    // {{vmFqn}} — multiple views
                                    if (instance is {{vmFqn}})
                                    {
                        """);

        // Contract-specific branches first
        for (var j = 0; j < indices.Count; j++)
        {
            var idx = indices[j];
            var reg = registrations[idx];
            if (reg.Contract is not null)
            {
                var escapedLiteral = SymbolDisplay.FormatLiteral(reg.Contract, true);
                var resolverMethodName = "__ResolveView_" + idx;
                sb.AppendLine().Append($$"""
                                        // -> {{reg.ViewFullyQualifiedName}} [contract: {{escapedLiteral}}]
                                        if (contract == {{escapedLiteral}})
                                        {
                                            return {{resolverMethodName}}(contract);
                                        }
                            """);
            }
        }

        // Default (no-contract) branch last
        for (var j = 0; j < indices.Count; j++)
        {
            var idx = indices[j];
            var reg = registrations[idx];
            if (reg.Contract is null)
            {
                var resolverMethodName = "__ResolveView_" + idx;
                sb.AppendLine().Append($$"""
                                        // -> {{reg.ViewFullyQualifiedName}} (default)
                                        return {{resolverMethodName}}(contract);
                            """);
                break; // Only one default per VM (deduplicated earlier)
            }
        }

        sb.AppendLine().Append("""
                                    }
                        """);
    }

    /// <summary>
    /// Generates a per-view-model resolver method.
    /// </summary>
    /// <param name="sb">The string builder.</param>
    /// <param name="reg">The view registration info.</param>
    /// <param name="index">The unique index for method naming.</param>
    private static void GenerateResolverMethod(StringBuilder sb, ViewRegistrationInfo reg, int index)
    {
        var methodName = "__ResolveView_" + index;

        var strategyDoc = (reg.IsSingleInstance, reg.HasParameterlessConstructor) switch
        {
            (true, true) => "        /// Returns a cached singleton instance (marked with [SingleInstanceView]).",
            (true, false) => "        /// Service locator only — [SingleInstanceView] without parameterless constructor.",
            (false, true) => "        /// Tries the service locator first, then falls back to direct construction.",
            (false, false) => "        /// Service locator only — no direct construction available.",
        };

        sb.AppendLine().Append($$"""

                              /// <summary>
                              /// Resolves a view for <see cref="{{reg.ViewModelFullyQualifiedName}}"/>.
                  {{strategyDoc}}
                              /// </summary>
                              /// <param name="contract">The contract string (empty string for default).</param>
                              /// <returns>The resolved view, or <see langword="null"/> if resolution fails.</returns>
                              private static global::ReactiveUI.Binding.IViewFor {{methodName}}(string contract)
                              {
                                  // Normalize contract: empty string means no contract (null for Splat lookup).
                                  string svcContract = contract.Length == 0 ? null : contract;

                                  // Prefer service-locator-registered view (supports DI-configured instances).
                                  var view = global::Splat.AppLocator.Current
                                      .GetService<global::ReactiveUI.Binding.IViewFor<{{reg.ViewModelFullyQualifiedName}}>>(
                                          svcContract);
                                  if (view != null)
                                  {
                                      return view;
                                  }
                  """);

        if (reg.HasParameterlessConstructor)
        {
            if (reg.IsSingleInstance)
            {
                var fieldName = "__singletonView_" + index;
                sb.Append($$"""

                                      // Fallback: singleton construction ({{reg.ViewFullyQualifiedName}} has [SingleInstanceView]).
                                      if ({{fieldName}} == null)
                                      {
                                          System.Threading.Interlocked.CompareExchange(
                                              ref {{fieldName}},
                                              new {{reg.ViewFullyQualifiedName}}(),
                                              null);
                                      }

                                      return {{fieldName}};
                  """);
            }
            else
            {
                sb.Append($$"""

                                      // Fallback: direct construction ({{reg.ViewFullyQualifiedName}} has a parameterless constructor).
                                      return new {{reg.ViewFullyQualifiedName}}();
                  """);
            }
        }
        else
        {
            sb.Append("""

                                  return null;
                  """);
        }

        sb.AppendLine().Append("""
                              }
                  """);
    }
}
