// Copyright (c) 2019-2026 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Collections.Immutable;
using System.Text;

using Microsoft.CodeAnalysis;

using ReactiveUI.Binding.SourceGenerators.Helpers;
using ReactiveUI.Binding.SourceGenerators.Models;

namespace ReactiveUI.Binding.SourceGenerators.Generators;

/// <summary>
/// Generates the AOT-safe view dispatch code for <see cref="ViewRegistrationInfo"/> entries.
/// Emits a type-switch function that resolves views without reflection.
/// </summary>
internal static class ViewLocatorDispatchGenerator
{
    /// <summary>
    /// Registers the view locator dispatch pipeline into the incremental generator.
    /// Scans for classes implementing <c>IViewFor&lt;T&gt;</c> and generates a dispatch method.
    /// </summary>
    /// <param name="context">The incremental generator initialization context.</param>
    internal static void Register(IncrementalGeneratorInitializationContext context)
    {
        // Reuse Pipeline A's class-with-base-list predicate
        var viewRegistrations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: RoslynHelpers.IsClassWithBaseList,
                transform: ViewRegistrationExtractor.ExtractFromIViewForImplementation)
            .Where(static x => x is not null)
            .Select(static (x, _) => x!);

        // Collect and deduplicate
        var collected = viewRegistrations.Collect();

        context.RegisterSourceOutput(collected, static (ctx, data) => Generate(ctx, data));
    }

    /// <summary>
    /// Generates the ViewDispatch.g.cs source file from collected view registrations.
    /// </summary>
    /// <param name="context">The source production context.</param>
    /// <param name="registrations">All detected view registration infos.</param>
    internal static void Generate(SourceProductionContext context, ImmutableArray<ViewRegistrationInfo> registrations)
    {
        if (!ExtractorValidation.HasItems(registrations))
        {
            return;
        }

        // Deduplicate by (ViewModel FQN, Contract) pair — first occurrence wins
        var deduplicated = Deduplicate(registrations);

        var sb = new StringBuilder(2048 + (deduplicated.Count * 512));
        GenerateSource(sb, deduplicated);
        context.AddSource("ViewDispatch.g.cs", sb.ToString());
    }

    /// <summary>
    /// Deduplicates view registrations by (view model fully qualified name, contract) pair.
    /// </summary>
    /// <param name="registrations">The raw registrations.</param>
    /// <returns>A deduplicated list of registrations.</returns>
    private static List<ViewRegistrationInfo> Deduplicate(ImmutableArray<ViewRegistrationInfo> registrations)
    {
        var seen = new HashSet<(string, string?)>(EqualityComparer<(string, string?)>.Default);
        var result = new List<ViewRegistrationInfo>(registrations.Length);

        for (var i = 0; i < registrations.Length; i++)
        {
            var reg = registrations[i];
            if (seen.Add((reg.ViewModelFullyQualifiedName, reg.Contract)))
            {
                result.Add(reg);
            }
        }

        return result;
    }

    /// <summary>
    /// Generates the full source output into the StringBuilder.
    /// </summary>
    /// <param name="sb">The string builder to write to.</param>
    /// <param name="registrations">The deduplicated registrations.</param>
    private static void GenerateSource(StringBuilder sb, List<ViewRegistrationInfo> registrations)
    {
        sb.Append("""
                  // <auto-generated/>
                  #pragma warning disable

                  namespace ReactiveUI.Binding
                  {
                      internal static partial class __ReactiveUIGeneratedBindings
                      {
                  """);

        // Singleton cache fields for [SingleInstanceView] views
        for (var i = 0; i < registrations.Count; i++)
        {
            var reg = registrations[i];
            if (reg.IsSingleInstance && reg.HasParameterlessConstructor)
            {
                sb.AppendLine().Append($$"""
                              /// <summary>
                              /// Cached singleton instance for <see cref="{{reg.ViewFullyQualifiedName}}"/> (marked with [SingleInstanceView]).
                              /// </summary>
                              private static {{reg.ViewFullyQualifiedName}} __singletonView_{{i}};
                  """);
            }
        }

        // Static field initializer to trigger registration
        sb.AppendLine().Append("""
                              /// <summary>
                              /// Triggers view dispatch registration when the generated bindings class is loaded.
                              /// </summary>
                              private static readonly bool __viewDispatchRegistered = __RegisterViewDispatch();

                              /// <summary>
                              /// Registers the source-generated view dispatch function with
                              /// <see cref="global::ReactiveUI.Binding.DefaultViewLocator"/>.
                              /// Called once via static field initializer when this class is first accessed.
                              /// </summary>
                              /// <returns>Always returns <see langword="true"/>.</returns>
                              private static bool __RegisterViewDispatch()
                              {
                                  global::ReactiveUI.Binding.DefaultViewLocator.SetGeneratedViewDispatch(
                                      __TryResolveView);
                                  return true;
                              }

                              /// <summary>
                              /// Compile-time generated type-switch dispatch for view resolution.
                              /// Attempts to resolve a view for the given view model instance without reflection.
                              /// </summary>
                              /// <param name="instance">The view model instance to resolve a view for.</param>
                              /// <param name="contract">The contract string (empty string for default).</param>
                              /// <returns>The resolved view, or <see langword="null"/> if no generated mapping exists.</returns>
                              private static global::ReactiveUI.Binding.IViewFor __TryResolveView(
                                  object instance, string contract)
                              {
                  """);

        for (var i = 0; i < registrations.Count; i++)
        {
            var reg = registrations[i];
            var resolverMethodName = "__ResolveView_" + i;

            sb.AppendLine();

            if (reg.Contract is not null)
            {
                sb.Append($$"""
                                    // {{reg.ViewModelFullyQualifiedName}} -> {{reg.ViewFullyQualifiedName}} [contract: "{{reg.Contract}}"]
                                    if (instance is {{reg.ViewModelFullyQualifiedName}})
                                    {
                                        if (contract == "{{reg.Contract}}")
                                        {
                                            return {{resolverMethodName}}(contract);
                                        }
                                    }
                        """);
            }
            else
            {
                sb.Append($$"""
                                    // {{reg.ViewModelFullyQualifiedName}} -> {{reg.ViewFullyQualifiedName}}
                                    if (instance is {{reg.ViewModelFullyQualifiedName}})
                                    {
                                        return {{resolverMethodName}}(contract);
                                    }
                        """);
            }
        }

        sb.AppendLine().Append("""

                                  // No compile-time mapping found; fall back to runtime resolution.
                                  return null;
                              }
                  """);

        // Per-view resolver methods
        for (var i = 0; i < registrations.Count; i++)
        {
            GenerateResolverMethod(sb, registrations[i], i);
        }

        sb.AppendLine().Append("""
                      }
                  }
                  """);
    }

    /// <summary>
    /// Generates a per-view-model resolver method.
    /// </summary>
    /// <param name="sb">The string builder.</param>
    /// <param name="reg">The view registration info.</param>
    /// <param name="index">The unique index for method naming.</param>
    private static void GenerateResolverMethod(StringBuilder sb, ViewRegistrationInfo reg, int index)
    {
        var methodName = "__ResolveView_" + index;

        var strategyDoc = reg.IsSingleInstance
            ? "        /// Returns a cached singleton instance (marked with [SingleInstanceView])."
            : reg.HasParameterlessConstructor
                ? "        /// Tries the service locator first, then falls back to direct construction."
                : "        /// Service locator only — no direct construction available.";

        sb.AppendLine().Append($$"""

                              /// <summary>
                              /// Resolves a view for <see cref="{{reg.ViewModelFullyQualifiedName}}"/>.
                  {{strategyDoc}}
                              /// </summary>
                              /// <param name="contract">The contract string (empty string for default).</param>
                              /// <returns>The resolved view, or <see langword="null"/> if resolution fails.</returns>
                              private static global::ReactiveUI.Binding.IViewFor {{methodName}}(string contract)
                              {
                                  // Normalize contract: empty string means no contract (null for Splat lookup).
                                  string svcContract = contract.Length == 0 ? null : contract;

                                  // Prefer service-locator-registered view (supports DI-configured instances).
                                  var view = global::Splat.AppLocator.Current
                                      .GetService<global::ReactiveUI.Binding.IViewFor<{{reg.ViewModelFullyQualifiedName}}>>(
                                          svcContract);
                                  if (view != null)
                                  {
                                      return view;
                                  }
                  """);

        if (reg.HasParameterlessConstructor)
        {
            if (reg.IsSingleInstance)
            {
                var fieldName = "__singletonView_" + index;
                sb.Append($$"""

                                      // Fallback: singleton construction ({{reg.ViewFullyQualifiedName}} has [SingleInstanceView]).
                                      if ({{fieldName}} == null)
                                      {
                                          {{fieldName}} = new {{reg.ViewFullyQualifiedName}}();
                                      }

                                      return {{fieldName}};
                  """);
            }
            else
            {
                sb.Append($$"""

                                      // Fallback: direct construction ({{reg.ViewFullyQualifiedName}} has a parameterless constructor).
                                      return new {{reg.ViewFullyQualifiedName}}();
                  """);
            }
        }
        else
        {
            sb.Append("""

                                  return null;
                  """);
        }

        sb.AppendLine().Append("""
                              }
                  """);
    }
}
