// Copyright (c) 2019-2026 ReactiveUI and Contributors. All rights reserved.
// ReactiveUI and Contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Runtime.CompilerServices;

namespace ReactiveUI.Binding.SourceGenerators.CodeGeneration;

/// <summary>The C# constructs generated code is built from, each written through a <see cref="SourceWriter"/>.</summary>
/// <remarks>
/// <para>
/// Each member names one construct - a namespace, a type, a doc comment, a condition, a local - and writes its
/// fixed text and its braces, so an emitter says what it builds and the layout follows from the writer's level.
/// </para>
/// <para>
/// Constructs whose variable part is built from several values come in two halves: a <c>Begin</c> member writes
/// the opening keyword, the emitter appends the parts, and the closing member finishes the line. That keeps the
/// parts out of an intermediate string. Constructs taking one finished value are a single call.
/// </para>
/// </remarks>
internal static class SourceWriterExtensions
{
    /// <summary>The documentation comment prefix.</summary>
    private const string DocCommentPrefix = "/// ";

    /// <summary>Writes C# constructs through a writer.</summary>
    /// <param name="writer">The writer the construct is written to.</param>
    extension(SourceWriter writer)
    {
        /// <summary>Writes the markers that open a generated file.</summary>
        /// <param name="emitGeneratedCodeMarkers">
        /// Whether to write <c>// &lt;auto-generated/&gt;</c> and <c>#pragma warning disable</c>, which suppress
        /// diagnostics in the consumer's build.
        /// </param>
        /// <param name="enableNullable">Whether to write <c>#nullable enable</c>.</param>
        /// <returns>The writer.</returns>
        internal SourceWriter FileHeader(bool emitGeneratedCodeMarkers, bool enableNullable)
        {
            if (emitGeneratedCodeMarkers)
            {
                _ = writer.Line("// <auto-generated/>").Line("#pragma warning disable");
            }

            return enableNullable ? writer.Line("#nullable enable") : writer;
        }

        /// <summary>Writes a <c>using</c> directive.</summary>
        /// <param name="namespaceName">The imported namespace.</param>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter Using(string namespaceName) => writer.Append("using ").Append(namespaceName).Line(";");

        /// <summary>Opens a block-scoped namespace, the only form C# 7.3 parses.</summary>
        /// <param name="namespaceName">The namespace.</param>
        /// <returns>The writer, one level deeper.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter OpenNamespace(string namespaceName) =>
            writer.Append("namespace ").Line(namespaceName).OpenBlock();

        /// <summary>Opens a type declaration.</summary>
        /// <param name="declaration">The declaration up to the body, such as <c>internal static partial class X</c>.</param>
        /// <returns>The writer, one level deeper.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter OpenType(string declaration) => writer.Line(declaration).OpenBlock();

        /// <summary>Writes a one-line summary doc comment.</summary>
        /// <param name="text">The summary, already XML-safe.</param>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter Summary(string text) =>
            writer.Append("/// <summary>").Append(text).Line("</summary>");

        /// <summary>Opens a multi-line summary doc comment.</summary>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter OpenSummary() => writer.Line("/// <summary>");

        /// <summary>Closes a multi-line summary doc comment.</summary>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter CloseSummary() => writer.Line("/// </summary>");

        /// <summary>Writes one line of a doc comment.</summary>
        /// <param name="text">The line, already XML-safe.</param>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter DocLine(string text) => writer.Append(DocCommentPrefix).Line(text);

        /// <summary>Starts a line of a doc comment, for the caller to complete.</summary>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter BeginDocLine() => writer.Append(DocCommentPrefix);

        /// <summary>Writes a line comment.</summary>
        /// <param name="text">The comment.</param>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter Comment(string text) => writer.Append("// ").Line(text);

        /// <summary>Starts a line comment, for the caller to complete.</summary>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter BeginComment() => writer.Append("// ");

        /// <summary>Writes an attribute on its own line.</summary>
        /// <param name="attribute">The attribute, without brackets.</param>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter Attribute(string attribute) => writer.Append('[').Append(attribute).Line("]");

        /// <summary>Starts a member signature's parameter list, one parameter per line one level deeper.</summary>
        /// <returns>The writer, one level deeper.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter OpenParameterList() => writer.Line("(").Indent();

        /// <summary>Writes a parameter that is followed by another.</summary>
        /// <param name="declaration">The parameter, such as <c>string name</c>.</param>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter Parameter(string declaration) => writer.Append(declaration).Line(",");

        /// <summary>Writes the last parameter and closes the list.</summary>
        /// <param name="declaration">The parameter, such as <c>int line = 0</c>.</param>
        /// <returns>The writer, back at the signature's level.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter LastParameter(string declaration) => writer.Append(declaration).Line(")").Outdent();

        /// <summary>Writes an <c>if</c> with a finished condition, and opens its block.</summary>
        /// <param name="condition">The condition.</param>
        /// <returns>The writer, inside the block.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter If(string condition) => writer.Append("if (").Append(condition).CloseCondition();

        /// <summary>Starts an <c>if</c>, for the caller to append the condition and <see cref="CloseCondition"/>.</summary>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter BeginIf() => writer.Append("if (");

        /// <summary>Starts an <c>else if</c>, for the caller to append the condition and <see cref="CloseCondition"/>.</summary>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter BeginElseIf() => writer.Append("else if (");

        /// <summary>Starts an <c>if</c> or <c>else if</c>, by position in a chain of branches.</summary>
        /// <param name="index">The branch's position; the first opens with <c>if</c>.</param>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter BeginBranch(int index) => index == 0 ? writer.BeginIf() : writer.BeginElseIf();

        /// <summary>Closes a condition and opens the block it guards.</summary>
        /// <returns>The writer, inside the block.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter CloseCondition() => writer.Line(")").OpenBlock();

        /// <summary>Writes an <c>else</c> and opens its block.</summary>
        /// <returns>The writer, inside the block.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter Else() => writer.Line("else").OpenBlock();

        /// <summary>Writes a <c>try</c> and opens its block.</summary>
        /// <returns>The writer, inside the block.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter Try() => writer.Line("try").OpenBlock();

        /// <summary>Writes a <c>finally</c> and opens its block.</summary>
        /// <returns>The writer, inside the block.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter Finally() => writer.Line("finally").OpenBlock();

        /// <summary>Writes a <c>return</c> of a finished expression.</summary>
        /// <param name="expression">The returned expression.</param>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter Return(string expression) => writer.Append("return ").Append(expression).Line(";");

        /// <summary>Starts a <c>return</c>, for the caller to append the expression and end the statement.</summary>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter BeginReturn() => writer.Append("return ");

        /// <summary>Writes a local declared with <c>var</c>.</summary>
        /// <param name="name">The local's name.</param>
        /// <param name="expression">Its initializer.</param>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter Var(string name, string expression) =>
            writer.BeginVar(name).Append(expression).Line(";");

        /// <summary>Starts a local declared with <c>var</c>, for the caller to append the initializer.</summary>
        /// <param name="name">The local's name.</param>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter BeginVar(string name) => writer.Append("var ").Append(name).Append(" = ");

        /// <summary>Ends a statement.</summary>
        /// <returns>The writer.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter EndStatement() => writer.Line(";");

        /// <summary>Ends the line and moves one level deeper, for the continuation lines of an expression.</summary>
        /// <returns>The writer, one level deeper.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal SourceWriter OpenContinuation() => writer.EndLine().Indent();
    }
}
