<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net11.0</TargetFrameworks>
    <IsAotCompatible>false</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ReactiveUI"/>
    <PackageReference Include="System.Reactive"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\ReactiveUI.Binding.Benchmarks\Mocks\BenchmarkViewModel.cs" Link="Mocks\BenchmarkViewModel.cs"/>
    <Compile Include="..\ReactiveUI.Binding.Benchmarks\Mocks\BenchmarkChildViewModel.cs" Link="Mocks\BenchmarkChildViewModel.cs"/>
    <Compile Include="..\ReactiveUI.Binding.Benchmarks\Mocks\BenchmarkView.cs" Link="Mocks\BenchmarkView.cs"/>
    <Compile Include="..\ReactiveUI.Binding.Benchmarks\Mocks\BenchmarkSource.cs" Link="Mocks\BenchmarkSource.cs"/>
  </ItemGroup>

</Project>
