// Copyright (c) 2019-2026 ReactiveUI and Contributors. All rights reserved.
// ReactiveUI and Contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Globalization;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using ReactiveUI.Binding.Analyzer.Analyzers;

namespace ReactiveUI.Binding.Documentation.AnalyzersIndex;

/// <summary>
/// Lists the build-time diagnostics the package ships, and shows the two MSBuild properties that control what a
/// build does with the generator: <c>ReactiveUIBindingUseInterceptors</c> and <c>ReactiveUIBindingEmitGeneratedCodeMarkers</c>.
/// </summary>
public static class AnalyzersIndexExamples
{
    /// <summary>The number of diagnostics the analyzers report.</summary>
    private const int AnalyzerDiagnosticCount = 11;

    /// <summary>The compiler version that can intercept calls.</summary>
    private const string InterceptingCompiler = "roslyn4.13";

    /// <summary>A compiler version that cannot intercept calls.</summary>
    private const string NonInterceptingCompiler = "roslyn4.8";

    /// <summary>The namespace the generator puts interceptors in.</summary>
    private const string InterceptorNamespace = "ReactiveUI.Binding.Generated.Interceptors";

    /// <summary>The name of the property that turns interceptors on and off.</summary>
    private const string UseInterceptorsProperty = "ReactiveUIBindingUseInterceptors";

    /// <summary>The name of the property that turns the generated-code markers on and off.</summary>
    private const string EmitMarkersProperty = "ReactiveUIBindingEmitGeneratedCodeMarkers";

    /// <summary>The name of the compiler feature that lists the namespaces allowed to intercept calls.</summary>
    private const string InterceptorsNamespacesProperty = "InterceptorsNamespaces";

    /// <summary>The value of a property that is switched on.</summary>
    private const string On = "true";

    /// <summary>The value of a property that is switched off.</summary>
    private const string Off = "false";

    /// <summary>The comment that marks a file as generated.</summary>
    private const string AutoGeneratedMarker = "<auto-generated/>";

    /// <summary>The attribute that marks a method as an interceptor.</summary>
    private const string InterceptsLocationAttribute = "InterceptsLocation";

    /// <summary>A view of the to-do list that watches the number of items left.</summary>
    private const string RemainingWatcherSource = """
        using System;
        using ReactiveUI.Binding;
        using ReactiveUI.Binding.Documentation.Todo;

        namespace TodoApp;

        public static class RemainingWatcher
        {
            public static IObservable<int> Watch(TodoListViewModel viewModel)
            {
                return viewModel.WhenChanged(x => x.RemainingCount);
            }
        }
        """;

    /// <summary>Lists every diagnostic the analyzers report, with its severity and title.</summary>
    public static void ListShippedDiagnostics()
    {
        var shipped = CollectDescriptors();

        (string Id, DiagnosticSeverity Severity, string Title)[] expected =
        [
            ("RXUIBIND001", DiagnosticSeverity.Info, "Expression must be inline lambda"),
            ("RXUIBIND002", DiagnosticSeverity.Warning, "Type has no observable properties"),
            ("RXUIBIND003", DiagnosticSeverity.Warning, "Expression contains private or protected member"),
            ("RXUIBIND004", DiagnosticSeverity.Warning, "Type does not support before-change notifications"),
            ("RXUIBIND005", DiagnosticSeverity.Info, "Validation binding not generated"),
            ("RXUIBIND006", DiagnosticSeverity.Warning, "Expression contains unsupported path segment"),
            ("RXUIBIND007", DiagnosticSeverity.Warning, "Control has no bindable event"),
            ("RXUIBIND008", DiagnosticSeverity.Warning, "Property is not an IInteraction"),
            ("RXUIBIND009", DiagnosticSeverity.Warning, "Generated binding dispatch is out of reach here"),
            ("RXUIBIND010", DiagnosticSeverity.Warning, "Observed path passes through a type that raises no notification"),
            ("RXUIBIND011", DiagnosticSeverity.Warning, "Binding call resolved to ReactiveUI's own mixin"),
        ];

        SampleCheck.Equal(AnalyzerDiagnosticCount, shipped.Count);

        foreach (var (id, severity, title) in expected)
        {
            SampleCheck.Equal(severity, shipped[id].DefaultSeverity);
            SampleCheck.Equal(title, shipped[id].Title.ToString(CultureInfo.InvariantCulture));
        }
    }

    /// <summary>Shows that a build lets the generator intercept calls by default.</summary>
    /// <returns>A task that completes when the checks finish.</returns>
    public static async Task ReadInterceptorsDefault()
    {
        var value = await BuildProbe.ReadPropertyAsync(UseInterceptorsProperty);

        SampleCheck.Equal(On, value);
    }

    /// <summary>Shows that, with interceptors on, a build on Roslyn 4.13 or later lists the interceptor namespace for the compiler.</summary>
    /// <returns>A task that completes when the checks finish.</returns>
    public static async Task ListInterceptorNamespaceOnRoslyn413()
    {
        var namespaces = await BuildProbe.ReadPropertyAsync(InterceptorsNamespacesProperty, $"CompilerApiVersion={InterceptingCompiler}");

        SampleCheck.Equal(InterceptorNamespace, namespaces);
    }

    /// <summary>Shows that setting the property to <c>false</c> leaves the interceptor namespace unlisted, so the generator emits overloads instead.</summary>
    /// <returns>A task that completes when the checks finish.</returns>
    public static async Task DisableInterceptors()
    {
        var namespaces = await BuildProbe.ReadPropertyAsync(
            InterceptorsNamespacesProperty,
            $"CompilerApiVersion={InterceptingCompiler}",
            $"{UseInterceptorsProperty}={Off}");

        SampleCheck.Equal(string.Empty, namespaces);
    }

    /// <summary>Shows that a compiler older than Roslyn 4.13 never lists the interceptor namespace.</summary>
    /// <returns>A task that completes when the checks finish.</returns>
    public static async Task SkipInterceptorsBeforeRoslyn413()
    {
        var namespaces = await BuildProbe.ReadPropertyAsync(InterceptorsNamespacesProperty, $"CompilerApiVersion={NonInterceptingCompiler}");

        SampleCheck.Equal(string.Empty, namespaces);
    }

    /// <summary>Shows what the generator writes when the compiler lists the interceptor namespace, and when it does not.</summary>
    public static void GenerateInterceptorsWhenTheNamespaceIsListed()
    {
        Dictionary<string, string> noProperties = [];
        KeyValuePair<string, string>[] listed = [new(InterceptorsNamespacesProperty, InterceptorNamespace)];

        var intercepted = GeneratorRun.Generate(RemainingWatcherSource, noProperties, listed);
        var overloaded = GeneratorRun.Generate(RemainingWatcherSource, noProperties, []);

        SampleCheck.Equal(true, intercepted.Contains(InterceptsLocationAttribute, StringComparison.Ordinal));
        SampleCheck.Equal(false, overloaded.Contains(InterceptsLocationAttribute, StringComparison.Ordinal));
    }

    /// <summary>Shows that a build writes the generated-code markers by default.</summary>
    /// <returns>A task that completes when the checks finish.</returns>
    public static async Task ReadGeneratedCodeMarkersDefault()
    {
        var value = await BuildProbe.ReadPropertyAsync(EmitMarkersProperty);

        SampleCheck.Equal(On, value);
    }

    /// <summary>Shows that setting the property to <c>false</c> leaves the auto-generated marker out of the generated files.</summary>
    /// <returns>A task that completes when the checks finish.</returns>
    public static async Task DisableGeneratedCodeMarkers()
    {
        var value = await BuildProbe.ReadPropertyAsync(EmitMarkersProperty, $"{EmitMarkersProperty}={Off}");

        SampleCheck.Equal(Off, value);

        Dictionary<string, string> withMarkers = new() { [EmitMarkersProperty] = On };
        Dictionary<string, string> withoutMarkers = new() { [EmitMarkersProperty] = Off };

        var marked = GeneratorRun.Generate(RemainingWatcherSource, withMarkers, []);
        var unmarked = GeneratorRun.Generate(RemainingWatcherSource, withoutMarkers, []);

        SampleCheck.Equal(true, marked.Contains(AutoGeneratedMarker, StringComparison.Ordinal));
        SampleCheck.Equal(false, unmarked.Contains(AutoGeneratedMarker, StringComparison.Ordinal));
    }

    /// <summary>Collects the descriptors of every analyzer the package ships.</summary>
    /// <returns>The descriptors, by diagnostic id.</returns>
    private static Dictionary<string, DiagnosticDescriptor> CollectDescriptors()
    {
        DiagnosticAnalyzer[] analyzers = [new BindingInvocationAnalyzer(), new TypeAnalyzer(), new DispatchReachAnalyzer(), new MixinShadowAnalyzer()];
        Dictionary<string, DiagnosticDescriptor> shipped = [];

        foreach (var analyzer in analyzers)
        {
            foreach (var descriptor in analyzer.SupportedDiagnostics)
            {
                shipped.Add(descriptor.Id, descriptor);
            }
        }

        return shipped;
    }
}
