<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <LangVersion>14.0</LangVersion>
    <RootNamespace>ReactiveUI.Binding.Documentation</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="ReactiveUI.Binding" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ReactiveUI" />
    <PackageReference Include="ReactiveUI.SourceGenerators" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../ReactiveUI.Binding/ReactiveUI.Binding.csproj" />
    <ProjectReference Include="../../../../ReactiveUI.Binding.SourceGenerators/ReactiveUI.Binding.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../../../ReactiveUI.Binding.Analyzer/ReactiveUI.Binding.Analyzer.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
