<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(BindingTestTargets)</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit"/>
    <PackageReference Include="Splat"/>
    <PackageReference Include="System.Reactive"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReactiveUI.Binding.GeneratedCode.TestModels\ReactiveUI.Binding.GeneratedCode.TestModels.csproj"/>
    <ProjectReference Include="..\..\ReactiveUI.Binding\ReactiveUI.Binding.csproj"/>
  </ItemGroup>

</Project>
