name: Benchmarks

on:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    benchmark:
        uses: reactiveui/actions-common/.github/workflows/workflow-common-benchmarks.yml@main
        with:
            projects: |
                benchmarks/ReactiveUI.Binding.Benchmarks/ReactiveUI.Binding.Benchmarks.csproj
                benchmarks/ReactiveUI.Binding.Benchmarks.ReactiveUI/ReactiveUI.Binding.Benchmarks.ReactiveUI.csproj
                benchmarks/ReactiveUI.Binding.Generator.Benchmarks/ReactiveUI.Binding.Generator.Benchmarks.csproj
            solutionFile: ReactiveUI.Binding.SourceGenerators.slnx
            installWorkloads: true
