name: Native AOT

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

permissions:
    contents: read

jobs:
    native-aot-smoke:
        uses: reactiveui/actions-common/.github/workflows/workflow-common-aot-smoke.yml@main
        with:
            projectFile: src/tests/ReactiveUI.Binding.AotValidation/ReactiveUI.Binding.AotValidation.csproj

    trimmed-smoke:
        uses: reactiveui/actions-common/.github/workflows/workflow-common-aot-smoke.yml@main
        with:
            projectFile: src/tests/ReactiveUI.Binding.TrimValidation/ReactiveUI.Binding.TrimValidation.csproj
